// apps/main-app/src/routes/in/(layout-1)/partners/join/thank-you/+page.svelte
<script lang="ts">
	import { breadcrumbLD } from '$lib/seo';
	import { CheckCircle } from '@lucide/svelte';

	const breadcrumb = breadcrumbLD([
		{ name: 'Home', url: 'https://solarvipani.com/in/' },
		{ name: 'Partners', url: 'https://solarvipani.com/in/partners/' },
		{ name: 'Thank You', url: 'https://solarvipani.com/in/partners/join/thank-you/' }
	]);
</script>

<svelte:head>
	<title>Thank You | Partner Sign-Up | Solar Vipani</title>
	<meta name="description" content="Thank you for signing up as a Solar Vipani partner. Our team will review your application and contact you within 48 hours." />
	<meta name="robots" content="noindex" />
	{@html `<script type="application/ld+json">${JSON.stringify(breadcrumb)}</script>`}
</svelte:head>

<div class="mx-auto flex max-w-xl flex-col items-center px-4 py-16 text-center">
	<CheckCircle class="mb-6 h-16 w-16 text-green-600" />

	<h1 class="mb-4 text-3xl font-bold text-foreground">Thank You for Signing Up</h1>

	<p class="mb-6 text-lg text-muted-foreground">
		We have received your partner application. Our team will review your details and get in touch within <strong class="text-foreground">48 hours</strong>.
	</p>

	<div class="mb-8 w-full rounded-lg border bg-muted/50 p-6">
		<h2 class="mb-3 text-lg font-semibold text-foreground">What Happens Next</h2>
		<ol class="space-y-2 text-left text-sm text-muted-foreground">
			<li><span class="font-medium text-foreground">1.</span> Our team reviews your business details</li>
			<li><span class="font-medium text-foreground">2.</span> We verify your business and contact you</li>
			<li><span class="font-medium text-foreground">3.</span> Your profile goes live and you start receiving leads</li>
		</ol>
	</div>

	<a href="/in/partners/" class="text-sm text-primary hover:underline">
		Back to Partners
	</a>
</div>

// apps/main-app-nextjs/app/[country]/partners/join/thank-you/page.tsx
/**
 * `/{cc}/partners/join/thank-you` — the partner signup confirmation.
 *
 * **Nothing routes here today**, and that is carried across rather than fixed:
 * `BusinessForm` sends every successful signup to `/{cc}/thank-you-business`,
 * on all three of the pages that render it, exactly as the SvelteKit form
 * does. This page exists, is linked from nothing, and says something slightly
 * different from the page that IS reached — a 48-hour promise where
 * thank-you-business promises a call.
 *
 * It is ported anyway because it is in the inventory and because deciding
 * which of the two confirmations a partner signup should land on is a content
 * decision, not a porting one. Recorded in the README as an open item.
 *
 * `noindex`, as the original has: a confirmation page in a search result is a
 * page reached without the thing it confirms.
 */
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { CheckCircle } from 'lucide-react';
import { PageShell, Section, Stack } from '@/components/layout';
import { getCountry, isCountry } from '@/lib/countries';
import { breadcrumbLD } from '@/lib/directory/structuredData';
import { pageMetadata } from '@/lib/metadata';

/** 15 days. Static copy, so the window is the tree's default rather than a measurement. */
export const revalidate = 1296000;

/** Empty on purpose — see "ISR needs `generateStaticParams` too" in the README. */
export async function generateStaticParams() {
  return [];
}

const STEPS = [
  'Our team reviews your business details.',
  'We verify your business and contact you.',
  'Your profile goes live and you start receiving leads.'
];

export async function generateMetadata({
  params
}: {
  params: Promise<{ country: string }>;
}): Promise<Metadata> {
  const { country } = await params;
  if (!isCountry(country)) return {};
  const config = getCountry(country);

  return {
    ...pageMetadata({
      title: 'Thank You | Partner Sign-Up',
      description: `Thank you for signing up as a ${config.brandName} partner. Our team will review your application and contact you within 48 hours.`,
      path: `/${country}/partners/join/thank-you`,
      locale: config.locale,
      imageAlt: `${config.brandName} partner sign-up received`
    }),
    robots: { index: false, follow: true }
  };
}

export default async function Page({ params }: { params: Promise<{ country: string }> }) {
  const { country } = await params;
  if (!isCountry(country)) notFound();

  const trail = [
    { name: 'Home', href: `/${country}` },
    { name: 'Partners', href: `/${country}/partners` },
    { name: 'Thank You' }
  ];

  return (
    <PageShell>
      <Section width="narrow">
        <Stack gap="md">
          <header>
            <CheckCircle aria-hidden className="h-10 w-10 text-action" />
            <h1 className="mt-md text-2xl leading-tight">Thank you for signing up</h1>
            <p className="mt-sm text-ink-muted">
              We have your partner application. Our team will review your details and get in touch
              within <strong className="font-semibold text-ink">48 hours</strong>.
            </p>
          </header>
        </Stack>
      </Section>

      <Section width="narrow">
        <div className="rounded-lg border border-line bg-surface-sunken p-lg">
          <h2 className="text-lg">What happens next</h2>
          {/* An ordered list, because these are steps in sequence — the
              original numbered them by hand inside <li>s, which reads the
              same and announces as an unordered list of strings starting
              with digits. */}
          <ol className="mt-md flex list-decimal flex-col gap-sm pl-md text-sm text-ink-muted">
            {STEPS.map((step) => (
              <li key={step}>{step}</li>
            ))}
          </ol>
        </div>
      </Section>

      <Section width="narrow">
        <a href={`/${country}/partners`} className="text-sm">
          Back to Partners
        </a>
      </Section>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLD(trail)) }}
      />
    </PageShell>
  );
}
