// apps/main-app/src/routes/in/(layout-1)/data-deletion/+page.svelte
<script>
  import { Button } from "$lib/components/ui/button";
  import { Input } from "$lib/components/ui/input";
  import { Textarea } from "$lib/components/ui/textarea";
  import { Alert, AlertDescription, AlertTitle } from "$lib/components/ui/alert";
  import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "$lib/components/ui/card";

  let formData = $state({
    email: "",
    phone: "",
    reason: "",
  });

  let submitting = $state(false);
  let submitted = $state(false);
  let error = $state("");

  const handleSubmit = async (event) => {
    event.preventDefault();
    submitting = true;
    error = "";

    try {
      const response = await fetch("/in/api/submitDataDeletion", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      });

      if (response.ok) {
        submitted = true;
        formData = { email: "", phone: "", reason: "" };
      } else {
        error = "Failed to submit request. Please try again.";
      }
    } catch (err) {
      error = "An error occurred. Please try again later.";
    } finally {
      submitting = false;
    }
  };
</script>

<svelte:head>
  <title>Data Deletion Request | Solar Vipani - Delete Your Personal Data</title>
  <meta
    name="description"
    content="Request deletion of your personal data from Solar Vipani. Submit a data deletion request to remove your information from our database."
  />
</svelte:head>

<main class="min-h-screen p-[theme(--container-padding)] transition-colors duration-300 bg-[hsl(var(--background))] text-[hsl(var(--foreground))]">
  <div class="max-w-2xl mx-auto">
    <h1 class="text-[2.25rem] font-semibold text-center mb-4 leading-tight md:text-[1.875rem]">Data Deletion Request</h1>

    <div class="mb-8">
      <p class="text-lg leading-relaxed mb-4">
        We respect your privacy and your right to control your personal data.
        Whether you are a customer or a registered solar installer on our
        platform, if you would like to request deletion of your personal
        information from our database, please fill out the form below.
      </p>

      <Card class="mb-8">
        <CardHeader>
          <CardTitle>What data will be deleted?</CardTitle>
        </CardHeader>
        <CardContent class="gap-3">
          <div>
            <h4 class="font-semibold mb-2 text-base">For Customers:</h4>
            <ul class="pl-4 space-y-1">
              <li class="leading-relaxed">Your contact information (phone number, email address)</li>
              <li class="leading-relaxed">Lead submissions and requirements</li>
              <li class="leading-relaxed">Account information and preferences</li>
              <li class="leading-relaxed">Communication history with our team</li>
            </ul>
          </div>

          <div>
            <h4 class="font-semibold mb-2 text-base">For Solar Installers/Businesses:</h4>
            <ul class="pl-4 space-y-1">
              <li class="leading-relaxed">Business profile and contact information</li>
              <li class="leading-relaxed">Service area and specialization details</li>
              <li class="leading-relaxed">Lead claims and interaction history</li>
              <li class="leading-relaxed">Project portfolios and showcase images</li>
              <li class="leading-relaxed">Branch locations and team information</li>
              <li class="leading-relaxed">Business verification documents</li>
            </ul>
          </div>
        </CardContent>
      </Card>
    </div>

    {#if submitted}
      <Alert class="mb-8 bg-[hsl(var(--success))] border-[hsl(var(--success))]">
        <AlertTitle>Request Submitted Successfully!</AlertTitle>
        <AlertDescription>
          <p class="mb-3">
            Your data deletion request has been received. We will process your
            request within 30 days and send you a confirmation email once
            completed.
          </p>
          <p>
            If you have any questions, please contact us at <a
              href="mailto:admin@solarvipani.com"
              class="text-[hsl(var(--accent))] hover:underline">admin@solarvipani.com</a
            >.
          </p>
        </AlertDescription>
      </Alert>
    {:else}
      <Card class="mb-8">
        <CardHeader>
          <CardTitle>Request Data Deletion</CardTitle>
        </CardHeader>
        <CardContent>
          <form onsubmit={handleSubmit} class="gap-4 flex flex-col">
            <div class="gap-2 flex flex-col">
              <label for="email" class="font-semibold text-sm">Email Address *</label>
              <Input
                type="email"
                id="email"
                bind:value={formData.email}
                required
                placeholder="Enter your email address (business or personal)"
              />
            </div>

            <div class="gap-2 flex flex-col">
              <label for="phone" class="font-semibold text-sm">Phone Number</label>
              <Input
                type="tel"
                id="phone"
                bind:value={formData.phone}
                placeholder="Enter your phone number (optional)"
              />
            </div>

            <div class="gap-2 flex flex-col">
              <label for="reason" class="font-semibold text-sm">Reason for Deletion (Optional)</label>
              <Textarea
                id="reason"
                bind:value={formData.reason}
                placeholder="Please let us know why you're requesting data deletion (customers and installers welcome)"
                rows={4}
              />
            </div>

            {#if error}
              <Alert class="bg-[hsl(var(--destructive))] border-[hsl(var(--destructive))]">
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            {/if}

            <Button
              type="submit"
              disabled={submitting}
              class="w-full"
            >
              {submitting ? "Submitting..." : "Submit Deletion Request"}
            </Button>
          </form>
        </CardContent>
      </Card>
    {/if}

    <Card>
      <CardHeader>
        <CardTitle>Important Information</CardTitle>
      </CardHeader>
      <CardContent class="gap-3 flex flex-col">
        <ul class="pl-4 space-y-1">
          <li class="leading-relaxed">Data deletion requests are processed within 30 business days</li>
          <li class="leading-relaxed">
            You will receive a confirmation email once your data has been deleted
          </li>
          <li class="leading-relaxed">
            Some data may be retained for legal compliance purposes (financial
            records, tax documentation, government subsidy records)
          </li>
          <li class="leading-relaxed">
            Deleting your data will remove you from our marketing communications
          </li>
          <li class="leading-relaxed">
            <strong>For Installers:</strong> Your business will be removed from our
            directory and you will no longer receive leads
          </li>
          <li class="leading-relaxed">
            <strong>For Customers:</strong> You will no longer receive solar installation
            quotes or updates
          </li>
        </ul>

        <p class="leading-relaxed">
          For any questions or concerns about your data deletion request, please
          contact us at
          <a href="mailto:admin@solarvipani.com" class="text-[hsl(var(--accent))] hover:underline">admin@solarvipani.com</a>.
        </p>
      </CardContent>
    </Card>
  </div>
</main>

// apps/main-app-nextjs/app/(layout-1)/data-deletion/page.tsx
/**
 * Data Deletion Request — the DPDP right of erasure. Ported from
 * apps/main-app/src/routes/(layout-1)/data-deletion/+page.svelte.
 *
 * The sibling of `/data-access` and built the same way; that file's header
 * carries the reasoning about copy, `revalidate` and the shared form. Privacy
 * Policy §3 and §7 both link here by name, so the promises here and there
 * have to stay in step.
 *
 * `Panel` is duplicated rather than shared with `/data-access`. Two copies of
 * a ten-line helper is cheaper than a components/ entry that only these two
 * pages will ever import, and the moment a third page wants it is the moment
 * it earns a home.
 */
import type { Metadata } from 'next';
import { DataRequestForm } from '@/components/forms';
import { PageShell, Section, Stack } from '@/components/layout';
import { getCountry } from '@/lib/countries';
import { pageMetadata } from '@/lib/metadata';

export const metadata: Metadata = pageMetadata({
  title: 'Data Deletion Request',
  description:
    'Request deletion of your personal data from Solar Vipani. Submit a data deletion request to remove your information from our database.',
  path: '/data-deletion',
  locale: getCountry('in').locale,
  imageAlt: 'Solar Vipani'
});

const WHAT_WILL_BE_DELETED = [
  {
    who: 'For Customers:',
    items: [
      'Your contact information (phone number, email address)',
      'Lead submissions and requirements',
      'Account information and preferences',
      'Communication history with our team'
    ]
  },
  {
    who: 'For Solar Installers/Businesses:',
    items: [
      'Business profile and contact information',
      'Service area and specialization details',
      'Lead claims and interaction history',
      'Project portfolios and showcase images',
      'Branch locations and team information',
      'Business verification documents'
    ]
  }
];

function Panel({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="rounded-lg border border-line p-lg">
      <h2 className="font-serif text-xl text-ink">{title}</h2>
      <div className="mt-md font-serif text-prose text-ink-muted">{children}</div>
    </section>
  );
}

function Ink({ children }: { children: React.ReactNode }) {
  return <strong className="font-semibold text-ink">{children}</strong>;
}

export default function Page() {
  return (
    <PageShell>
      <Section width="narrow">
        <Stack gap="md">
          <h1 className="font-serif text-2xl text-ink">Data Deletion Request</h1>
          <p className="font-serif text-prose text-ink-muted">
            We respect your privacy and your right to control your personal data. Whether you are a
            customer or a registered solar installer on our platform, if you would like to request
            deletion of your personal information from our database, please fill out the form below.
          </p>
        </Stack>
      </Section>

      <Section width="narrow">
        <Stack gap="lg">
          <Panel title="What data will be deleted?">
            <Stack gap="md">
              {WHAT_WILL_BE_DELETED.map((group) => (
                <div key={group.who}>
                  <h3 className="font-sans text-base font-semibold text-ink">{group.who}</h3>
                  <ul className="mt-xs flex list-disc flex-col gap-2xs pl-lg">
                    {group.items.map((item) => (
                      <li key={item}>{item}</li>
                    ))}
                  </ul>
                </div>
              ))}
            </Stack>
          </Panel>

          <Panel title="Request Data Deletion">
            <DataRequestForm
              endpoint="/api/submitDataDeletion"
              submitLabel="Submit Deletion Request"
              reasonLabel="Reason for deletion"
              reasonPlaceholder="Please let us know why you're requesting data deletion (customers and installers welcome)"
              confirmation={
                <>
                  <p className="font-semibold text-ink">Request submitted successfully</p>
                  <p className="mt-sm">
                    Your data deletion request has been received. We will process your request
                    within 30 days and send you a confirmation email once completed.
                  </p>
                  <p className="mt-sm">
                    If you have any questions, please contact us at{' '}
                    <a href="mailto:admin@solarvipani.com" className="text-action underline">
                      admin@solarvipani.com
                    </a>
                    .
                  </p>
                </>
              }
            />
          </Panel>

          <Panel title="Important Information">
            <ul className="flex list-disc flex-col gap-xs pl-lg">
              <li>Data deletion requests are processed within 30 business days</li>
              <li>You will receive a confirmation email once your data has been deleted</li>
              <li>
                Some data may be retained for legal compliance purposes (financial records, tax
                documentation, government subsidy records)
              </li>
              <li>Deleting your data will remove you from our marketing communications</li>
              <li>
                <Ink>For Installers:</Ink> Your business will be removed from our directory and you
                will no longer receive leads
              </li>
              <li>
                <Ink>For Customers:</Ink> You will no longer receive solar installation quotes or
                updates
              </li>
            </ul>
            <p className="mt-md">
              For any questions or concerns about your data deletion request, please contact us at{' '}
              <a href="mailto:admin@solarvipani.com" className="text-action underline">
                admin@solarvipani.com
              </a>
              .
            </p>
          </Panel>
        </Stack>
      </Section>
    </PageShell>
  );
}
