// apps/main-app/src/routes/[country=country]/(layout-1)/thank-you/+page.svelte
<script>
	import { Card } from '$lib/components/ui/card';
	import { Alert } from '$lib/components/ui/alert';

	let { data } = $props();

	const cc = $derived(data.country.code);

	// Extract customer details from server data
	let customerDetails = $derived(data?.customerDetails || null);
	let error = $derived(data?.error || null);

	// Format date for display
	function formatDate(dateString) {
		if (!dateString) return '';
		const date = new Date(dateString);
		return date.toLocaleString('en-IN', {
			year: 'numeric',
			month: 'long',
			day: 'numeric',
			hour: '2-digit',
			minute: '2-digit'
		});
	}
</script>

<svelte:head>
	<!-- Meta Pixel Code -->
	<script>
		!(function (f, b, e, v, n, t, s) {
			if (f.fbq) return;
			n = f.fbq = function () {
				n.callMethod ? n.callMethod.apply(n, arguments) : n.queue.push(arguments);
			};
			if (!f._fbq) f._fbq = n;
			n.push = n;
			n.loaded = !0;
			n.version = '2.0';
			n.queue = [];
			t = b.createElement(e);
			t.async = !0;
			t.src = v;
			s = b.getElementsByTagName(e)[0];
			s.parentNode.insertBefore(t, s);
		})(window, document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');
		fbq('init', '1226087962095221');
		fbq('track', 'Lead');
	</script>
	<noscript>
		<!-- svelte-ignore a11y_img_redundant_alt -->
		<img
			height="1"
			width="1"
			style="display:none"
			src="https://www.facebook.com/tr?id=1226087962095221&ev=PageView&noscript=1"
			alt="Facebook Pixel tracking"
		/>
	</noscript>
	<!-- End Meta Pixel Code -->

	<title>Thank You | Solar Vipani</title>
	<meta
		name="description"
		content="Thank you for submitting your details. We will contact you soon."
	/>
</svelte:head>

<main class="min-h-screen pt-2 flex flex-col items-center justify-start text-center transition-colors duration-[theme(--transition-default)] bg-background text-foreground">
	<!-- The lead-detail body below is IN-only: its loader reads LeadData and
	     business_profiles, both IN-only tables, and US leads live in
	     us_leaddata. The /us page has only ever shown this headline, and this
	     preserves that exactly. Giving /us a real lead-detail page means
	     reading us_leaddata — a behaviour addition, deliberately not done here. -->
	{#if cc !== 'in'}
		<h1 class="text-2xl md:text-4xl font-bold mb-4">Thank you for submitting your details.</h1>
	{:else if error}
		<h1 class="text-2xl md:text-4xl font-bold mb-2">Details not found</h1>
		<p class="text-base md:text-lg max-w-2xl mx-auto mb-3">The requested information could not be found. Please contact us if you need assistance.</p>
		<p class="text-base md:text-lg max-w-2xl mx-auto mb-3">
			If you'd like to speak with us, feel free to give us a call at <a
				href="tel:+918983066701"
				class="text-primary-strong underline hover:no-underline"
			>+91 8983066701</a
			>
		</p>
	{:else}
		<h1 class="text-2xl md:text-4xl font-bold mb-4">We have received your details.</h1>

		<!-- Customer details section -->
		{#if customerDetails}
		<div class="w-full max-w-2xl mx-auto mb-8 px-2 text-left">
			<Card class="p-2 md:p-4 border border-border">
				<div class="space-y-3">
					<div class="flex flex-col md:flex-row md:justify-between md:items-start pb-3 border-b border-border last:border-b-0">
						<span class="font-semibold text-foreground-secondary md:min-w-[140px] flex-shrink-0">Name:</span>
						<span class="font-medium text-foreground md:text-right flex-grow md:ml-4">{customerDetails.name}</span>
					</div>
					<div class="flex flex-col md:flex-row md:justify-between md:items-start pb-3 border-b border-border last:border-b-0">
						<span class="font-semibold text-foreground-secondary md:min-w-[140px] flex-shrink-0">Phone:</span>
						<span class="font-medium text-foreground md:text-right flex-grow md:ml-4">{customerDetails.phone}</span>
					</div>
					<div class="flex flex-col md:flex-row md:justify-between md:items-start pb-3 border-b border-border last:border-b-0">
						<span class="font-semibold text-foreground-secondary md:min-w-[140px] flex-shrink-0">Email:</span>
						<span class="font-medium text-foreground md:text-right flex-grow md:ml-4">{customerDetails.email || 'Not provided'}</span>
					</div>
					<div class="flex flex-col md:flex-row md:justify-between md:items-start pb-3 border-b border-border last:border-b-0">
						<span class="font-semibold text-foreground-secondary md:min-w-[140px] flex-shrink-0">Location:</span>
						<span class="font-medium text-foreground md:text-right flex-grow md:ml-4">{customerDetails.pinCode}{customerDetails.district ? `, ${customerDetails.district}` : ''}</span>
					</div>
					<div class="flex flex-col md:flex-row md:justify-between md:items-start pb-3 border-b border-border last:border-b-0">
						<span class="font-semibold text-foreground-secondary md:min-w-[140px] flex-shrink-0">Installation Type:</span>
						<span class="font-medium text-foreground md:text-right flex-grow md:ml-4">{customerDetails.type}</span>
					</div>
					<div class="flex flex-col md:flex-row md:justify-between md:items-start pb-3 border-b border-border last:border-b-0">
						<span class="font-semibold text-foreground-secondary md:min-w-[140px] flex-shrink-0">Requirements:</span>
						<span class="font-medium text-foreground md:text-right flex-grow md:ml-4">{customerDetails.comment}</span>
					</div>
					<div class="flex flex-col md:flex-row md:justify-between md:items-start">
						<span class="font-semibold text-foreground-secondary md:min-w-[140px] flex-shrink-0">Submitted:</span>
						<span class="font-medium text-foreground md:text-right flex-grow md:ml-4">{formatDate(customerDetails.submittedAt)}</span>
					</div>
				</div>
			</Card>
		</div>

		{#if customerDetails && !customerDetails.hasVerifiedBusinessInDistrict && customerDetails.district}
			<Alert class="w-full max-w-2xl mx-auto mb-8 px-2 py-2 bg-warning/10 border border-warning rounded-[theme(--radius-lg)] shadow-[theme(--shadow-sm)] text-center">
				<h3 class="text-lg md:text-xl font-semibold mb-2 text-warning">Service Area Update</h3>
				<p class="text-sm md:text-base text-warning/90 leading-relaxed">We are expanding to <strong>{customerDetails.district}</strong>. We will reach out to you once we have a verified installer there.</p>
			</Alert>
		{/if}
	{/if}

	<h2 class="text-xl md:text-2xl font-bold my-4 text-primary-strong">Next Steps</h2>
	{#if customerDetails && customerDetails.hasVerifiedBusinessInDistrict}
		<p class="text-base md:text-lg max-w-2xl mx-auto mb-3">
			We will call you within 24 hours to gather the exact requirement and clear any doubts that you
			may have.
		</p>
		<p class="text-base md:text-lg max-w-2xl mx-auto mb-3">
			After gathering your exact requirement, we will reshare your requirement with 2-3 verfied
			intallers in your area so that they can provide you with the quotaion.
		</p>
	{:else if customerDetails && !customerDetails.hasVerifiedBusinessInDistrict}
		<p class="text-base md:text-lg max-w-2xl mx-auto mb-3">
			Once we have verified installers in your district, we will connect you with 2-3 qualified installers who can provide you with competitive quotations.
		</p>
	{:else}
		<p class="text-base md:text-lg max-w-2xl mx-auto mb-3">
			We will call you within 24 hours to gather the exact requirement and clear any doubts that you
			may have.
		</p>
		<p class="text-base md:text-lg max-w-2xl mx-auto mb-3">
			After gathering your exact requirement, we will reshare your requirement with 2-3 verfied
			intallers in your area so that they can provide you with the quotaion.
		</p>
	{/if}
		<p class="text-base md:text-lg max-w-2xl mx-auto mb-3">
			If you'd like to speak with us right away, feel free to give us a call at <a
				href="tel:+918983066701"
				class="text-primary-strong underline hover:no-underline"
			>+91 8983066701</a
			>
		</p>
	{/if}
</main>

// apps/main-app-nextjs/app/[country]/thank-you/page.tsx
/**
 * `/{cc}/thank-you?ref={uuid}` — the customer's lead receipt.
 *
 * **Dynamic, not ISR.** Every other page in this tree is `revalidate` plus an
 * empty `generateStaticParams`; this one reads a query string and prints one
 * visitor's own contact details, so there is nothing cacheable about it. A
 * shared cache entry keyed on the path alone would serve one person's phone
 * number to the next visitor — which is the whole reason the exception is
 * written out here rather than left implicit in the absence of a `revalidate`.
 *
 * **The lead detail is IN-only**, as in SvelteKit: `reference_uuid` is
 * returned by `insertLead` for IN alone (lib/server/leads.ts records why), so
 * a US visitor never holds a `ref` to present. /us has only ever shown the
 * headline, and that is preserved — giving /us a real receipt means reading
 * US lead rows by reference, which is a behaviour addition and not a port.
 *
 * **Nothing in this app routes here yet.** `LeadForm` confirms in place
 * instead of redirecting — its header explains why, and that reasoning still
 * holds now that this page is real: an in-place panel cannot be reached by
 * pressing back into a stale form, and it does not put a lead's details in a
 * URL that gets pasted around. The page is reached from the confirmation
 * email's link and is ported for that. Whether the form should start
 * redirecting here is a product decision, recorded in the README.
 *
 * The uuid is the only access control: there is no session, so anyone holding
 * the link sees the row. That is the SvelteKit behaviour and the link only
 * ever reaches the person who submitted it.
 *
 * The Meta Pixel `Lead` event on the original is not ported — see the note in
 * `business-form/page.tsx`.
 */
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { PageShell, Section, Stack } from '@/components/layout';
import { getCountry, isCountry } from '@/lib/countries';
import { getLeadReceipt, type LeadReceipt } from '@/lib/forms/data';
import { pageMetadata } from '@/lib/metadata';

/** Reads a query string and prints one visitor's own row. Never cached. */
export const dynamic = 'force-dynamic';

export async function generateMetadata({
  params
}: {
  params: Promise<{ country: string }>;
}): Promise<Metadata> {
  const { country } = await params;
  if (!isCountry(country)) return {};
  const config = getCountry(country);

  return {
    ...pageMetadata({
      title: 'Thank You',
      description: 'Thank you for submitting your details. We will contact you soon.',
      path: `/${country}/thank-you`,
      locale: config.locale,
      imageAlt: `${config.brandName} enquiry received`
    }),
    robots: { index: false, follow: true }
  };
}

/** One term/value row of the receipt. */
function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex flex-col gap-2xs border-b border-line py-sm last:border-b-0 sm:flex-row sm:justify-between sm:gap-md">
      <dt className="text-sm font-semibold text-ink-muted">{label}</dt>
      <dd className="text-sm text-ink sm:text-right">{value}</dd>
    </div>
  );
}

/**
 * The submitted-at stamp, in the country's own locale.
 *
 * Null-safe because `leaddata.created_at` is nullable — the row is dropped
 * rather than printed as "Invalid Date", which is what `new Date(null)`
 * formats to.
 */
function formatSubmitted(value: string | null, locale: string): string | null {
  if (!value) return null;
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return null;
  return date.toLocaleString(locale, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
}

function Receipt({ lead, locale }: { lead: LeadReceipt; locale: string }) {
  const submitted = formatSubmitted(lead.submittedAt, locale);
  return (
    <dl className="rounded-lg border border-line bg-surface p-lg">
      <Row label="Name" value={lead.name} />
      <Row label="Phone" value={lead.phone} />
      <Row label="Email" value={lead.email || 'Not provided'} />
      <Row
        label="Location"
        value={lead.district ? `${lead.postalCode}, ${lead.district}` : lead.postalCode}
      />
      {/* The three optional columns are dropped when empty rather than
          printed as "Not provided". Unlike the business confirmation email —
          which an operator reads to check a form for completeness — this is
          the visitor's own receipt, and a row telling them they did not
          answer an optional question is noise. */}
      {lead.type ? <Row label="Installation type" value={lead.type} /> : null}
      {lead.comment ? <Row label="Requirements" value={lead.comment} /> : null}
      {submitted ? <Row label="Submitted" value={submitted} /> : null}
    </dl>
  );
}

export default async function Page({
  params,
  searchParams
}: {
  params: Promise<{ country: string }>;
  searchParams: Promise<{ ref?: string }>;
}) {
  const { country } = await params;
  if (!isCountry(country)) notFound();
  const config = getCountry(country);

  const { ref } = await searchParams;

  // US never has a reference, so it never reaches the lookup and always gets
  // the plain headline below.
  const lead = country === 'in' && ref ? await getLeadReceipt(ref) : null;

  // A `ref` that resolves to nothing is the "Details not found" branch. No
  // `ref` at all is not an error — it is the ordinary confirmation, which is
  // what /us always shows and what an IN visitor gets if the link lost its
  // query string.
  const notFoundRef = country === 'in' && Boolean(ref) && !lead;

  if (notFoundRef) {
    return (
      <PageShell>
        <Section width="narrow">
          <Stack gap="md">
            <h1 className="text-2xl leading-tight">Details not found</h1>
            <p className="text-ink-muted">
              We could not find the enquiry this link points at. Please contact us if you need
              assistance.
            </p>
            <p className="text-ink-muted">
              To speak to us, call{' '}
              <a href="tel:+918983066701" className="text-action">
                +91 8983066701
              </a>
              .
            </p>
          </Stack>
        </Section>
      </PageShell>
    );
  }

  return (
    <PageShell>
      <Section width="narrow">
        <h1 className="text-2xl leading-tight">
          {lead ? 'We have received your details' : 'Thank you for submitting your details'}
        </h1>
      </Section>

      {lead ? (
        <Section width="narrow">
          <Receipt lead={lead} locale={config.locale} />
        </Section>
      ) : null}

      {lead && !lead.hasVerifiedInstaller && lead.district ? (
        <Section width="narrow">
          {/* Said before the "next steps" below, because it changes what those
              steps are. The original renders it in the same order.

              `brand`, not a warning colour: globals.css says there is no
              warning token because no archetype had a use for one, and daisyUI's
              `--color-warning` is mapped to `--color-brand` for exactly this
              reason. This is also not really a warning — it is the honest
              version of the same good news. */}
          <div className="rounded-lg border border-brand bg-brand-surface p-lg">
            <h2 className="text-lg">Service area update</h2>
            <p className="mt-sm text-sm text-ink-muted">
              We are expanding to <strong className="font-semibold text-ink">{lead.district}</strong>
              . We will reach out once we have a verified installer there.
            </p>
          </div>
        </Section>
      ) : null}

      <Section width="narrow">
        <Stack gap="md">
          <h2 className="text-lg">Next steps</h2>
          {lead && !lead.hasVerifiedInstaller ? (
            <p className="text-ink-muted">
              Once we have verified installers in {lead.district ?? 'your area'}, we will connect
              you with 2–3 who can quote for your requirement.
            </p>
          ) : (
            <>
              <p className="text-ink-muted">
                We will call you within 24 hours to get your exact requirement and clear up any
                questions.
              </p>
              <p className="text-ink-muted">
                We then share that requirement with 2–3 verified installers in your area so they
                can quote for it.
              </p>
            </>
          )}
          <p className="text-ink-muted">
            If you would like to speak to us right away, call{' '}
            <a href="tel:+918983066701" className="text-action">
              +91 8983066701
            </a>
            .
          </p>
        </Stack>
      </Section>
    </PageShell>
  );
}
