// apps/main-app-nextjs/components/tools/EmiCalculator.tsx
/* eslint-disable-next-line no-restricted-syntax -- Interactive leaf. Three controls whose every movement re-runs the EMI formula and the whole bank comparison; the numbers only exist in response to dragging, which is the one thing a server component cannot do. The page around it stays server-rendered. */
'use client';

/**
 * The EMI calculator's interactive half. Ported from
 * apps/main-app/src/routes/(layout-1)/tools/emi-calculator/+page.svelte.
 *
 * Svelte's `$derived` becomes plain expressions in the render body. There is
 * no `useMemo` on any of them on purpose: each is one `Math.pow` or a map
 * over a list that is empty today and would be a dozen rows at most. Memoising
 * arithmetic that is cheaper than the memo's own bookkeeping makes the code
 * harder to read and the page no faster.
 *
 * The results stay behind the button, exactly as the original: `revealed` is
 * only ever set true, so once the reader has asked for the numbers the panel
 * tracks the sliders live. A button that gates the first reveal and then gets
 * out of the way is the behaviour the SvelteKit page has, and it is the right
 * one — a reader who has not entered anything yet should not be shown an EMI
 * for the default loan.
 *
 * `capture('...')` is dropped: there is no PostHog in this app.
 */
import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Calendar, IndianRupee, Percent } from 'lucide-react';
import { BreakdownRow, Panel, StatTile } from './Panel';
import { RangeField, SelectField } from './Field';
import { contentUrl } from '@/lib/directory/urls';
import type { FinancingBank } from '@/lib/tools/data';
import { emi, rupees } from '@/lib/tools/estimate';

const TENURES = [12, 24, 36, 48, 60];

export function EmiCalculator({ banks }: { banks: FinancingBank[] }) {
  const [loanAmount, setLoanAmount] = useState(300_000);
  const [tenure, setTenure] = useState(60);
  const [interestRate, setInterestRate] = useState(9);
  const [revealed, setRevealed] = useState(false);

  const monthly = Math.round(emi(loanAmount, interestRate, tenure));
  const totalPayment = monthly * tenure;
  const totalInterest = totalPayment - loanAmount;

  /**
   * A bank row whose `interest_rate` does not parse falls back to the
   * slider's rate rather than being dropped. The column is free-form `text`,
   * so a row reading "9.5% onwards" is a real possibility; showing the bank
   * with the reader's own rate is more useful than hiding it, and the rate
   * column prints what was used either way.
   */
  const comparisons = banks.map((bank) => {
    const rate = Number.parseFloat(bank.interestRate ?? '') || interestRate;
    const bankEmi = Math.round(emi(loanAmount, rate, tenure));
    return {
      ...bank,
      rate,
      emi: bankEmi,
      totalInterest: bankEmi * tenure - loanAmount
    };
  });

  return (
    <>
      <Panel>
        <div className="grid grid-cols-1 gap-lg md:grid-cols-2">
          <div className="md:col-span-2">
            <RangeField
              label="Loan Amount"
              value={loanAmount}
              readout={rupees(loanAmount)}
              min={50_000}
              max={2_000_000}
              step={10_000}
              hint="Rs 50,000 - Rs 20,00,000"
              onChange={setLoanAmount}
            />
          </div>

          <RangeField
            label="Interest Rate (% p.a.)"
            value={interestRate}
            readout={`${interestRate.toFixed(1)}%`}
            min={5}
            max={18}
            step={0.25}
            hint="5% - 18%"
            onChange={setInterestRate}
          />

          <SelectField
            label="Loan Tenure"
            value={String(tenure)}
            onChange={(v) => setTenure(Number(v))}
            options={TENURES.map((months) => ({
              value: String(months),
              label: `${months} months (${months / 12} ${months === 12 ? 'year' : 'years'})`
            }))}
          />
        </div>

        <button type="button" onClick={() => setRevealed(true)} className="btn btn-primary mt-lg w-full">
          Calculate EMI
        </button>
      </Panel>

      {revealed ? (
        <>
          <Panel title="EMI Breakdown">
            <div className="grid grid-cols-1 gap-md md:grid-cols-3">
              <StatTile icon={IndianRupee} value={rupees(monthly)} label="Monthly EMI" />
              <StatTile icon={Percent} value={rupees(totalInterest)} label="Total Interest" />
              <StatTile icon={Calendar} value={rupees(totalPayment)} label="Total Payment" />
            </div>

            <dl className="mt-lg divide-y divide-line border-t border-line pt-xs">
              <BreakdownRow label="Loan Amount" value={rupees(loanAmount)} />
              <BreakdownRow label="Interest Rate" value={`${interestRate.toFixed(2)}% p.a.`} />
              <BreakdownRow label="Tenure" value={`${tenure} months`} />
              <BreakdownRow
                label="Principal Component"
                value={`${Math.round((loanAmount / totalPayment) * 100)}% of total`}
              />
              <BreakdownRow
                label="Interest Component"
                value={`${Math.round((totalInterest / totalPayment) * 100)}% of total`}
              />
            </dl>
          </Panel>

          {/* `solar_financing_banks` is empty today, so this never renders.
              It is built rather than deferred because the table is the only
              reason the page queries anything — lib/tools/data.ts. */}
          {comparisons.length > 0 ? (
            <Panel title="Compare Bank Schemes">
              <p className="text-sm text-ink-muted">
                EMI comparison for {rupees(loanAmount)} over {tenure} months.
              </p>
              <div className="mt-md overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-line text-left text-ink-muted">
                      <th scope="col" className="py-xs pr-md font-medium">
                        Bank
                      </th>
                      <th scope="col" className="px-md py-xs text-right font-medium">
                        Rate
                      </th>
                      <th scope="col" className="px-md py-xs text-right font-medium">
                        Monthly EMI
                      </th>
                      <th scope="col" className="py-xs pl-md text-right font-medium">
                        Total Interest
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {comparisons.map((bank) => (
                      <tr key={bank.slug} className="border-b border-line last:border-0">
                        <th scope="row" className="py-sm pr-md text-left font-medium">
                          <a href={contentUrl(`/solar-financing/${bank.slug}`)}>{bank.name}</a>
                        </th>
                        <td className="px-md py-sm text-right tabular-nums">
                          {bank.rate.toFixed(2)}%
                        </td>
                        <td className="px-md py-sm text-right font-medium tabular-nums">
                          {rupees(bank.emi)}
                        </td>
                        <td className="py-sm pl-md text-right tabular-nums">
                          {rupees(bank.totalInterest)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </Panel>
          ) : null}

          <div className="rounded-lg bg-accent-surface p-md">
            <p className="text-sm text-ink-muted">
              Ready to finance your solar installation? Get connected with verified installers who
              can help with financing options.
            </p>
            <Link href="/in/get-quotes" className="btn btn-primary mt-sm">
              Apply for Solar Financing <ArrowRight aria-hidden className="h-4 w-4" />
            </Link>
          </div>
        </>
      ) : null}
    </>
  );
}

// apps/main-app/src/routes/(layout-1)/tools/emi-calculator/+page.svelte
<script lang="ts">
	import { contentUrl, countryUrl, geoUrl } from '$lib/countries/urls';
	import { Label } from '$lib/components/ui/label';
	import { Slider } from '$lib/components/ui/slider';
	import * as Select from '$lib/components/ui/select';
	import { breadcrumbLD, webAppLD } from '$lib/seo';
	import Breadcrumb from '$lib/in/components/seo/Breadcrumb.svelte';
	import { IndianRupee, Percent, Calendar, ArrowRight } from '@lucide/svelte';

	let { data } = $props();

	const BASE_URL = 'https://solarvipani.com';

	const breadcrumb = breadcrumbLD([
		{ name: 'Home', url: `${BASE_URL}/in/` },
		{ name: 'Tools', url: `${BASE_URL}/tools/` },
		{ name: 'EMI Calculator', url: `${BASE_URL}/tools/emi-calculator/` }
	]);

	const webApp = webAppLD({
		name: 'Solar EMI Calculator',
		description:
			'Calculate monthly EMI for solar panel loans. Compare rates across banks and find the best financing for your solar installation in India.',
		url: `${BASE_URL}/tools/emi-calculator/`
	});

	// Form state
	let loanAmount = $state(300000);
	let tenureMonths = $state('60');
	let interestRate = $state(9);
	let hasCalculated = $state(false);

	// EMI formula: EMI = P * r * (1+r)^n / ((1+r)^n - 1)
	function calculateEmi(principal: number, annualRate: number, months: number) {
		if (annualRate === 0) return principal / months;
		const r = annualRate / 12 / 100;
		const n = months;
		return (principal * r * Math.pow(1 + r, n)) / (Math.pow(1 + r, n) - 1);
	}

	const tenure = $derived(parseInt(tenureMonths));
	const emi = $derived(Math.round(calculateEmi(loanAmount, interestRate, tenure)));
	const totalPayment = $derived(emi * tenure);
	const totalInterest = $derived(totalPayment - loanAmount);

	// Bank comparison
	const bankComparisons = $derived(
		data.banks.map(
			(bank: { slug: string; name: string; interestRate: string; maxAmount: string; tenure: string }) => {
				const rate = parseFloat(bank.interestRate) || interestRate;
				const bankEmi = Math.round(calculateEmi(loanAmount, rate, tenure));
				const bankTotal = bankEmi * tenure;
				return {
					...bank,
					rate,
					emi: bankEmi,
					totalPayment: bankTotal,
					totalInterest: bankTotal - loanAmount
				};
			}
		)
	);

	function handleCalculate() {
		hasCalculated = true;
	}
</script>

<svelte:head>
	<title>Solar EMI Calculator — Monthly Loan Payment Estimator | Solar Vipani</title>
	<meta
		name="description"
		content="Calculate monthly EMI for solar panel loans. Compare interest rates across SBI, HDFC, and other banks. Free solar loan calculator for India."
	/>
	<link rel="canonical" href="{BASE_URL}/tools/emi-calculator/" />
	{@html `<script type="application/ld+json">${JSON.stringify(breadcrumb)}<\u002Fscript>`}
	{@html `<script type="application/ld+json">${JSON.stringify(webApp)}<\u002Fscript>`}
</svelte:head>

<div class="max-w-4xl mx-auto px-4 py-8">
	<Breadcrumb
		items={[
			{ name: 'Home', href: countryUrl('in', '/') },
			{ name: 'Tools', href: contentUrl('/tools/') },
			{ name: 'EMI Calculator', href: contentUrl('/tools/emi-calculator/') }
		]}
	/>

	<h1 class="text-3xl md:text-4xl font-bold text-primary mb-4">Solar EMI Calculator</h1>
	<p class="text-muted-foreground mb-8 max-w-2xl">
		Calculate monthly EMI for your solar panel loan. Adjust loan amount, tenure, and interest rate
		to find the best financing option.
	</p>

	<!-- Calculator Form -->
	<div class="rounded-lg border bg-card p-6 shadow-[theme(--shadow-xs)] mb-8">
		<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
			<!-- Loan Amount -->
			<div class="flex flex-col gap-2 md:col-span-2">
				<div class="flex justify-between items-baseline">
					<Label for="loan">Loan Amount</Label>
					<span class="text-primary text-lg font-semibold">
						Rs {loanAmount.toLocaleString('en-IN')}
					</span>
				</div>
				<Slider
					id="loan"
					min={[50000]}
					max={[2000000]}
					step={[10000]}
					bind:value={loanAmount}
					class="w-full"
				/>
				<div class="text-muted-foreground text-xs">Rs 50,000 - Rs 20,00,000</div>
			</div>

			<!-- Interest Rate -->
			<div class="flex flex-col gap-2">
				<div class="flex justify-between items-baseline">
					<Label for="interest">Interest Rate (% p.a.)</Label>
					<span class="text-primary text-lg font-semibold">{interestRate.toFixed(1)}%</span>
				</div>
				<Slider
					id="interest"
					min={[5]}
					max={[18]}
					step={[0.25]}
					bind:value={interestRate}
					class="w-full"
				/>
				<div class="text-muted-foreground text-xs">5% - 18%</div>
			</div>

			<!-- Tenure -->
			<div class="flex flex-col gap-2">
				<Label for="tenure">Loan Tenure</Label>
				<Select.Root type="single" bind:value={tenureMonths}>
					<Select.Trigger class="w-full">
						{tenure} months ({Math.round(tenure / 12)} {tenure === 12 ? 'year' : 'years'})
					</Select.Trigger>
					<Select.Content>
						<Select.Item value="12">12 months (1 year)</Select.Item>
						<Select.Item value="24">24 months (2 years)</Select.Item>
						<Select.Item value="36">36 months (3 years)</Select.Item>
						<Select.Item value="48">48 months (4 years)</Select.Item>
						<Select.Item value="60">60 months (5 years)</Select.Item>
					</Select.Content>
				</Select.Root>
			</div>
		</div>

		<button
			onclick={handleCalculate}
			class="mt-6 w-full bg-primary text-primary-foreground font-semibold py-3 rounded-lg hover:opacity-90 transition-opacity"
		>
			Calculate EMI
		</button>
	</div>

	<!-- Results -->
	{#if hasCalculated}
		<div class="rounded-lg border bg-card p-6 shadow-[theme(--shadow-xs)] mb-8">
			<h2 class="text-2xl font-semibold text-primary mb-6">EMI Breakdown</h2>

			<div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
				<div class="rounded-lg bg-muted p-4 text-center">
					<IndianRupee class="w-6 h-6 text-primary mx-auto mb-2" />
					<p class="text-2xl font-bold text-primary">Rs {emi.toLocaleString('en-IN')}</p>
					<p class="text-xs text-muted-foreground">Monthly EMI</p>
				</div>
				<div class="rounded-lg bg-muted p-4 text-center">
					<Percent class="w-6 h-6 text-primary mx-auto mb-2" />
					<p class="text-2xl font-bold text-primary">Rs {totalInterest.toLocaleString('en-IN')}</p>
					<p class="text-xs text-muted-foreground">Total Interest</p>
				</div>
				<div class="rounded-lg bg-muted p-4 text-center">
					<Calendar class="w-6 h-6 text-primary mx-auto mb-2" />
					<p class="text-2xl font-bold text-primary">Rs {totalPayment.toLocaleString('en-IN')}</p>
					<p class="text-xs text-muted-foreground">Total Payment</p>
				</div>
			</div>

			<!-- Payment Breakdown -->
			<div class="border-t pt-4 space-y-3">
				<div class="flex justify-between text-sm">
					<span class="text-muted-foreground">Loan Amount</span>
					<span class="font-medium">Rs {loanAmount.toLocaleString('en-IN')}</span>
				</div>
				<div class="flex justify-between text-sm">
					<span class="text-muted-foreground">Interest Rate</span>
					<span class="font-medium">{interestRate.toFixed(2)}% p.a.</span>
				</div>
				<div class="flex justify-between text-sm">
					<span class="text-muted-foreground">Tenure</span>
					<span class="font-medium">{tenure} months</span>
				</div>
				<div class="flex justify-between text-sm">
					<span class="text-muted-foreground">Principal Component</span>
					<span class="font-medium">
						{Math.round((loanAmount / totalPayment) * 100)}% of total
					</span>
				</div>
				<div class="flex justify-between text-sm">
					<span class="text-muted-foreground">Interest Component</span>
					<span class="font-medium">
						{Math.round((totalInterest / totalPayment) * 100)}% of total
					</span>
				</div>
			</div>
		</div>

		<!-- Bank Comparison -->
		{#if bankComparisons.length > 0}
			<div class="rounded-lg border bg-card p-6 shadow-[theme(--shadow-xs)] mb-8">
				<h2 class="text-2xl font-semibold text-primary mb-4">Compare Bank Schemes</h2>
				<p class="text-sm text-muted-foreground mb-4">
					EMI comparison for Rs {loanAmount.toLocaleString('en-IN')} over {tenure} months.
				</p>
				<div class="overflow-x-auto">
					<table class="w-full text-sm">
						<thead>
							<tr class="border-b">
								<th class="text-left py-2 pr-4 font-medium text-muted-foreground">Bank</th>
								<th class="text-right py-2 px-4 font-medium text-muted-foreground">Rate</th>
								<th class="text-right py-2 px-4 font-medium text-muted-foreground">Monthly EMI</th>
								<th class="text-right py-2 pl-4 font-medium text-muted-foreground">Total Interest</th>
							</tr>
						</thead>
						<tbody>
							{#each bankComparisons as bank}
								<tr class="border-b last:border-0">
									<td class="py-2.5 pr-4">
										<a
											href={contentUrl(`/solar-financing/${bank.slug}/`)}
											class="text-primary hover:underline font-medium"
										>
											{bank.name}
										</a>
									</td>
									<td class="text-right py-2.5 px-4">{bank.rate.toFixed(2)}%</td>
									<td class="text-right py-2.5 px-4 font-medium">
										Rs {bank.emi.toLocaleString('en-IN')}
									</td>
									<td class="text-right py-2.5 pl-4">
										Rs {bank.totalInterest.toLocaleString('en-IN')}
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</div>
		{/if}

		<!-- CTA -->
		<div class="rounded-lg bg-primary/5 p-6 mb-8">
			<p class="text-sm text-muted-foreground mb-3">
				Ready to finance your solar installation? Get connected with verified installers who can
				help with financing options.
			</p>
			<a
				href={countryUrl("in", "/get-quotes/")}
				class="inline-flex items-center gap-2 bg-primary text-primary-foreground font-semibold px-6 py-2.5 rounded-lg hover:opacity-90 transition-opacity text-sm"
			>
				Apply for Solar Financing <ArrowRight class="w-4 h-4" />
			</a>
		</div>
	{/if}

	<!-- Authority links -->
	<div class="flex flex-wrap gap-3 text-sm mb-8">
		<a href={contentUrl("/tools/solar-calculator/")} class="text-primary hover:underline">Solar Calculator</a>
		<span class="text-muted-foreground">|</span>
		<a href={contentUrl("/solar-financing/")} class="text-primary hover:underline">Solar Financing Guide</a>
		<span class="text-muted-foreground">|</span>
		<a href={geoUrl("in")} class="text-primary hover:underline">Browse Installers</a>
	</div>
</div>
