// apps/main-app/src/routes/[country=country]/(layout-1)/+page.svelte
<script>
  import { onMount } from "svelte";
  import { contentUrl, countryUrl } from "$lib/countries/urls";
  import RecentProjectsHome from "$lib/components/RecentProjectsHome.svelte";
  import SolarComparisonTable from "$lib/components/SolarComparisonTable.svelte";

  // Receive data from server
  let { data } = $props();

  const cc = $derived(data.country.code);
  const homeUrl = $derived(countryUrl(cc, ""));
  const quotesUrl = $derived(countryUrl(cc, "/get-quotes/"));

  // Assembled here rather than inline in the markup: svelte2tsx mis-parses
  // `{@html `<script ...`}` and reports a phantom error far from the real line.
  // (The two such blocks already in this file are why `npm run check` reports
  // "Unterminated template" here in the baseline.)
  const breadcrumbScript = $derived(
    `<script type="application/ld+json">${JSON.stringify({
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Home",
          item: `https://solarvipani.com${homeUrl}`,
        },
      ],
    })}<\/script>`,
  );

  // Initialize component state
  let videoLoaded = $state(false);
  let videoRef = $state(null);

  // Extract recent projects from data
  const recentProjects = $derived(data?.recentProjects || []);
  const dateModified = $derived(data?.dateModified ?? new Date().toISOString().split('T')[0]);

  // Lazy load non-critical components after initial page load
  onMount(async () => {
    // Progressive enhancement: the hero video (~4.5MB) is decorative and fades
    // in over the static AVIF (the LCP element). We defer its download until the
    // browser is idle so it never competes with the LCP image for bandwidth.
    if (videoRef) {
      videoRef.addEventListener('loadeddata', () => {
        videoLoaded = true;
      });

      videoRef.addEventListener('error', () => {
        console.log('Video failed to load, using static image');
      });

      const startVideoLoad = () => {
        videoRef.src = "/video/installation-video.mp4";
        videoRef.load();
      };

      // requestIdleCallback runs after the page is interactive and the LCP image
      // has had the connection to itself; setTimeout is the Safari fallback.
      if ("requestIdleCallback" in window) {
        requestIdleCallback(startVideoLoad, { timeout: 3000 });
      } else {
        setTimeout(startVideoLoad, 2000);
      }
    }
  });
</script>

<svelte:head>
  <title
    >Solar Vipani | India's #1 Solar Quotation Service | Quickly Get Solar
    Quotations from 2-3 Verified Installers</title
  >
  <meta
    name="description"
    content="Find verified solar panel installers near you in India. Get up to ₹78,000 government subsidy under PM Surya Ghar Yojana. Compare quotes, read reviews & save up to 95% on electricity bills. Free consultation available."
  />

  <!-- Enhanced Keywords -->
  <meta
    name="keywords"
    content="solar panel installation India, solar installers near me, PM Surya Ghar Yojana, solar subsidy India, rooftop solar installation, solar panel cost, verified solar installers, solar energy India, solar panel quotes"
  />

  <!-- Geographic targeting -->
  <meta name="geo.region" content="IN" />
  <meta name="geo.country" content="India" />

  <!-- Enhanced Open Graph -->
  <meta
    property="og:title"
    content="Solar Vipani | India's #1 Solar Panel Installer Directory"
  />
  <meta
    property="og:description"
    content="Connect with 500+ verified solar installers across India. Get up to ₹78,000 government subsidy. Save up to 95% on electricity bills. Free consultation & quotes."
  />
  <meta property="og:image" content="https://solarvipani.com/logo512.png" />
  <meta property="og:image:width" content="512" />
  <meta property="og:image:height" content="512" />
  <meta property="og:url" content="https://solarvipani.com{homeUrl}" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Solar Vipani" />
  <meta property="og:locale" content="en_IN" />

  <!-- Twitter Cards -->
  <meta name="twitter:card" content="summary_large_image" />
  <meta
    name="twitter:title"
    content="Solar Vipani | India's #1 Solar Panel Installer Directory"
  />
  <meta
    name="twitter:description"
    content="Find verified solar installers near you. Get ₹78,000 subsidy & save 95% on electricity bills."
  />
  <meta name="twitter:image" content="https://solarvipani.com/logo512.png" />

  <!-- Canonical URL -->
  <link rel="canonical" href="https://solarvipani.com{homeUrl}" />

  <!-- Preload critical hero image for faster LCP -->
  <link
    rel="preload"
    as="image"
    href="/header/header.avif"
    fetchpriority="high"
  />

  <!-- Preconnect to external domains for faster resource loading -->
  <link rel="preconnect" href="https://res.cloudinary.com" />

  <!-- JSON-LD Structured Data -->
  {@html `<script type="application/ld+json">${JSON.stringify({
      "@context": "https://schema.org",
      "@type": "Organization",
      "name": "Solar Vipani",
      "url": "https://solarvipani.com",
      "logo": "https://solarvipani.com/logo512.png",
      "description": "India's leading platform connecting customers with verified solar panel installers",
      "address": {
        "@type": "PostalAddress",
        "addressCountry": "IN"
      },
      "sameAs": [
        "https://www.facebook.com/solarvipani",
        "https://www.linkedin.com/company/solarvipani"
      ],
      "contactPoint": {
        "@type": "ContactPoint",
        "contactType": "customer service",
        "availableLanguage": ["English", "Hindi"]
      },
      "dateModified": dateModified
    })}<\/script>`}

  {@html `<script type="application/ld+json">${JSON.stringify({
      "@context": "https://schema.org",
      "@type": "WebSite",
      "name": "Solar Vipani",
      "url": "https://solarvipani.com",
      "description": "Find verified solar panel installers across India",
      "dateModified": dateModified
    })}<\/script>`}

  {@html breadcrumbScript}

  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "HowTo",
      "name": "How to Get Solar Installation Quotes in India",
      "description": "Get competitive solar installation quotes from verified installers in 4 simple steps",
      "step": [
        {
          "@type": "HowToStep",
          "position": 1,
          "name": "Fill the Inquiry Form",
          "text": "Share your basic details and energy requirements to help us understand your needs."
        },
        {
          "@type": "HowToStep",
          "position": 2,
          "name": "Receive Competitive Quotes",
          "text": "Review quotes from 2-3 solar companies, comparing costs, equipment, and terms to find the perfect match."
        },
        {
          "@type": "HowToStep",
          "position": 3,
          "name": "Make an Informed Choice",
          "text": "Select a provider with complete confidence, backed by transparent, verified information."
        },
        {
          "@type": "HowToStep",
          "position": 4,
          "name": "Share Your Success",
          "text": "Join our community of solar adopters by sharing your experience, helping others on their journey to clean energy."
        }
      ]
    }
  </script>

  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": [
        {
          "@type": "Question",
          "name": "What is the cost of solar panel installation in India?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "A 3 kW rooftop solar system costs ₹1.5–2.5 lakh before subsidy. After the PM Surya Ghar Yojana subsidy of up to ₹78,000, the effective cost drops significantly. Exact pricing depends on your location, panel brand, and installer. Get free quotes from 2–3 verified installers to compare."
          }
        },
        {
          "@type": "Question",
          "name": "How much government subsidy can I get under PM Surya Ghar Yojana?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Under PM Surya Ghar Muft Bijli Yojana, residential customers can get up to ₹78,000 in direct subsidy: ₹30,000 per kW for the first 2 kW, and ₹18,000 per kW for the next 1 kW (capped at 3 kW). The subsidy is credited directly to your bank account after installation."
          }
        },
        {
          "@type": "Question",
          "name": "How long does it take to install solar panels?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "A typical residential rooftop solar installation takes 1–3 days for physical installation. The complete process including site survey, permits, and net metering connection usually takes 2–6 weeks depending on your state's DISCOM."
          }
        },
        {
          "@type": "Question",
          "name": "How do I choose a verified solar installer?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Look for installers who are MNRE empanelled, have local installation experience, provide a 5-year workmanship warranty, and offer after-sales service. Solar Vipani connects you with pre-verified installers so you can compare 2–3 quotes with confidence."
          }
        },
        {
          "@type": "Question",
          "name": "What is net metering and how does it benefit me?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Net metering lets you export surplus solar energy back to the grid and earn credits on your electricity bill. When your panels produce more than you consume — typically during daytime — the excess units are credited, reducing your monthly bill to near zero in many cases."
          }
        }
      ]
    }
  </script>

  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Service",
      "name": "Solar Panel Installation Directory",
      "description": "Connect with verified solar panel installers across India",
      "provider": {
        "@type": "Organization",
        "name": "Solar Vipani"
      },
      "areaServed": {
        "@type": "Country",
        "name": "India"
      },
      "hasOfferCatalog": {
        "@type": "OfferCatalog",
        "name": "Solar Installation Services",
        "itemListElement": [
          {
            "@type": "Offer",
            "itemOffered": {
              "@type": "Service",
              "name": "Residential Solar Installation"
            }
          },
          {
            "@type": "Offer",
            "itemOffered": {
              "@type": "Service",
              "name": "Commercial Solar Installation"
            }
          },
          {
            "@type": "Offer",
            "itemOffered": {
              "@type": "Service",
              "name": "Agricultural Solar Installation"
            }
          }
        ]
      }
    }
  </script>
</svelte:head>

<main class="w-full bg-background text-foreground transition-colors duration-300 overflow-x-hidden dark:bg-background dark:text-foreground">
  <!-- Hero Banner Section -->
  <div class="relative w-full h-[theme(--height-lg)] flex items-center justify-center text-center overflow-hidden md:h-[42rem]">
    <!-- Static Image - Always visible initially, fades out when video loads -->
    <img
      class="absolute top-0 left-0 w-full h-full object-cover object-center z-0 transition-opacity duration-1000"
      class:opacity-0={videoLoaded}
      src="/header/header.avif"
      alt="Residential Solar Panel Installation in India"
      width="1920"
      height="600"
      fetchpriority="high"
      decoding="async"
    />

    <!-- Video - src is attached after idle (see onMount), then fades in once loaded -->
    <video
      bind:this={videoRef}
      class="absolute top-0 left-0 w-full h-full object-cover object-center z-0 transition-opacity duration-1000"
      class:opacity-0={!videoLoaded}
      autoplay
      muted
      loop
      playsinline
      preload="none"
    ></video>

    <div class="absolute top-0 left-0 w-full h-full z-10 bg-black/55"></div>
    <div class="relative z-20 max-w-3xl px-6">
      <h1 class="text-4xl md:text-5xl font-bold mb-6 text-primary-foreground leading-tight drop-shadow-lg">
        Get 2-3 Free Quotes from Verified Installers in Your Area
      </h1>
      <h2 class="text-2xl md:text-3xl font-medium mb-6 text-primary-foreground leading-snug drop-shadow-lg">
        Save 10-20% on installation costs with competitive solar quotations online
      </h2>
    </div>
  </div>

  <div class="mx-auto max-w-[1140px] p-[theme(--container-padding)]">
    <!-- Get Quote CTA Section -->
    <section id="lead-form-sv" class="mb-8 mx-auto max-w-md">
      <div class="rounded-[theme(--radius-lg)] p-[theme(--card-padding-y)] shadow-[theme(--shadow-lg)] bg-gradient-to-br from-primary/10 to-primary/5">
        <div class="text-center mb-8">
          <h2 class="text-3xl md:text-4xl font-semibold mb-4 text-primary">Get Your Free Solar Quotation Online</h2>
          <div class="flex justify-center items-center my-4">
            <span class="w-[theme(--divider-line-width)] h-[theme(--divider-line-height)] bg-accent rounded"></span>
          </div>
        </div>
        <div class="text-center">
          <a
            href={quotesUrl}
            class="inline-block bg-primary text-primary-foreground font-semibold px-8 py-3 rounded-lg hover:opacity-90 transition-opacity"
          >
            Get a Free Solar Quotation Online
          </a>
        </div>
      </div>
    </section>

    <!-- Solar Comparison Section -->
    <SolarComparisonTable />

    <!-- Solar Knowledge Hub — authority links to all 7 pillar pages -->
    <section class="mb-8 rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] shadow-[theme(--shadow-md)]">
      <div class="text-center mb-8">
        <h2 class="text-3xl md:text-4xl font-semibold mb-4 text-primary">Solar Knowledge Hub</h2>
        <div class="flex justify-center items-center my-4">
          <span class="w-[theme(--divider-line-width)] h-[theme(--divider-line-height)] bg-accent rounded"></span>
        </div>
        <p class="text-lg text-foreground dark:text-foreground-secondary max-w-2xl mx-auto">
          Everything you need to know before going solar — from panels and inverters to subsidies and financing
        </p>
      </div>
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-[theme(--card-gap)]">
        {#each [
          { href: contentUrl("/rooftop-solar"), title: "Rooftop Solar", desc: "System sizing, costs, and what to expect from a rooftop installation", icon: "☀️" },
          { href: contentUrl("/solar-panels"), title: "Solar Panels", desc: "Compare panel brands, technologies, and specifications", icon: "🔋" },
          { href: contentUrl("/solar-inverters"), title: "Solar Inverters", desc: "On-grid, hybrid, and micro inverter options for your system", icon: "⚡" },
          { href: contentUrl("/solar-installation"), title: "Solar Installation", desc: "Site assessment, installation process, and timeline", icon: "🔧" },
          { href: contentUrl("/solar-subsidy"), title: "Solar Subsidy", desc: "PM Surya Ghar Yojana, state subsidies, and how to apply", icon: "🏛️" },
          { href: contentUrl("/solar-financing"), title: "Solar Financing", desc: "Solar loans, EMI options, and bank schemes", icon: "💳" },
          { href: contentUrl("/solar-pumps"), title: "Solar Pumps", desc: "Agricultural and residential solar pump solutions", icon: "💧" }
        ] as pillar}
          <a
            href={pillar.href}
            class="group flex flex-col border border-border rounded-[theme(--radius-lg)] bg-background p-6 no-underline transition-all duration-[theme(--transition-default)] hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-sm)]"
          >
            <span class="text-3xl mb-3">{pillar.icon}</span>
            <h3 class="text-lg font-semibold text-primary mb-2 group-hover:text-primary-hover transition-colors">{pillar.title}</h3>
            <p class="text-sm text-foreground dark:text-foreground-secondary leading-relaxed">{pillar.desc}</p>
          </a>
        {/each}
      </div>
    </section>

    <!-- How It Works Section -->
    <section class="mb-8 rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] shadow-[theme(--shadow-md)]">
      <div class="text-center mb-8">
        <h2 class="text-3xl md:text-4xl font-semibold mb-4 text-primary">How Solar Vipani Works</h2>
        <div class="flex justify-center items-center my-4">
          <span class="w-[theme(--divider-line-width)] h-[theme(--divider-line-height)] bg-accent rounded"></span>
        </div>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-4 gap-[theme(--card-gap)]">
        <div class="text-center border border-border hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-sm)] rounded-[theme(--radius-lg)] bg-background p-8 transition-all duration-[theme(--transition-default)]">
          <div class="w-12 h-12 bg-primary text-primary-foreground rounded-full flex items-center justify-center font-bold text-xl mx-auto mb-4">1</div>
          <h3 class="text-lg font-semibold text-primary mb-3">Fill the Inquiry Form</h3>
          <p class="text-foreground dark:text-foreground-secondary">
            Share your basic details and energy requirements to help us understand your needs.
          </p>
        </div>
        <div class="text-center border border-border hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-sm)] rounded-[theme(--radius-lg)] bg-background p-8 transition-all duration-[theme(--transition-default)]">
          <div class="w-12 h-12 bg-primary text-primary-foreground rounded-full flex items-center justify-center font-bold text-xl mx-auto mb-4">2</div>
          <h3 class="text-lg font-semibold text-primary mb-3">Receive Competitive Quotes</h3>
          <p class="text-foreground dark:text-foreground-secondary">
            Review quotes from 2-3 solar companies, comparing costs, equipment, and terms to find the perfect match.
          </p>
        </div>
        <div class="text-center border border-border hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-sm)] rounded-[theme(--radius-lg)] bg-background p-8 transition-all duration-[theme(--transition-default)]">
          <div class="w-12 h-12 bg-primary text-primary-foreground rounded-full flex items-center justify-center font-bold text-xl mx-auto mb-4">3</div>
          <h3 class="text-lg font-semibold text-primary mb-3">Make an Informed Choice</h3>
          <p class="text-foreground dark:text-foreground-secondary">
            Select a provider with complete confidence, backed by transparent, verified information.
          </p>
        </div>
        <div class="text-center border border-border hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-sm)] rounded-[theme(--radius-lg)] bg-background p-8 transition-all duration-[theme(--transition-default)]">
          <div class="w-12 h-12 bg-primary text-primary-foreground rounded-full flex items-center justify-center font-bold text-xl mx-auto mb-4">4</div>
          <h3 class="text-lg font-semibold text-primary mb-3">Share Your Success</h3>
          <p class="text-foreground dark:text-foreground-secondary">
            Join our community of solar adopters by sharing your experience, helping others on their journey to clean energy.
          </p>
        </div>
      </div>
      <div class="text-center mt-8">
        <a
          href={quotesUrl}
          class="inline-block bg-primary text-primary-foreground font-semibold px-8 py-3 rounded-lg hover:opacity-90 transition-opacity"
        >
          Get a Free Solar Quotation Online
        </a>
      </div>
    </section>

    <!-- Recent Projects Section -->
    <RecentProjectsHome projects={recentProjects} />

    <!-- Benefits Section -->
    <section class="mb-8 rounded-[theme(--radius-lg)] bg-accent-muted p-[theme(--card-padding-y)] shadow-[theme(--shadow-md)]">
      <div class="text-center mb-8">
        <h2 class="text-3xl md:text-4xl font-semibold mb-4 text-primary">Why Now is the Right Time to Install Solar in India</h2>
        <div class="flex justify-center items-center my-4">
          <span class="w-[theme(--divider-line-width)] h-[theme(--divider-line-height)] bg-accent rounded"></span>
        </div>
        <p class="text-lg text-foreground dark:text-foreground-secondary max-w-2xl mx-auto">
          Take advantage of record subsidies, rising electricity costs, and our network of verified installers
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-3 gap-[theme(--card-gap)] mb-8">
        <div class="flex flex-col items-center text-center border-t-[theme(--card-accent-border)] border-accent hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-md)] rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] shadow-[theme(--shadow-md)] transition-all duration-[theme(--transition-default)]">
          <div class="text-5xl mb-4">💰</div>
          <div class="text-3xl font-bold text-primary mb-2">Up to ₹78,000</div>
          <h3 class="text-xl font-semibold text-primary mb-3">Government Subsidy</h3>
          <p class="text-foreground dark:text-foreground-secondary">
            Get up to ₹78,000 in direct subsidy under PM Surya Ghar Yojana - available for limited time
          </p>
        </div>

        <div class="flex flex-col items-center text-center border-t-[theme(--card-accent-border)] border-accent hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-md)] rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] shadow-[theme(--shadow-md)] transition-all duration-[theme(--transition-default)]">
          <div class="text-5xl mb-4">🏦</div>
          <div class="text-3xl font-bold text-primary mb-2">0% Interest</div>
          <h3 class="text-xl font-semibold text-primary mb-3">Easy Financing Options</h3>
          <p class="text-foreground dark:text-foreground-secondary">Zero-cost EMI and attractive loan schemes from leading banks and NBFCs make solar affordable</p>
        </div>

        <div class="flex flex-col items-center text-center border-t-[theme(--card-accent-border)] border-accent hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-md)] rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] shadow-[theme(--shadow-md)] transition-all duration-[theme(--transition-default)]">
          <div class="text-5xl mb-4">⚡</div>
          <div class="text-3xl font-bold text-primary mb-2">50-80%</div>
          <h3 class="text-xl font-semibold text-primary mb-3">Electricity Bill Savings</h3>
          <p class="text-foreground dark:text-foreground-secondary">
            Save up to 80% on rising electricity costs with net metering and reduce dependency on the grid
          </p>
        </div>
      </div>
    </section>

    <!-- FAQ Section -->
    <section class="mb-8 rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] shadow-[theme(--shadow-md)]">
      <div class="text-center mb-8">
        <h2 class="text-3xl md:text-4xl font-semibold mb-4 text-primary">Frequently Asked Questions</h2>
        <div class="flex justify-center items-center my-4">
          <span class="w-[theme(--divider-line-width)] h-[theme(--divider-line-height)] bg-accent rounded"></span>
        </div>
      </div>
      <div class="max-w-3xl mx-auto divide-y divide-border">
        {#each [
          {
            q: "What is the cost of solar panel installation in India?",
            a: "A 3 kW rooftop solar system costs ₹1.5–2.5 lakh before subsidy. After the PM Surya Ghar Yojana subsidy of up to ₹78,000, the effective cost drops significantly. Exact pricing depends on your location, panel brand, and installer. Get free quotes from 2–3 verified installers to compare."
          },
          {
            q: "How much government subsidy can I get under PM Surya Ghar Yojana?",
            a: "Residential customers can get up to ₹78,000 in direct subsidy: ₹30,000 per kW for the first 2 kW, and ₹18,000 per kW for the next 1 kW (capped at 3 kW). The subsidy is credited directly to your bank account after installation."
          },
          {
            q: "How long does it take to install solar panels?",
            a: "Physical installation takes 1–3 days. The complete process including site survey, permits, and net metering connection usually takes 2–6 weeks depending on your state's DISCOM."
          },
          {
            q: "How do I choose a verified solar installer?",
            a: "Look for MNRE-empanelled installers with local experience, a 5-year workmanship warranty, and after-sales support. Solar Vipani connects you with pre-verified installers so you can compare 2–3 quotes with confidence."
          },
          {
            q: "What is net metering and how does it benefit me?",
            a: "Net metering lets you export surplus solar energy to the grid and earn bill credits. When your panels produce more than you consume — typically during daytime — the excess units offset your monthly bill, often reducing it to near zero."
          }
        ] as faq}
          <details class="group py-4 cursor-pointer">
            <summary class="flex items-center justify-between gap-4 list-none font-semibold text-foreground text-base md:text-lg select-none">
              <span>{faq.q}</span>
              <span class="shrink-0 text-primary transition-transform duration-200 group-open:rotate-45">+</span>
            </summary>
            <p class="mt-3 text-foreground dark:text-foreground-secondary leading-relaxed">{faq.a}</p>
          </details>
        {/each}
      </div>
    </section>

  </div>
</main>

// apps/main-app-nextjs/app/(layout-1)/page.tsx
/**
 * The homepage — `/`. Spec: archetype/home.md. Ported from
 * apps/main-app/src/lib/components/HomePage.svelte, which is the whole of the
 * SvelteKit `/`.
 *
 * Not an archetype — one page — but the only long-tail page whose source
 * design contradicts the design system on every axis it has (§3), so what
 * comes across is the copy and the structure, not the styling:
 *
 *  - headings are ink and left-aligned, not centred brand orange with a rule;
 *  - cards are a hairline on bg-surface and do not lift on a shadow;
 *  - the two hero buttons are new — the live front door has no call to action
 *    anywhere above the fold (§2). They are the country choice itself, one
 *    per market, because that is this page's first job;
 *  - the counts are new. The original's comment refused them because the true
 *    figure "would need a query this page otherwise does not make" (§4). It
 *    does now: `getCountryHub` is the country hub's own query, memoised.
 *
 * **The page no longer leads with India.** It used to open on India's coverage
 * sentence and then offer a country grid below it, which made /in the default
 * and /us a second thought. Both are gone: the hero offers the two markets
 * side by side and carries the per-country installer counts under them, so
 * the counts survive the deletion and the choice is made once. The per-country
 * coverage ratios — districts and counties covered — are not carried over;
 * each country hub still prints its own.
 *
 * The 4.5MB decorative hero video does not come across (§6). Without it the
 * page needs no JavaScript at all: the AVIF is the LCP element, `priority`
 * preloads it, and nothing here is a client component.
 */
import type { Metadata } from 'next';
import Image from 'next/image';
import {
  Banknote,
  BadgeIndianRupee,
  Calculator,
  CreditCard,
  Droplets,
  HardHat,
  House,
  Landmark,
  PlugZap,
  SolarPanel
} from 'lucide-react';
import { Container, PageShell, Section, Stack } from '@/components/layout';
import { COUNTRIES, getCountry } from '@/lib/countries';
import { getCountryHub } from '@/lib/directory/data';
import { contentUrl, geoUrl } from '@/lib/directory/urls';
import { BASE_URL } from '@/lib/directory/structuredData';
import { OG_IMAGE, SITE_NAME, pageMetadata } from '@/lib/metadata';

/**
 * 15 days, matching `config.isr.expiration` on the SvelteKit root loader, and
 * a literal here per the README's Route Segment Config note.
 *
 * It is what keeps the coverage counts honest: without it they are read once
 * at build and the page's claim silently ages.
 */
export const revalidate = 1296000;

/**
 * The original's title and description, which are good and stay. The title
 * already carried the site name, so it is passed without it — `pageMetadata`
 * appends the suffix.
 */
export const metadata: Metadata = pageMetadata({
  title: 'Find Verified Solar Installers',
  description:
    'Browse verified solar panel installers by state. Compare quotes, read reviews and go solar. Free to use.',
  path: '/',
  locale: getCountry('in').locale,
  imageAlt: 'Solar Vipani'
});

/** The seven editorial families, through `contentUrl` — they are mid-migration
    out from under the /{country} prefix. Copy is the original's, verbatim. */
const PILLARS = [
  {
    href: contentUrl('/rooftop-solar'),
    title: 'Rooftop Solar',
    desc: 'System sizing, costs, and what to expect from a rooftop installation',
    icon: House
  },
  {
    href: contentUrl('/solar-panels'),
    title: 'Solar Panels',
    desc: 'Compare panel brands, technologies, and specifications',
    icon: SolarPanel
  },
  {
    href: contentUrl('/solar-inverters'),
    title: 'Solar Inverters',
    desc: 'On-grid, hybrid, and micro inverter options for your system',
    icon: PlugZap
  },
  {
    href: contentUrl('/solar-installation'),
    title: 'Solar Installation',
    desc: 'Site assessment, installation process, and timeline',
    icon: HardHat
  },
  {
    href: contentUrl('/solar-subsidy'),
    title: 'Solar Subsidy',
    desc: 'PM Surya Ghar Yojana, state subsidies, and how to apply',
    icon: Landmark
  },
  {
    href: contentUrl('/solar-financing'),
    title: 'Solar Financing',
    desc: 'Solar loans, EMI options, and bank schemes',
    icon: CreditCard
  },
  {
    href: contentUrl('/solar-pumps'),
    title: 'Solar Pumps',
    desc: 'Agricultural and residential solar pump solutions',
    icon: Droplets
  }
];

/** §7 section 5, new to this page: the three calculators are reachable today
    only from the footer. Copy from the SvelteKit /tools loader. */
const TOOLS = [
  {
    href: contentUrl('/tools/solar-calculator'),
    title: 'Solar Calculator',
    desc: 'Estimate system size, cost, savings, and payback period from your electricity bill.',
    icon: Calculator
  },
  {
    href: contentUrl('/tools/emi-calculator'),
    title: 'EMI Calculator',
    desc: 'Calculate monthly EMI for solar loans and compare rates across banks.',
    icon: Banknote
  },
  {
    href: contentUrl('/tools/subsidy-checker'),
    title: 'Subsidy Checker',
    desc: 'Check the central and state subsidies your system qualifies for.',
    icon: BadgeIndianRupee
  }
];

/** The card the app already has — LocationGrid's, minus the count. Local to
    this page because the two grids below are the only icon cards in the app. */
function IconCard({
  href,
  title,
  desc,
  icon: Icon
}: {
  href: string;
  title: string;
  desc: string;
  icon: typeof House;
}) {
  return (
    <li>
      <a
        href={href}
        className="flex h-full flex-col rounded-lg border border-line bg-surface p-md text-ink no-underline transition-shadow duration-fast ease-standard hover:shadow-raised"
      >
        {/* Decoration in a card, but seven different glyphs across seven cards
            is navigation rather than the identical marker LocationGrid dropped
            its pin for (§8). aria-hidden: the title carries the meaning. */}
        <Icon aria-hidden className="size-6 text-ink-subtle" />
        <h3 className="mt-sm text-base leading-snug text-action underline decoration-action/40 underline-offset-2">
          {title}
        </h3>
        <p className="mt-2xs text-sm text-ink-muted">{desc}</p>
      </a>
    </li>
  );
}

export default async function Page() {
  // Both hubs in parallel, both memoised, nothing added to data.ts (§9).
  const [inHub, usHub] = await Promise.all([getCountryHub('in'), getCountryHub('us')]);
  const hubs = { in: inHub, us: usHub };

  const india = getCountry('in');

  const hero = (
    /* Full-bleed: the <section> is the photograph and the scrim, and the copy
       inside sits in a normal Container so the h1 aligns with every heading
       below it. ~24rem, not the live page's 42rem poster — the band earns its
       height with a headline, a lede and two buttons (§6). */
    <section className="relative isolate flex min-h-[24rem] items-center overflow-hidden py-2xl">
      {/* Decorative, so alt="". The copy on top carries the meaning. The
          intrinsic size is the asset's; object-cover does the rest. */}
      <Image
        src="/header/header.avif"
        alt=""
        width={1920}
        height={600}
        priority
        className="absolute inset-0 -z-10 size-full object-cover object-center"
      />
      {/* White on a photograph is the one legitimate exception to the contrast
          system (§11 q1): this is not text on a token surface, so the scrim is
          carried across from the original unchanged and unverified. */}
      <div className="absolute inset-0 -z-10 bg-black/55" />
      <Container>
        <Stack gap="lg">
          <div className="max-w-prose">
            <h1 className="text-3xl leading-tight text-white">
              Get 2-3 Free Quotes from Verified Installers in Your Area
            </h1>
            {/* A <p>, not the original's <h2>: a subtitle as a heading puts a
                phantom entry in the outline above the page's real sections. */}
            <p className="mt-md text-lg text-white">
              Save 10-20% on installation costs with competitive solar quotations online
            </p>
          </div>
          {/* The page's first job is a choice between two countries, so the
              two buttons ARE that choice. One fill, one outline — the fill is
              the only sky on the band, which is rule 2, and it goes to India
              because this is an IN-first site. */}
          <div className="flex flex-wrap gap-sm">
            <a
              href={geoUrl('in')}
              className="inline-flex items-center justify-center rounded-md bg-action px-lg py-sm text-base font-semibold text-action-ink no-underline transition-colors duration-fast ease-standard hover:bg-action-hover"
            >
              Installers in {india.shortName}
            </a>
            <a
              href={geoUrl('us')}
              className="inline-flex items-center justify-center rounded-md border border-white px-lg py-sm text-base font-semibold text-white no-underline transition-colors duration-fast ease-standard hover:bg-white/10"
            >
              Installers in {getCountry('us').shortName}
            </a>
          </div>
          {/* The country-wise counts, which the two deleted sections used to
              carry. Here because this is the band where the choice is made and
              the count is what it turns on. `tabular-nums` so the figures read
              as data, as on /{cc}/solar. */}
          <p className="text-sm text-white">
            {Object.values(COUNTRIES).map((market, i) => (
              <span key={market.code}>
                {i > 0 ? <span aria-hidden> · </span> : null}
                <span className="font-semibold tabular-nums">
                  {hubs[market.code].totalInstallers.toLocaleString(india.locale)}
                </span>{' '}
                in {market.shortName}
              </span>
            ))}
          </p>
        </Stack>
      </Container>
    </section>
  );

  return (
    <PageShell hero={hero}>
      <Section>
        <nav aria-label="Solar guides">
          <h2 className="text-xl">Learn about solar</h2>
          <p className="mt-sm max-w-prose text-ink-muted">
            Everything worth knowing before going solar — from panels and inverters to subsidies
            and financing.
          </p>
          <ul className="mt-lg grid gap-md sm:grid-cols-2 lg:grid-cols-3">
            {PILLARS.map((pillar) => (
              <IconCard key={pillar.href} {...pillar} />
            ))}
          </ul>
        </nav>
      </Section>

      <Section>
        <nav aria-label="Solar tools and calculators">
          <h2 className="text-xl">Tools</h2>
          <ul className="mt-lg grid gap-md sm:grid-cols-2 lg:grid-cols-3">
            {TOOLS.map((tool) => (
              <IconCard key={tool.href} {...tool} />
            ))}
          </ul>
        </nav>
      </Section>

      {/* The original's @graph, minus `sameAs`: it asserted Facebook and
          LinkedIn profiles that nothing on the page or in SiteFooter links to,
          which is the same mismatch /about-us dropped it for (§10). */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@graph': [
              {
                '@type': 'Organization',
                name: SITE_NAME,
                url: BASE_URL,
                logo: OG_IMAGE.url,
                description:
                  'Platform connecting customers with verified solar panel installers',
                contactPoint: {
                  '@type': 'ContactPoint',
                  contactType: 'customer service',
                  availableLanguage: ['English', 'Hindi']
                }
              },
              {
                '@type': 'WebSite',
                name: SITE_NAME,
                url: BASE_URL,
                description: 'Find verified solar panel installers near you'
              }
            ]
          })
        }}
      />
    </PageShell>
  );
}
