// apps/main-app/src/routes/in/(layout-1)/get-quotes/+page.svelte
<script lang="ts">
	import LeadFormSection from '$lib/in/components/LeadFormSection.svelte';
	import { breadcrumbLD } from '$lib/seo';
	import { Users, FolderCheck } from '@lucide/svelte';

	let { data } = $props();

	const breadcrumb = breadcrumbLD([
		{ name: 'Home', url: 'https://solarvipani.com/in/' },
		{ name: 'Get Quotes', url: 'https://solarvipani.com/in/get-quotes/' }
	]);

	const faqs = [
		{
			q: 'Where can I get a solar quotation online in India?',
			a: 'You can get a free solar quotation online at Solar Vipani. Fill the inquiry form on this page with your location and energy requirements, and you will receive competitive quotations from 2-3 verified solar installers near you — entirely online, with no obligation.'
		},
		{
			q: 'Is the online solar quotation free?',
			a: 'Yes. Requesting a solar quotation online through Solar Vipani is completely free. You only deal with verified installers, compare their quotations, and decide if you want to proceed — there is no charge for the quotes.'
		},
		{
			q: 'How long does it take to receive my solar quotation?',
			a: 'After you submit the form online, you typically receive 2-3 competitive quotations from verified installers within 24 hours.'
		}
	];

	const faqLD = {
		'@context': 'https://schema.org',
		'@type': 'FAQPage',
		mainEntity: faqs.map((f) => ({
			'@type': 'Question',
			name: f.q,
			acceptedAnswer: { '@type': 'Answer', text: f.a }
		}))
	};
</script>

<svelte:head>
	<title>Get a Free Solar Quotation Online | Solar Vipani</title>
	<meta name="description" content="Get a free solar quotation online from verified solar panel installers in India. Compare 2-3 competitive quotations on price, services & reviews. {data.installerCount}+ installers, {data.projectCount}+ completed projects." />
	<link rel="canonical" href="https://solarvipani.com/in/get-quotes/" />
	{@html `<script type="application/ld+json">${JSON.stringify(breadcrumb)}</script>`}
	{@html `<script type="application/ld+json">${JSON.stringify(faqLD)}</script>`}
</svelte:head>

<div class="max-w-4xl mx-auto px-4 py-8">
	<!-- Breadcrumb -->
	<nav class="text-sm text-muted-foreground mb-6" aria-label="Breadcrumb">
		<ol class="flex flex-wrap gap-1">
			<li><a href="/in/" class="hover:text-primary">Home</a> /</li>
			<li class="text-foreground font-medium">Get Quotes</li>
		</ol>
	</nav>

	<h1 class="text-3xl md:text-4xl font-bold text-primary mb-4 text-center">
		Get a Free Solar Quotation Online
	</h1>

	<p class="text-center text-muted-foreground mb-8 max-w-2xl mx-auto">
		Connect with verified solar installers in your area and get a solar quotation online. Share your details and receive 2-3 competitive quotations within 24 hours.
	</p>

	<!-- Trust Bar -->
	<div class="flex flex-wrap justify-center gap-6 mb-10">
		<div class="flex items-center gap-2 bg-muted rounded-lg px-4 py-2">
			<Users class="w-5 h-5 text-primary" />
			<span class="font-semibold">{data.installerCount}+</span>
			<span class="text-muted-foreground">Verified Installers</span>
		</div>
		<div class="flex items-center gap-2 bg-muted rounded-lg px-4 py-2">
			<FolderCheck class="w-5 h-5 text-primary" />
			<span class="font-semibold">{data.projectCount}+</span>
			<span class="text-muted-foreground">Verified Projects</span>
		</div>
	</div>

	<!-- Lead Form -->
	<LeadFormSection title="Get Your Solar Quotation Online" hasBusinesses={true} />

	<!-- How to get a solar quotation online -->
	<section class="mt-12">
		<h2 class="text-2xl md:text-3xl font-semibold text-primary mb-6 text-center">
			How to Get Your Solar Quotation Online
		</h2>
		<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
			<div class="border border-border rounded-lg p-6 text-center">
				<div class="w-10 h-10 bg-primary text-primary-foreground rounded-full flex items-center justify-center font-bold mx-auto mb-3">1</div>
				<h3 class="font-semibold text-primary mb-2">Fill the Form Online</h3>
				<p class="text-sm text-muted-foreground">Share your location and energy requirements in the form above — it takes less than a minute.</p>
			</div>
			<div class="border border-border rounded-lg p-6 text-center">
				<div class="w-10 h-10 bg-primary text-primary-foreground rounded-full flex items-center justify-center font-bold mx-auto mb-3">2</div>
				<h3 class="font-semibold text-primary mb-2">Receive 2-3 Quotations</h3>
				<p class="text-sm text-muted-foreground">Verified installers near you send competitive solar quotations, usually within 24 hours.</p>
			</div>
			<div class="border border-border rounded-lg p-6 text-center">
				<div class="w-10 h-10 bg-primary text-primary-foreground rounded-full flex items-center justify-center font-bold mx-auto mb-3">3</div>
				<h3 class="font-semibold text-primary mb-2">Compare & Choose</h3>
				<p class="text-sm text-muted-foreground">Compare prices, equipment, and reviews online, then pick the installer that suits you best.</p>
			</div>
		</div>
	</section>

	<!-- FAQ -->
	<section class="mt-12">
		<h2 class="text-2xl md:text-3xl font-semibold text-primary mb-6 text-center">
			Frequently Asked Questions
		</h2>
		<div class="max-w-2xl mx-auto divide-y divide-border">
			{#each faqs as faq}
				<details class="group py-4 cursor-pointer">
					<summary class="flex items-center justify-between gap-4 list-none font-semibold text-foreground select-none">
						<span>{faq.q}</span>
						<span class="shrink-0 text-primary transition-transform duration-200 group-open:rotate-45">+</span>
					</summary>
					<p class="mt-3 text-muted-foreground leading-relaxed">{faq.a}</p>
				</details>
			{/each}
		</div>
	</section>
</div>

// apps/main-app-nextjs/app/[country]/get-quotes/page.tsx
/**
 * `/{cc}/get-quotes` — the standalone quote request. 2 pages (IN and US).
 *
 * The one page whose whole job is the lead form. Everywhere else the form is a
 * section of a page about a place; here the page is about the form, so the
 * structure is: what you get, the form, how it works, and the FAQ that answers
 * the objections to filling it in.
 *
 * It reuses `LeadFormSection` rather than growing a second form. That
 * component takes a `place` and interpolates it into the heading and the
 * offer, which is exactly right for a district page and needs a sensible value
 * here — this page is not about a place, so it passes the country's name. The
 * alternative was a second variant of the copy, which is two strings to keep
 * in step for one page.
 *
 * **The counts are not country-scoped**, matching the SvelteKit loader. See
 * `lib/forms/data.ts`, which records why narrowing them would change a
 * published figure.
 *
 * The FAQ copy is IN-specific in the original — it says "in India" and quotes
 * rupee expectations. It is carried across as written and gated to IN rather
 * than being generalised: /us gets the page without the FAQ, which is what a
 * page with no US answers should show. Writing US answers is a content task.
 */
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { FolderCheck, Users } from 'lucide-react';
import { PageShell, Section, Stack } from '@/components/layout';
import { Breadcrumb, FAQ, LeadFormSection, type FaqEntry } from '@/components/directory';
import { StatTile } from '@/components/tools/Panel';
import { getCountry, isCountry } from '@/lib/countries';
import { getQuoteCounts } from '@/lib/forms/data';
import { breadcrumbLD, faqLD } from '@/lib/directory/structuredData';
import { pageMetadata } from '@/lib/metadata';

/**
 * The SvelteKit loader sets `isr: { expiration: false }` — cache forever, no
 * revalidation. That is not carried across: the page prints two live counts,
 * and a permanent cache means they are the counts from whenever the page was
 * first built. 15 days, the same window as every other page in this tree.
 */
export const revalidate = 1296000;

/** Empty on purpose — see "ISR needs `generateStaticParams` too" in the README. */
export async function generateStaticParams() {
  return [];
}

/**
 * Three questions, carried across from the SvelteKit head's FAQPage block. The
 * page renders the same array it feeds to the structured data, so the markup
 * cannot claim a question the page does not show.
 */
const FAQS_IN: FaqEntry[] = [
  {
    question: 'Where can I get a solar quotation online in India?',
    answer:
      'You can get a free solar quotation online at Solar Vipani. Fill the inquiry form on this page with your location and energy requirements, and you will receive competitive quotations from 2-3 verified solar installers near you — entirely online, with no obligation.'
  },
  {
    question: 'Is the online solar quotation free?',
    answer:
      'Yes. Requesting a solar quotation online through Solar Vipani is completely free. You only deal with verified installers, compare their quotations, and decide if you want to proceed — there is no charge for the quotes.'
  },
  {
    question: 'How long does it take to receive my solar quotation?',
    answer:
      'After you submit the form online, you typically receive 2-3 competitive quotations from verified installers within 24 hours.'
  }
];

const STEPS = [
  {
    title: 'Fill the form',
    body: 'Share your location and what you need. It takes less than a minute.'
  },
  {
    title: 'Receive 2–3 quotations',
    body: 'Verified installers who cover your area quote for the work, usually within 24 hours.'
  },
  {
    title: 'Compare and choose',
    body: 'Compare prices, equipment and reviews, then pick the installer that suits you.'
  }
];

export async function generateMetadata({
  params
}: {
  params: Promise<{ country: string }>;
}): Promise<Metadata> {
  const { country } = await params;
  if (!isCountry(country)) return {};
  const config = getCountry(country);

  // Memoised for the request, so the page below re-reads this rather than
  // running both counts a second time.
  const { installerCount, projectCount } = await getQuoteCounts();

  return pageMetadata({
    title: 'Get a Free Solar Quotation Online',
    description: `Get a free solar quotation online from verified solar panel installers in ${config.name}. Compare 2-3 competitive quotations on price, services and reviews. ${installerCount}+ installers, ${projectCount}+ completed projects.`,
    path: `/${country}/get-quotes`,
    locale: config.locale,
    imageAlt: `Get free solar quotes in ${config.name}`
  });
}

export default async function Page({ params }: { params: Promise<{ country: string }> }) {
  const { country } = await params;
  if (!isCountry(country)) notFound();
  const config = getCountry(country);

  const { installerCount, projectCount } = await getQuoteCounts();
  const faqs = country === 'in' ? FAQS_IN : [];

  const trail = [{ name: 'Home', href: `/${country}` }, { name: 'Get Quotes' }];

  return (
    <PageShell>
      <Section width="narrow">
        <Stack gap="md">
          <Breadcrumb trail={trail} />
          <header>
            <h1 className="text-2xl leading-tight">Get a free solar quotation online</h1>
            <p className="mt-sm text-ink-muted">
              Tell us what you need once. Verified installers who cover your area come back with
              2–3 competitive quotations, usually within 24 hours. No cost, no obligation.
            </p>
          </header>
        </Stack>
      </Section>

      <Section width="narrow">
        {/* Two tiles, so 2-up holds at every width — the orphan the district
            page has to avoid cannot happen here. `gap-md` matches the tools'
            tile rows. */}
        <div className="grid grid-cols-2 gap-md">
          <StatTile
            icon={Users}
            value={`${installerCount.toLocaleString(config.locale)}+`}
            label="Verified installers"
          />
          <StatTile
            icon={FolderCheck}
            value={`${projectCount.toLocaleString(config.locale)}+`}
            label="Verified projects"
          />
        </div>
      </Section>

      <Section width="narrow">
        {/* `place` is the country name: this page is not about one place, and
            the component's copy needs something to name. */}
        <LeadFormSection country={config} place={config.name} />
      </Section>

      <Section width="narrow">
        <h2 className="text-xl">How it works</h2>
        {/* An ordered list because the steps are a sequence. The original
            numbered three cards by hand with a styled circle; the number is
            the semantics, so it comes from the list. */}
        <ol className="mt-lg flex list-decimal flex-col gap-md pl-md">
          {STEPS.map((step) => (
            <li key={step.title}>
              <h3 className="text-base font-semibold">{step.title}</h3>
              <p className="mt-2xs text-sm text-ink-muted">{step.body}</p>
            </li>
          ))}
        </ol>
      </Section>

      {faqs.length > 0 ? (
        <Section width="narrow">
          <FAQ items={faqs} heading="Frequently asked questions" />
        </Section>
      ) : null}

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify([
            breadcrumbLD(trail),
            ...(faqs.length > 0 ? [faqLD(faqs)] : [])
          ])
        }}
      />
    </PageShell>
  );
}
