// apps/main-app-nextjs/components/directory/Breadcrumb.tsx
/**
 * Breadcrumb for the directory surface.
 *
 * Takes real hrefs rather than labels alone, because it also feeds the
 * BreadcrumbList structured data on the page — and a breadcrumb whose visible
 * trail and whose markup can disagree is worse than none.
 */

export type Crumb = { name: string; href?: string };

export function Breadcrumb({ trail }: { trail: Crumb[] }) {
  return (
    <nav aria-label="Breadcrumb">
      <ol className="flex flex-wrap items-center gap-x-xs gap-y-2xs text-xs text-ink-muted">
        {trail.map((c, i) => (
          <li key={c.name} className="flex items-center gap-x-xs">
            {i === trail.length - 1 || !c.href ? (
              <span className="text-ink">{c.name}</span>
            ) : (
              <>
                <a href={c.href}>{c.name}</a>
                <span aria-hidden className="text-ink-subtle">
                  /
                </span>
              </>
            )}
          </li>
        ))}
      </ol>
    </nav>
  );
}

// apps/main-app/src/lib/components/seo/Breadcrumb.svelte
<script lang="ts">
	let { items }: {
		items: { name: string; href: string }[];
	} = $props();
</script>

<nav class="text-sm text-muted-foreground mb-6" aria-label="Breadcrumb">
	<ol class="flex flex-wrap gap-1">
		{#each items as item, i}
			{#if i < items.length - 1}
				<li><a href={item.href} class="hover:text-primary">{item.name}</a> /</li>
			{:else}
				<li class="text-foreground font-medium">{item.name}</li>
			{/if}
		{/each}
	</ol>
</nav>
