// apps/main-app-nextjs/components/directory/SubsidySection.tsx
/**
 * PM Surya Ghar subsidy. geo-listing.md §5 section 10, gated on
 * `features.subsidy` (IN only).
 *
 * The content is hardcoded, exactly as in the SvelteKit original. Worth
 * knowing why, because the loader looks like it disagrees: the SvelteKit
 * district page selects a `state_subsidies` row and then never passes it to
 * this section, which takes only the place name. That query is dead and is not
 * ported (see lib/directory/data.ts). Nothing here reads the database.
 *
 * Three things changed in the port, all of them rule 1 and rule 2:
 *
 *  - The table head was `bg-primary` with white text — the interaction hue
 *    filling a strip that cannot be interacted with. It is `surface-sunken`
 *    with ink now, which is what the elevation scale is for: things on the
 *    page are separated by a line, not by colour.
 *  - The subsidy column was `text-success`. A subsidy is not a status; it is
 *    the number the reader came for, so it is ink and semibold, and the
 *    status hue goes back to meaning status.
 *  - The "Sample PDF" column is gone. It lazy-loaded jsPDF to generate a
 *    quotation — a separate feature with its own dependency and its own client
 *    boundary, and porting it here would have made a table of five constants
 *    into an interactive leaf. It comes across on its own or not at all.
 *
 * Money is tabular-nums and right-aligned so the four cost columns scan
 * down rather than across, which is the whole reason this is a table.
 */

const ROWS = [
  {
    size: '1 kW',
    gross: '₹65,000 – ₹80,000',
    subsidy: '₹30,000',
    net: '₹35,000 – ₹50,000',
    savings: '~₹7,000'
  },
  {
    size: '2 kW',
    gross: '₹1,30,000 – ₹1,60,000',
    subsidy: '₹60,000',
    net: '₹70,000 – ₹1,00,000',
    savings: '~₹14,000'
  },
  {
    size: '3 kW',
    gross: '₹1,80,000 – ₹2,20,000',
    subsidy: '₹78,000',
    net: '₹1,02,000 – ₹1,42,000',
    savings: '~₹21,000'
  },
  {
    size: '5 kW',
    gross: '₹2,80,000 – ₹3,50,000',
    subsidy: '₹78,000',
    net: '₹2,02,000 – ₹2,72,000',
    savings: '~₹35,000'
  },
  {
    size: '10 kW',
    gross: '₹5,50,000 – ₹7,00,000',
    subsidy: '₹78,000',
    net: '₹4,72,000 – ₹6,22,000',
    savings: '~₹70,000'
  }
];

const HOW_IT_WORKS = [
  'Subsidy is ₹30,000/kW for the first 2 kW',
  'Additional ₹18,000 for capacity between 2–3 kW',
  'Maximum central subsidy is capped at ₹78,000',
  'Subsidy is credited directly to your bank account',
  'Installer must be DISCOM-empanelled to avail subsidy'
];

const STEPS = [
  'Register at pmsuryaghar.gov.in',
  'Get feasibility approval from your DISCOM',
  'Install via a DISCOM-empanelled installer',
  'Submit documents: installation report and net meter application',
  'Subsidy credited within 30 days of inspection'
];

const HEAD = 'px-sm py-xs text-left text-xs font-semibold uppercase tracking-wide text-ink-muted';
const CELL = 'px-sm py-xs text-sm';
const NUM = `${CELL} text-right tabular-nums whitespace-nowrap`;

export function SubsidySection({ place }: { place: string }) {
  return (
    <>
      <h2 className="text-xl">Solar subsidy in {place} — PM Surya Ghar Yojana</h2>
      <p className="mt-sm max-w-prose text-ink-muted">
        The central government&rsquo;s PM Surya Ghar Yojana pays a direct subsidy on residential
        rooftop solar. It is credited to your bank account after installation and grid connection.
      </p>

      {/* The table is wider than a phone and stays a table: five costs that
          have to be compared down a column are not a list. It scrolls
          sideways, with the size column doing the labelling. */}
      <div className="mt-lg overflow-x-auto">
        <table className="w-full min-w-[36rem] border-collapse">
          <thead>
            <tr className="border-b border-line-strong bg-surface-sunken">
              <th scope="col" className={HEAD}>
                System size
              </th>
              <th scope="col" className={`${HEAD} text-right`}>
                Gross cost
              </th>
              <th scope="col" className={`${HEAD} text-right`}>
                Central subsidy
              </th>
              <th scope="col" className={`${HEAD} text-right`}>
                Net cost
              </th>
              <th scope="col" className={`${HEAD} text-right`}>
                Est. annual savings
              </th>
            </tr>
          </thead>
          <tbody>
            {ROWS.map((r) => (
              <tr key={r.size} className="border-b border-line last:border-b-0">
                <th scope="row" className={`${CELL} text-left font-semibold`}>
                  {r.size}
                </th>
                <td className={`${NUM} text-ink-muted`}>{r.gross}</td>
                <td className={`${NUM} font-semibold`}>{r.subsidy}</td>
                <td className={`${NUM} font-semibold`}>{r.net}</td>
                <td className={`${NUM} text-ink-muted`}>{r.savings}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-lg grid gap-md sm:grid-cols-2">
        <div className="rounded-lg border border-line bg-surface p-md">
          <h3 className="text-base">How the subsidy works</h3>
          <ul className="mt-sm list-disc space-y-2xs pl-md text-sm text-ink-muted">
            {HOW_IT_WORKS.map((line) => (
              <li key={line}>{line}</li>
            ))}
          </ul>
        </div>
        <div className="rounded-lg border border-line bg-surface p-md">
          <h3 className="text-base">Steps to get the subsidy</h3>
          <ol className="mt-sm list-decimal space-y-2xs pl-md text-sm text-ink-muted">
            {STEPS.map((line) => (
              <li key={line}>{line}</li>
            ))}
          </ol>
        </div>
      </div>

      <p className="mt-md max-w-prose text-2xs text-ink-subtle">
        Costs are indicative estimates for the {place} region. Final pricing depends on roof type,
        panel brand, inverter and installation complexity. Annual savings assume a ₹7/unit average
        tariff.
      </p>
    </>
  );
}

// apps/main-app/src/lib/components/SubsidySection.svelte
<script lang="ts">
	import * as Table from '$lib/components/ui/table';
	import * as Card from '$lib/components/ui/card';
	import { Button } from '$lib/components/ui/button';
	import { Download } from '@lucide/svelte';
	import { parseKw } from '$lib/in/sampleQuotation';

	interface Props {
		city: string;
		pageUrl?: string;
	}

	const { city, pageUrl }: Props = $props();

	let downloadingKw = $state<number | null>(null);

	async function downloadSample(sizeLabel: string) {
		const kw = parseKw(sizeLabel);
		if (kw <= 0 || downloadingKw !== null) return;
		downloadingKw = kw;
		try {
			const { generateSampleQuotationPdf } = await import('$lib/in/sampleQuotationPdf');
			await generateSampleQuotationPdf({ kw, systemType: 'On-Grid', city, pageUrl });
		} catch (e) {
			console.error('Failed to generate sample quotation', e);
		} finally {
			downloadingKw = null;
		}
	}

	const subsidyRows = [
		{ size: '1 kW', grossCost: '₹65,000 – ₹80,000', centralSubsidy: '₹30,000', netCost: '₹35,000 – ₹50,000', annualSavings: '~₹7,000' },
		{ size: '2 kW', grossCost: '₹1,30,000 – ₹1,60,000', centralSubsidy: '₹60,000', netCost: '₹70,000 – ₹1,00,000', annualSavings: '~₹14,000' },
		{ size: '3 kW', grossCost: '₹1,80,000 – ₹2,20,000', centralSubsidy: '₹78,000', netCost: '₹1,02,000 – ₹1,42,000', annualSavings: '~₹21,000' },
		{ size: '5 kW', grossCost: '₹2,80,000 – ₹3,50,000', centralSubsidy: '₹78,000', netCost: '₹2,02,000 – ₹2,72,000', annualSavings: '~₹35,000' },
		{ size: '10 kW', grossCost: '₹5,50,000 – ₹7,00,000', centralSubsidy: '₹78,000', netCost: '₹4,72,000 – ₹6,22,000', annualSavings: '~₹70,000' },
	];
</script>

<section id="subsidy-section" class="mb-8 rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] shadow-[theme(--shadow-md)]">
	<div class="text-center mb-8">
		<h2 class="text-3xl md:text-4xl font-semibold mb-4 text-primary">
			Solar Subsidy in {city} — PM Surya Ghar Yojana
		</h2>
		<div class="flex justify-center items-center my-4">
			<span class="w-[theme(--divider-line-width)] h-[theme(--divider-line-height)] bg-accent rounded"></span>
		</div>
		<p class="text-foreground dark:text-foreground-secondary max-w-2xl mx-auto text-base leading-relaxed">
			The central government's <strong>PM Surya Ghar Yojana</strong> provides direct subsidies for residential rooftop solar installations. The subsidy is credited directly to your bank account after installation and grid connection.
		</p>
	</div>

	<Card.Root class="border-0 shadow-[theme(--shadow-card)] mb-8">
		<Card.Content class="p-0">
			<div class="overflow-x-auto">
				<Table.Root>
					<Table.Header>
						<Table.Row class="bg-primary">
							<Table.Head class="text-primary-foreground uppercase font-semibold text-sm tracking-wider">System Size</Table.Head>
							<Table.Head class="text-primary-foreground uppercase font-semibold text-sm tracking-wider">Gross Cost</Table.Head>
							<Table.Head class="text-primary-foreground uppercase font-semibold text-sm tracking-wider">Central Subsidy</Table.Head>
							<Table.Head class="text-primary-foreground uppercase font-semibold text-sm tracking-wider">Net Cost After Subsidy</Table.Head>
							<Table.Head class="text-primary-foreground uppercase font-semibold text-sm tracking-wider">Est. Annual Savings</Table.Head>
							<Table.Head class="text-primary-foreground uppercase font-semibold text-sm tracking-wider">Sample Quote</Table.Head>
						</Table.Row>
					</Table.Header>
					<Table.Body>
						{#each subsidyRows as row, idx}
							<Table.Row class={idx % 2 === 0 ? 'bg-muted' : ''}>
								<Table.Cell class="font-semibold text-primary">{row.size}</Table.Cell>
								<Table.Cell>{row.grossCost}</Table.Cell>
								<Table.Cell class="font-semibold text-success">{row.centralSubsidy}</Table.Cell>
								<Table.Cell class="font-semibold">{row.netCost}</Table.Cell>
								<Table.Cell class="text-foreground-secondary text-sm">{row.annualSavings}</Table.Cell>
								<Table.Cell>
									<Button
										variant="outline"
										size="sm"
										class="whitespace-nowrap"
										disabled={downloadingKw !== null}
										onclick={() => downloadSample(row.size)}
									>
										<Download size={14} />
										{downloadingKw === parseKw(row.size) ? 'Preparing…' : 'Sample PDF'}
									</Button>
								</Table.Cell>
							</Table.Row>
						{/each}
					</Table.Body>
				</Table.Root>
			</div>
		</Card.Content>
	</Card.Root>

	<div class="grid grid-cols-1 md:grid-cols-2 gap-[theme(--card-gap)] mb-8">
		<div class="rounded-[theme(--radius-md)] bg-[hsl(var(--accent)/0.1)] p-4">
			<strong class="block text-base font-semibold text-primary mb-2">How the Subsidy Works</strong>
			<ul class="text-sm text-foreground dark:text-foreground-secondary space-y-1 list-disc list-inside leading-relaxed">
				<li>Subsidy is ₹30,000/kW for first 2 kW</li>
				<li>Additional ₹18,000 for capacity between 2–3 kW</li>
				<li>Maximum central subsidy is capped at ₹78,000</li>
				<li>Subsidy is credited directly to your bank account</li>
				<li>Installer must be DISCOM-empanelled to avail subsidy</li>
			</ul>
		</div>
		<div class="rounded-[theme(--radius-md)] bg-[hsl(var(--accent)/0.1)] p-4">
			<strong class="block text-base font-semibold text-primary mb-2">Steps to Get the Subsidy</strong>
			<ol class="text-sm text-foreground dark:text-foreground-secondary space-y-1 list-decimal list-inside leading-relaxed">
				<li>Register at <strong>pmsuryaghar.gov.in</strong></li>
				<li>Get feasibility approval from your DISCOM</li>
				<li>Install via a DISCOM-empanelled installer</li>
				<li>Submit documents: installation report + net meter application</li>
				<li>Subsidy credited within 30 days of inspection</li>
			</ol>
		</div>
	</div>

	<p class="text-xs text-muted-foreground text-center mb-8">
		* Costs are indicative estimates for {city} region. Final pricing depends on roof type, panel brand, inverter, and installation complexity. Annual savings based on ₹7/unit average tariff.
	</p>

</section>
