// apps/main-app-nextjs/components/chat/widgets/SubsidyDisplay.tsx
import { formatCurrency } from '@/lib/chat/format';
import { Panel, StatRow, WidgetShell, type ToolData } from './parts';

export function SubsidyDisplay({ data }: { data: ToolData }) {
  const subsidies: ToolData[] = Array.isArray(data.subsidies) ? data.subsidies : [];
  return (
    <WidgetShell
      emoji="🏛️"
      title="Available Subsidies & Incentives"
      subtitle={data.location ? `in ${data.location}` : undefined}
    >
      {subsidies.map((subsidy, i) => (
        <Panel key={i}>
          <div>
            <h5 className="text-sm font-semibold">{subsidy.scheme}</h5>
            {subsidy.provider && <p className="text-xs text-ink-muted">{subsidy.provider}</p>}
          </div>
          <StatRow label="Benefit" value={subsidy.subsidy_amount} accent />
          {subsidy.total_subsidy && (
            <StatRow label="Total" value={formatCurrency(subsidy.total_subsidy)} accent strong />
          )}
        </Panel>
      ))}
    </WidgetShell>
  );
}

// apps/main-app/src/lib/in/components/chat/widgets/SubsidyDisplay.svelte
<script lang="ts">
  import WidgetShell from "./WidgetShell.svelte";
  import StatRow from "./StatRow.svelte";
  import { formatCurrency } from "../format";

  let { data }: { data: any } = $props();

  let subsidies = $derived(Array.isArray(data?.subsidies) ? data.subsidies : []);
</script>

<WidgetShell
  emoji="🏛️"
  title="Available Subsidies &amp; Incentives"
  subtitle={data.location ? `in ${data.location}` : ""}
>
  {#each subsidies as subsidy}
    <div class="flex flex-col gap-[theme(--form-element-field-gap)] p-[theme(--form-element-field-gap)] rounded-[theme(--radius-md)] bg-[hsl(var(--card))] border border-[hsl(var(--border))]">
      <div>
        <h5 class="text-sm font-semibold text-[hsl(var(--foreground))]">{subsidy.scheme}</h5>
        {#if subsidy.provider}
          <p class="text-xs text-[hsl(var(--muted-foreground))]">{subsidy.provider}</p>
        {/if}
      </div>
      <StatRow label="Benefit" value={subsidy.subsidy_amount} accent />
      {#if subsidy.total_subsidy}
        <StatRow label="Total" value={formatCurrency(subsidy.total_subsidy)} accent strong />
      {/if}
    </div>
  {/each}
</WidgetShell>
