// apps/main-app/src/routes/in/(layout-1)/about-us/+page.svelte
<script>
  import { Card } from "$lib/components/ui/card";

  const socialLinks = [
    {
      label: "Facebook",
      url: "https://www.facebook.com/p/Solar-Vipani-61556033262509/",
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>',
    },
    {
      label: "Twitter",
      url: "https://x.com/Solarvipani",
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>',
    },
    {
      label: "LinkedIn",
      url: "https://www.linkedin.com/company/solar-vipani/",
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>',
    },
    {
      label: "Instagram",
      url: "https://www.instagram.com/solar.vipani/",
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>',
    },
    {
      label: "WhatsApp",
      url: "https://wa.me/918983066701",
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>',
    },
  ];
</script>

<svelte:head>
  <title
    >About Us | Solar Vipani - Your Trusted Solar Panel Installation Marketplace</title
  >
  <meta
    name="description"
    content="Learn more about Solar Vipani and our mission to connect you with trusted local solar panel installers. We provide reliable information for a smart, hassle-free solar journey."
  />
</svelte:head>

<main class="w-full bg-background text-foreground transition-colors duration-300 overflow-x-hidden dark:bg-background dark:text-foreground">
  <div class="mx-auto max-w-[1140px] p-[theme(--container-padding)]">
    <!-- Hero Section -->
    <section class="rounded-[theme(--radius-lg)] bg-gradient-to-r from-primary to-primary text-primary-foreground p-[theme(--card-padding-y)] shadow-[theme(--shadow-md)]">
      <div class="text-center mb-[theme(--card-gap)]">
        <h1 class="text-4xl md:text-5xl font-bold mb-4 text-primary-foreground">About Solar Vipani</h1>
        <div class="flex justify-center items-center my-4">
          <span class="w-[theme(--divider-line-width)] h-[theme(--divider-line-height)] bg-accent rounded"></span>
        </div>
        <p class="text-xl text-primary-foreground max-w-2xl mx-auto">
          Your trusted marketplace for solar energy solutions
        </p>
      </div>
    </section>

    <!-- Introduction Section -->
    <section class="rounded-[theme(--radius-lg)] bg-accent-muted p-[theme(--card-padding-y)] mb-[theme(--card-gap)] shadow-[theme(--shadow-md)]">
      <div>
        <p class="text-lg font-medium text-primary mb-6">
          Our platform is designed for homeowners and businesses ready to go
          solar but unsure where to start.
        </p>
        <p class="text-base text-foreground dark:text-foreground-secondary mb-6 leading-relaxed">
          Finding the right solar panel installer can be overwhelming. We
          simplify this process by connecting you with verified installers,
          ensuring competitive pricing, and giving you peace of mind.
        </p>
        <div class="bg-accent text-foreground p-3 rounded-[theme(--radius-md)] mb-6 text-center">
          <p class="text-base">
            <strong
              >We make solar panel installation easy, affordable, and secure by
              matching homeowners and business with reliable local installers
              through our marketplace.</strong
            >
          </p>
        </div>
        <p class="text-base text-foreground dark:text-foreground-secondary leading-relaxed">
          This is a platform where your journey to a sustainable future is
          streamlined, informed, and supported by digital expertise. We're not
          manufacturers or installers of solar products—instead, we're your
          trusted guide, a digital marketplace that connects you with the top
          Solar installation companies, Solar EPC (Engineering, Procurement, and
          Construction) companies. By bringing together verified solar experts
          and valuable insights, Solar Vipani simplifies your path to solar
          energy adoption.
        </p>
      </div>
    </section>

    <!-- Stats Grid -->
    <section class="rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] mb-[theme(--card-gap)] shadow-[theme(--shadow-md)]">
      <div class="grid grid-cols-1 md:grid-cols-3 gap-[theme(--card-gap)]">
        <Card class="p-4 border-t-[theme(--card-accent-border)] border-accent hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-md)] transition-all text-center">
          <div class="text-4xl font-bold text-primary mb-2">500+</div>
          <h3 class="text-xl font-semibold text-primary mb-2">Verified Businesses</h3>
          <p class="text-foreground dark:text-foreground-secondary">Listed across India</p>
        </Card>
        <Card class="p-4 border-t-[theme(--card-accent-border)] border-accent hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-md)] transition-all text-center">
          <div class="text-4xl font-bold text-primary mb-2">5,000+</div>
          <h3 class="text-xl font-semibold text-primary mb-2">Cities & Towns</h3>
          <p class="text-foreground dark:text-foreground-secondary">Nationwide coverage</p>
        </Card>
        <Card class="p-4 border-t-[theme(--card-accent-border)] border-accent hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-md)] transition-all text-center">
          <div class="text-4xl font-bold text-primary mb-2">100%</div>
          <h3 class="text-xl font-semibold text-primary mb-2">Quality Assured</h3>
          <p class="text-foreground dark:text-foreground-secondary">Verified solar providers</p>
        </Card>
      </div>
    </section>

    <!-- Purpose Section -->
    <section class="rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] mb-[theme(--card-gap)] shadow-[theme(--shadow-md)]">
      <div class="text-center mb-[theme(--card-gap)]">
        <h2 class="text-3xl md:text-4xl font-semibold mb-4 text-primary">Our Purpose</h2>
        <div class="flex justify-center items-center my-4">
          <span class="w-[theme(--divider-line-width)] h-[theme(--divider-line-height)] bg-accent rounded"></span>
        </div>
      </div>
      <p class="text-base text-foreground dark:text-foreground-secondary leading-relaxed">
        At Solar Vipani, we believe going solar should be a straightforward,
        empowering choice for everyone. Our mission is to make this transition
        as smooth as possible by <strong
          >connecting you with reputable solar providers who align with your
          specific needs and goals.</strong
        > With us, you can make confident, well-informed decisions that benefit both
        your wallet and the environment.
      </p>
    </section>

    <!-- Expertise Section -->
    <section class="rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] mb-[theme(--card-gap)] shadow-[theme(--shadow-md)]">
      <div class="text-center mb-[theme(--card-gap)]">
        <h2 class="text-3xl md:text-4xl font-semibold mb-4 text-primary">Our Digital Expertise</h2>
        <div class="flex justify-center items-center my-4">
          <span class="w-[theme(--divider-line-width)] h-[theme(--divider-line-height)] bg-accent rounded"></span>
        </div>
      </div>
      <p class="text-base text-foreground dark:text-foreground-secondary leading-relaxed">
        As a digital marketing company, we leverage our <strong
          >deep expertise in local search engine optimization, social media and
          search engine advertising</strong
        > to ensure you connect with only the most qualified, certified solar providers
        in your area. We're passionate about simplifying complex choices through
        smart, data-driven connections, so you get the information you need to make
        sustainable decisions without any guesswork.
      </p>
    </section>

    <!-- Why Choose Us Section -->
    <section class="rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] mb-[theme(--card-gap)] shadow-[theme(--shadow-md)]">
      <div class="text-center mb-[theme(--card-gap)]">
        <h2 class="text-3xl md:text-4xl font-semibold mb-4 text-primary">Why Choose Solar Vipani?</h2>
        <div class="flex justify-center items-center my-4">
          <span class="w-[theme(--divider-line-width)] h-[theme(--divider-line-height)] bg-accent rounded"></span>
        </div>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-[theme(--card-gap)]">
        <Card class="p-4 hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-sm)] transition-all text-center">
          <div class="text-4xl mb-4 block">⚡</div>
          <h3 class="text-lg font-semibold text-primary mb-3">Quality Assurance</h3>
          <p class="text-foreground dark:text-foreground-secondary text-sm">
            We rigorously screen every Solar EPC company on our platform, so
            you're only matched with trusted industry leaders.
          </p>
        </Card>
        <Card class="p-4 hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-sm)] transition-all text-center">
          <div class="text-4xl mb-4 block">📊</div>
          <h3 class="text-lg font-semibold text-primary mb-3">Unbiased Information</h3>
          <p class="text-foreground dark:text-foreground-secondary text-sm">
            Solar Vipani is built to inform, not sell. Our platform provides
            objective, detailed information on each solar provider.
          </p>
        </Card>
        <Card class="p-4 hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-sm)] transition-all text-center">
          <div class="text-4xl mb-4 block">🔍</div>
          <h3 class="text-lg font-semibold text-primary mb-3">Effortless Comparisons</h3>
          <p class="text-foreground dark:text-foreground-secondary text-sm">
            Comparing options is as easy as browsing. Get insights on service
            quality, equipment standards, and financial benefits at a glance.
          </p>
        </Card>
        <Card class="p-4 hover:shadow-[theme(--shadow-card-hover)] hover:-translate-y-[theme(--hover-lift-sm)] transition-all text-center">
          <div class="text-4xl mb-4 block">🎯</div>
          <h3 class="text-lg font-semibold text-primary mb-3">Customer-First Support</h3>
          <p class="text-foreground dark:text-foreground-secondary text-sm">
            Our support team is dedicated to guiding you through every step,
            from initial inquiries to post-installation feedback.
          </p>
        </Card>
      </div>
    </section>

    <!-- Call to Action Section -->
    <section class="rounded-[theme(--radius-lg)] bg-card p-[theme(--card-padding-y)] mb-[theme(--card-gap)] shadow-[theme(--shadow-md)]">
      <div class="text-center mb-[theme(--card-gap)]">
        <h2 class="text-3xl md:text-4xl font-semibold mb-4 text-primary">Building a Brighter Future, Together</h2>
        <div class="flex justify-center items-center my-4">
          <span class="w-[theme(--divider-line-width)] h-[theme(--divider-line-height)] bg-accent rounded"></span>
        </div>
      </div>
      <p class="text-base text-foreground dark:text-foreground-secondary leading-relaxed mb-6">
        Choosing solar isn't just about savings; it's about building a
        sustainable tomorrow. At Solar Vipani, we're committed to making that
        journey clear and accessible for every household and business. Whether
        you're exploring options for the first time or ready to dive in, we're
        here to guide you every step of the way.
      </p>
      <div class="bg-accent text-foreground p-3 rounded-[theme(--radius-md)] text-center">
        <p>
          <strong
            >Step into a Greener Future with Solar Vipani — where High
            Convenience, Best Price and Low Risk is assured through Design</strong
          >
        </p>
      </div>
    </section>

    <!-- Contact Information -->
    <section class="text-center p-[theme(--card-padding-y)] mb-[theme(--card-gap)]">
      <div class="mb-[theme(--card-gap)]">
        <p class="text-base mb-2">
          Write to us at
          <a href="mailto:admin@solarvipani.com" class="font-semibold text-primary hover:underline">admin@solarvipani.com</a>
          <br />
          or call us at <a href="tel:+918983066701" class="font-semibold text-primary hover:underline">+91 8983066701</a>
        </p>
      </div>

      <div class="mb-[theme(--card-gap)]">
        <h4 class="text-xl font-semibold text-foreground dark:text-foreground-secondary mb-4">Follow us on:</h4>
        <div class="flex justify-center gap-[theme(--card-gap)] flex-wrap">
          {#each socialLinks as link}
            <a
              href={link.url}
              target="_blank"
              aria-label={link.label}
              class="flex items-center gap-2 text-primary hover:text-primary-hover dark:hover:text-primary font-medium transition-colors hover:-translate-y-[theme(--hover-lift-sm)] transform"
            >
              {@html link.icon}
              <span>{link.label}</span>
            </a>
          {/each}
        </div>
      </div>

      <div class="border-t border-border pt-[theme(--card-padding-y)]">
        <p class="text-foreground dark:text-foreground-secondary">
          <a href="/in/terms-of-use" class="text-primary hover:underline">Terms of Use</a> |
          <a href="/in/privacy-policy" class="text-primary hover:underline">Privacy Policy</a>
        </p>
      </div>
    </section>
  </div>
</main>

// apps/main-app-nextjs/app/(layout-1)/about-us/page.tsx
/**
 * About Us. Ported from
 * apps/main-app/src/routes/(layout-1)/about-us/+page.svelte and its loader.
 *
 * Sans, not serif, and that is the one real design decision on the page. The
 * two legal pages next to it are documents you read top to bottom, so they
 * take Source Serif; this is a stat row, two card grids and eight short
 * paragraphs — UI, which design-foundation.md §6 gives to Inter.
 *
 * Every figure is counted live (lib/stats.ts). The SvelteKit page's own
 * comment records why: it used to claim "500+" businesses and "5,000+ Cities
 * & Towns" against 470 and 356 actual.
 *
 * Two blocks of the Svelte page do not come across:
 *
 *  - **the contact/legal strip at the bottom.** Terms, Privacy and the email
 *    are all in SiteFooter now, directly below this page. The Svelte page
 *    predates the shared footer and carried its own.
 *  - **the GitHub icon.** lucide-react dropped its brand glyphs in v1
 *    (ContactPanel.tsx hit the same thing with Instagram), so the repo link
 *    is a plain button. An icon here would be a vendored SVG for decoration.
 *
 * `AboutPage` JSON-LD is kept, minus `sameAs`: the SvelteKit version built it
 * from a `SOCIAL_LINKS` constant this app does not have, and asserting social
 * profiles that nothing on the page links to is exactly the mismatch
 * EditorialArticle.tsx avoids with its breadcrumb and FAQ markup.
 */
import type { Metadata } from 'next';
import { BookOpen, LifeBuoy, MapPin, Scale, TrendingUp, Users } from 'lucide-react';
import { PageShell, Section, Stack } from '@/components/layout';
import { getCountry } from '@/lib/countries';
import { BASE_URL } from '@/lib/directory/structuredData';
import { OG_IMAGE, pageMetadata } from '@/lib/metadata';
import { getPlatformStats } from '@/lib/stats';

const REPO_URL = 'https://github.com/arkanere/solar-app';

/**
 * 15 days, matching `config.isr.expiration` on the SvelteKit load and the
 * editorial routes. Without it the three counts are read once at build and
 * never move again — the page's own "counted live from our database" line
 * would stop being true the day after a deploy.
 */
export const revalidate = 1296000;

export const metadata: Metadata = pageMetadata({
  title: 'About Us',
  description:
    'Solar Vipani connects homeowners and businesses with local solar installers, and publishes the guides and tools to decide before you spend. Our platform is open source.',
  path: '/about-us',
  locale: getCountry('in').locale,
  imageAlt: 'Solar Vipani'
});

const OFFERINGS = [
  {
    title: 'Local installer listings',
    body: 'Browse solar companies by state, district and city, see the work they have completed, and request quotes from more than one before you commit.'
  },
  {
    title: 'Guides that explain the choice',
    body: 'Independent writing on rooftop solar, panels, inverters, solar pumps, subsidies and financing — written to educate before you spend, not to sell a brand.'
  },
  {
    title: 'Calculators and tools',
    body: 'Size a system against your electricity bill, check what subsidy you qualify for, and work out EMIs — so you can sanity-check a quote before you sign it.'
  },
  {
    title: 'Real installation projects',
    body: 'Photos, system sizes and locations from installations completed by companies on the platform, published by the installers themselves.'
  }
];

const REASONS = [
  {
    icon: Scale,
    title: 'Effortless Comparisons',
    body: 'Comparing options is as easy as browsing. See service area, completed work and contact details side by side, at a glance.'
  },
  {
    icon: BookOpen,
    title: 'Built to Inform, Not to Sell',
    body: 'We do not manufacture or install anything, so we have no product to push. Our guides describe trade-offs, including the ones that argue against going solar right now.'
  },
  {
    icon: MapPin,
    title: 'Local, Not National',
    body: 'Enquiries go to installers who actually work in your area, and to more than one of them, so you get comparable quotes from people who can service what they sell you.'
  },
  {
    icon: LifeBuoy,
    title: 'Customer-First Support',
    body: 'Our team is here to guide you through every step, from an initial question to feedback after your system is installed.'
  }
];

/** The shared card: a line around it, no shadow — design-foundation.md §7. */
function Card({ children, center = false }: { children: React.ReactNode; center?: boolean }) {
  return (
    <div className={`rounded-lg border border-line bg-surface p-md ${center ? 'text-center' : ''}`}>
      {children}
    </div>
  );
}

export default async function Page() {
  const stats = await getPlatformStats();
  const locale = getCountry('in').locale;

  const figures = [
    { icon: Users, value: stats.installerCount, label: 'Installers on the Platform' },
    { icon: MapPin, value: stats.citiesServed, label: 'Cities Served' },
    { icon: TrendingUp, value: stats.leadsGenerated, label: 'Leads Generated' }
  ];

  return (
    <PageShell>
      <Section width="content">
        <Stack gap="sm">
          <h1 className="text-2xl text-ink">About Solar Vipani</h1>
          <p className="text-lg text-ink-muted">
            Your trusted marketplace for solar energy solutions.
          </p>
        </Stack>
      </Section>

      <Section width="content">
        <div className="max-w-prose">
          <Stack gap="md">
            <p className="text-lg font-medium text-ink">
              Going solar is a decision you live with for 25 years, and it involves a significant
              amount of money.
            </p>
            <p className="text-ink-muted">
              Most people start that decision with no way to tell a good installer from a bad one,
              and no independent source for what a system should cost. Solar Vipani exists to close
              that gap. We are not a manufacturer and not an installer — we are the layer in
              between: a marketplace that connects you with local solar installation and EPC
              companies, and a library of guides and tools that let you judge their quotes for
              yourself.
            </p>
            <p className="rounded-md bg-accent-surface p-md font-medium text-ink">
              Compare multiple options, get free quotes from installers near you, and choose with
              the numbers in front of you.
            </p>
            <p className="text-ink-muted">
              Listing is free for installers, and we never charge you for a quote. You decide who to
              talk to, and you keep control of your details until you do.
            </p>
          </Stack>
        </div>
      </Section>

      <Section width="content">
        <Stack gap="md">
          <div className="grid grid-cols-1 gap-md md:grid-cols-3">
            {figures.map((figure) => (
              <Card key={figure.label} center>
                <div className="flex justify-center">
                  <figure.icon aria-hidden className="mb-xs h-6 w-6 text-action" />
                </div>
                <div className="text-2xl font-bold tabular-nums text-ink">
                  {figure.value.toLocaleString(locale)}+
                </div>
                {/* h2, not a div: each figure is a claim the page makes, and
                    the three of them are its first level of structure. */}
                <h2 className="text-lg text-ink-muted">{figure.label}</h2>
              </Card>
            ))}
          </div>
          <p className="text-center text-sm text-ink-subtle">
            Counted live from our database, across every country we operate in.
          </p>
        </Stack>
      </Section>

      <Section width="content">
        <div className="max-w-prose">
          <Stack gap="sm">
            <h2 className="text-xl text-ink">Our Purpose</h2>
            <p className="text-ink-muted">
              We believe going solar should be a straightforward, well-informed choice for everyone.
              Our mission is to make the transition as smooth as possible by{' '}
              <strong className="font-semibold text-ink">
                connecting you with solar providers who match your specific needs and goals
              </strong>
              , and by giving you enough information to know why they match. A decision that lasts
              25 years deserves more than a single quote from whoever knocked on your door.
            </p>
          </Stack>
        </div>
      </Section>

      <Section width="content">
        <div className="max-w-prose">
          <Stack gap="md">
            <h2 className="text-xl text-ink">Built in the Open</h2>
            <p className="text-ink-muted">
              A marketplace asks you to trust how it ranks and matches. We would rather you did not
              have to take that on faith:{' '}
              <strong className="font-semibold text-ink">Solar Vipani is open source</strong>. The
              code behind this site — how installers are matched to an enquiry, how our calculators
              work, how your data is handled — is public and MIT licensed. Read it, check our claims
              against it, or use it in your own project.
            </p>
            <div>
              <a
                href={REPO_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="btn btn-primary"
              >
                View the source on GitHub
              </a>
            </div>
          </Stack>
        </div>
      </Section>

      <Section width="content">
        <Stack gap="md">
          <h2 className="text-xl text-ink">What You&rsquo;ll Find Here</h2>
          <div className="grid grid-cols-1 gap-md md:grid-cols-2">
            {OFFERINGS.map((item) => (
              <Card key={item.title}>
                <h3 className="text-lg text-ink">{item.title}</h3>
                <p className="mt-xs text-sm text-ink-muted">{item.body}</p>
              </Card>
            ))}
          </div>
        </Stack>
      </Section>

      <Section width="content">
        <Stack gap="md">
          <h2 className="text-xl text-ink">Why Choose Solar Vipani?</h2>
          <div className="grid grid-cols-1 gap-md md:grid-cols-2">
            {REASONS.map((item) => (
              <Card key={item.title} center>
                <div className="flex justify-center">
                  <item.icon aria-hidden className="mb-sm h-8 w-8 text-action" />
                </div>
                <h3 className="text-lg text-ink">{item.title}</h3>
                <p className="mt-xs text-sm text-ink-muted">{item.body}</p>
              </Card>
            ))}
          </div>
        </Stack>
      </Section>

      <Section width="content">
        <div className="max-w-prose">
          <Stack gap="md">
            <h2 className="text-xl text-ink">Building a Brighter Future, Together</h2>
            <p className="text-ink-muted">
              Choosing solar isn&rsquo;t only about savings; it&rsquo;s about what your roof is
              doing for the next 25 years. Whether you are exploring the idea for the first time or
              already comparing quotes, we&rsquo;re here to make that path clear.
            </p>
            <p className="rounded-md bg-accent-surface p-md text-center font-medium text-ink">
              Step into a greener future with Solar Vipani — high convenience, fair pricing and low
              risk, by design.
            </p>
            <p className="text-ink-muted">
              Write to us at <a href="mailto:admin@solarvipani.com">admin@solarvipani.com</a> or
              call us at <a href="tel:+918983066701">+91 8983066701</a>.
            </p>
          </Stack>
        </div>
      </Section>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'AboutPage',
            name: 'About Solar Vipani',
            url: `${BASE_URL}/about-us`,
            mainEntity: {
              '@type': 'Organization',
              name: 'Solar Vipani',
              url: BASE_URL,
              logo: OG_IMAGE.url,
              description:
                'An open source marketplace connecting homeowners and businesses with local solar installers.',
              email: 'admin@solarvipani.com',
              telephone: '+91-8983066701',
              sameAs: [REPO_URL]
            }
          })
        }}
      />
    </PageShell>
  );
}
