// apps/main-app/src/lib/components/chrome/SiteFooter.svelte
<script lang="ts">
  import type { CountryConfig } from "$lib/countries";
  import { contentUrl } from "$lib/countries/urls";

  // `country` is optional — see SiteHeader. Without it only the country-less
  // columns render.
  let { country }: { country?: CountryConfig } = $props();

  const cc = $derived(country?.code);
  const features = $derived(country?.features);
</script>

<footer class="border-t border-border bg-background text-foreground mt-8">
  <div class="mx-auto max-w-[1140px] p-[theme(--container-padding)]">
    <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-8 py-8">
      <!-- Solar Topics -->
      {#if !country || features?.seoContentFamilies}
        <div>
          <h4 class="text-sm font-semibold text-primary mb-3">Solar Topics</h4>
          <ul class="space-y-2 list-none p-0 m-0">
            {#each [
              { href: contentUrl("/rooftop-solar"), label: "Rooftop Solar" },
              { href: contentUrl("/solar-panels"), label: "Solar Panels" },
              { href: contentUrl("/solar-inverters"), label: "Solar Inverters" },
              { href: contentUrl("/solar-installation"), label: "Solar Installation" },
              { href: contentUrl("/solar-subsidy"), label: "Solar Subsidy" },
              { href: contentUrl("/solar-financing"), label: "Solar Financing" },
              { href: contentUrl("/solar-pumps"), label: "Solar Pumps" },
            ] as link}
              <li><a href={link.href} class="text-sm text-foreground no-underline hover:text-primary transition-colors">{link.label}</a></li>
            {/each}
          </ul>
        </div>
      {/if}

      <!-- Find Solar (the directory and lead funnels are per-country) -->
      {#if country}
        <div>
          <h4 class="text-sm font-semibold text-primary mb-3">Find Solar</h4>
          <ul class="space-y-2 list-none p-0 m-0">
            <li><a href="/{cc}/solar" class="text-sm text-foreground no-underline hover:text-primary transition-colors">Solar Directory</a></li>
            {#if features?.projects}
              <li><a href="/{cc}/recent-solar-installation-projects" class="text-sm text-foreground no-underline hover:text-primary transition-colors">Recent Projects</a></li>
            {/if}
            {#if cc === 'in'}
              <li><a href="/{cc}/get-quotes" class="text-sm text-foreground no-underline hover:text-primary transition-colors">Get Quotes</a></li>
            {/if}
          </ul>
        </div>
      {/if}

      <!-- Company -->
      <div>
        <h4 class="text-sm font-semibold text-primary mb-3">Company</h4>
        <ul class="space-y-2 list-none p-0 m-0">
          <li><a href="/about-us" class="text-sm text-foreground no-underline hover:text-primary transition-colors">About Us</a></li>
          <!-- Installer acquisition. Each country's entry point is a different
               page: IN pitches at /in/partners, US at /us/business-listing —
               which is also what hooks.server.ts 301s /us/partners to. -->
          {#if cc === 'in'}
            <li><a href="/{cc}/partners" class="text-sm text-foreground no-underline hover:text-primary transition-colors">Partner with Us</a></li>
          {:else if cc === 'us'}
            <li><a href="/{cc}/business-listing" class="text-sm text-foreground no-underline hover:text-primary transition-colors">List Your Business</a></li>
          {/if}
        </ul>
      </div>

      <!-- Tools -->
      {#if !country || features?.tools}
        <div>
          <h4 class="text-sm font-semibold text-primary mb-3">Tools</h4>
          <ul class="space-y-2 list-none p-0 m-0">
            <li><a href={contentUrl("/tools/solar-calculator")} class="text-sm text-foreground no-underline hover:text-primary transition-colors">Solar Calculator</a></li>
            <li><a href={contentUrl("/tools/emi-calculator")} class="text-sm text-foreground no-underline hover:text-primary transition-colors">EMI Calculator</a></li>
            <li><a href={contentUrl("/tools/subsidy-checker")} class="text-sm text-foreground no-underline hover:text-primary transition-colors">Subsidy Checker</a></li>
          </ul>
        </div>
      {/if}

      <!-- Brand -->
      <div>
        <h4 class="text-sm font-semibold text-primary mb-3">Solar Vipani</h4>
        <p class="text-sm text-foreground dark:text-foreground-secondary leading-relaxed">
          The open-source platform helping homeowners and businesses go solar with confidence.
        </p>
      </div>
    </div>

    <div class="border-t border-border pt-4 pb-2 text-center">
      <p class="text-xs text-muted-foreground">&copy; {new Date().getFullYear()} Solar Vipani. All rights reserved.</p>
    </div>
  </div>
</footer>

// apps/main-app-nextjs/components/chrome/SiteFooter.tsx
/**
 * The site footer. Ported from apps/main-app/src/lib/components/chrome/SiteFooter.svelte.
 *
 * Same `country` contract as SiteHeader: without one, only the country-less
 * columns render.
 *
 * The original's hand-rolled `mx-auto max-w-[1140px]` is a <Container> here —
 * that is the lint rule the layout primitives exist to enforce, and it also
 * puts the footer on the same measure and the same gutter as every page above
 * it, which the 1140px never quite was.
 *
 * No <Stack>: the columns are a grid and the rows inside them are a <ul>, so
 * the rhythm is the grid's gap, not a stack of blocks.
 */
import type { CountryConfig } from '@/lib/countries';
import { contentUrl } from '@/lib/directory/urls';
import { Container } from '@/components/layout';

const LINK =
  'text-sm text-ink no-underline transition-colors duration-fast ease-standard hover:text-action';

const TOPICS = [
  { href: contentUrl('/rooftop-solar'), label: 'Rooftop Solar' },
  { href: contentUrl('/solar-panels'), label: 'Solar Panels' },
  { href: contentUrl('/solar-inverters'), label: 'Solar Inverters' },
  { href: contentUrl('/solar-installation'), label: 'Solar Installation' },
  { href: contentUrl('/solar-subsidy'), label: 'Solar Subsidy' },
  { href: contentUrl('/solar-financing'), label: 'Solar Financing' },
  { href: contentUrl('/solar-pumps'), label: 'Solar Pumps' }
];

const TOOLS = [
  { href: contentUrl('/tools/solar-calculator'), label: 'Solar Calculator' },
  { href: contentUrl('/tools/emi-calculator'), label: 'EMI Calculator' },
  { href: contentUrl('/tools/subsidy-checker'), label: 'Subsidy Checker' }
];

function Column({ title, links }: { title: string; links: { href: string; label: string }[] }) {
  return (
    <div>
      <h2 className="mb-sm text-sm font-semibold text-ink">{title}</h2>
      <ul className="flex flex-col gap-xs">
        {links.map((link) => (
          <li key={link.href}>
            <a href={link.href} className={LINK}>
              {link.label}
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
}

export function SiteFooter({ country }: { country?: CountryConfig }) {
  const cc = country?.code;
  const features = country?.features;

  const findSolar = country
    ? [
        { href: `/${cc}/solar`, label: 'Solar Directory' },
        ...(features?.projects
          ? [{ href: `/${cc}/recent-solar-installation-projects`, label: 'Recent Projects' }]
          : []),
        ...(cc === 'in' ? [{ href: `/${cc}/get-quotes`, label: 'Get Quotes' }] : [])
      ]
    : [];

  // Installer acquisition. Each country's entry point is a different page: IN
  // pitches at /in/partners, US at /us/business-listing — which is also what
  // the legacy hooks.server.ts 301s /us/partners to.
  const company = [
    { href: '/about-us', label: 'About Us' },
    ...(cc === 'in' ? [{ href: `/${cc}/partners`, label: 'Partner with Us' }] : []),
    ...(cc === 'us' ? [{ href: `/${cc}/business-listing`, label: 'List Your Business' }] : [])
  ];

  return (
    <footer className="mt-2xl border-t border-line bg-surface">
      <Container>
        <div className="grid grid-cols-2 gap-xl py-xl sm:grid-cols-3 lg:grid-cols-5">
          {!country || features?.seoContentFamilies ? (
            <Column title="Solar Topics" links={TOPICS} />
          ) : null}

          {country ? <Column title="Find Solar" links={findSolar} /> : null}

          <Column title="Company" links={company} />

          {!country || features?.tools ? <Column title="Tools" links={TOOLS} /> : null}

          <div>
            <h2 className="mb-sm text-sm font-semibold text-ink">Solar Vipani</h2>
            <p className="text-sm leading-relaxed text-ink-muted">
              The open-source platform helping homeowners and businesses go solar with confidence.
            </p>
          </div>
        </div>

        <div className="border-t border-line py-md text-center">
          <p className="text-2xs text-ink-subtle">
            &copy; {new Date().getFullYear()} Solar Vipani. All rights reserved.
          </p>
        </div>
      </Container>
    </footer>
  );
}
