// apps/main-app/src/routes/in/(layout-1)/business-listing/+page.svelte
<script module>
  // Enhanced data objects with icons
  const benefits = [
    {
      title: "Get Discovered Online",
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"></polygon></svg>',
      descriptions: [
        'Clients search for queries like "Solar Panel Installers Near Me", "Top Solar Panel installer in [CityName]"',
        "We rank on the first page of Google, Yahoo, CHATGPT, etc for such relevant queries",
      ],
    },
    {
      title: "Direct Customer Inquiries",
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>',
      descriptions: [
        "We display your business phone number, WhatsApp, email and address.",
        "This allows customers to reach out to you directly.",
      ],
    },
    {
      title: "Post Recent Projects",
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21,15 16,10 5,21"></polyline></svg>',
      descriptions: ["Showcase your workmanship to the potential customers."],
    },
    {
      title: "Enhance Online Presence",
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="7"></circle><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"></polyline></svg>',
      descriptions: [
        "Get dedicated page on website which has high rating for Solar Installation Domain.",
      ],
    },
    {
      title: "Strengthen Credibility",
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>',
      descriptions: [
        "Get a Verified Business tag that boosts client confidence",
      ],
    },
    {
      title: "Manage Multiple Branch Offices",
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18"></path><path d="M5 21V7l8-4v18"></path><path d="M19 21V11l-6-4"></path></svg>',
      descriptions: [
        "Expand your business reach by managing multiple branch locations under one main business profile.",
      ],
    },
  ];

  const faqs = [
    {
      question: "What is Solar Vipani?",
      answer:
        "Solar Vipani is India's leading platform connecting customers actively seeking solar installation with verified solar installers. We help grow your business by giving you direct access to qualified leads in your area.",
    },
    {
      question: "How much does it cost to list my business?",
      answer:
        "Listing your business is completely free of charge. We believe in providing value first and helping solar businesses grow their online presence without any upfront costs.",
    },
    {
      question:
        "Why should I list my business if I'm already getting customers?",
      answer:
        "Even if you have a steady customer base, listing on Solar Vipani significantly increases your online visibility, helping you reach even more potential customers who are actively searching for solar installation services. It's an additional channel that complements your existing marketing efforts.",
    },
  ];

  const stats = [
    { number: "450+", label: "Businesses Listed" },
    { number: "5,000+", label: "Cities & Towns" },
  ];
</script>

<script>
  import { goto } from "$app/navigation";
  import AboutSolarVipani from "$lib/in-new-rewrites/AboutSolarVipani.svelte";
  import { Button } from "$lib/components/ui/button";
  import { Card } from "$lib/components/ui/card";

  // For data loading
  let { data } = $props();

  // Navigation function
  const navigateToBusinessForm = () => goto("/in/business-form");
</script>

<svelte:head>
  <!-- Meta Pixel Code - Deferred for Performance -->
  <script>
    // Defer Facebook Pixel until after user interaction or 3 seconds
    function loadFacebookPixel() {
      !(function (f, b, e, v, n, t, s) {
        if (f.fbq) return;
        n = f.fbq = function () {
          n.callMethod
            ? n.callMethod.apply(n, arguments)
            : n.queue.push(arguments);
        };
        if (!f._fbq) f._fbq = n;
        n.push = n;
        n.loaded = !0;
        n.version = "2.0";
        n.queue = [];
        t = b.createElement(e);
        t.async = !0;
        t.src = v;
        s = b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t, s);
      })(
        window,
        document,
        "script",
        "https://connect.facebook.net/en_US/fbevents.js",
      );
      fbq("init", "1226087962095221");
      fbq("track", "PageView");
    }

    // Load on user interaction or after 3 seconds
    let pixelLoaded = false;
    function initPixel() {
      if (!pixelLoaded) {
        pixelLoaded = true;
        loadFacebookPixel();
      }
    }

    // Load on first user interaction
    ["mousedown", "touchstart", "keydown", "scroll"].forEach((event) => {
      document.addEventListener(event, initPixel, {
        once: true,
        passive: true,
      });
    });

    // Fallback after 3 seconds
    setTimeout(initPixel, 3000);
  </script>
  <noscript>
    <img
      height="1"
      width="1"
      style="display:none"
      src="https://www.facebook.com/tr?id=1226087962095221&ev=PageView&noscript=1"
      alt="Facebook Pixel tracking"
    />
  </noscript>
  <!-- End Meta Pixel Code -->

  <!-- Structured Data / JSON-LD - Minified -->
  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Organization",
      "name": "Solar Vipani",
      "url": "https://solarvipani.com",
      "logo": "https://solarvipani.com/images/solar-vipani-logo.png",
      "description": "India's leading solar panel installer directory connecting customers with verified solar installation services",
      "contactPoint": {
        "@type": "ContactPoint",
        "telephone": "+91-8983066701",
        "contactType": "customer service",
        "email": "admin@solarvipani.com",
        "availableLanguage": ["English", "Hindi"]
      },
      "address": { "@type": "PostalAddress", "addressCountry": "IN" },
      "sameAs": [
        "https://www.facebook.com/solarvipani",
        "https://www.linkedin.com/company/solarvipani",
        "https://twitter.com/solarvipani"
      ]
    }
  </script>
  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Service",
      "name": "Solar Business Directory Listing",
      "description": "Free business listing service for solar panel installers and solar energy companies",
      "provider": { "@type": "Organization", "name": "Solar Vipani" },
      "serviceType": "Business Directory",
      "areaServed": { "@type": "Country", "name": "India" },
      "offers": {
        "@type": "Offer",
        "price": "0",
        "priceCurrency": "INR",
        "description": "Free business listing for solar installers"
      }
    }
  </script>
  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [
        {
          "@type": "ListItem",
          "position": 1,
          "name": "Home",
          "item": "https://solarvipani.com"
        },
        {
          "@type": "ListItem",
          "position": 2,
          "name": "Business Listing",
          "item": "https://solarvipani.com/business-listing"
        }
      ]
    }
  </script>

  <title>List Your Solar Business | Solar Vipani</title>
  <meta
    name="description"
    content="Expand your solar business reach by listing on Solar Vipani. Connect with customers actively seeking solar installation services in your area."
  />
  <link rel="canonical" href="https://solarvipani.com/business-listing" />

  <!-- Preload critical hero images for faster LCP -->
  <link
    rel="preload"
    as="image"
    href="/header/header_mobile.avif"
    media="(max-width: 768px)"
    fetchpriority="high"
  />
  <link
    rel="preload"
    as="image"
    href="/header/header_desktop.avif"
    media="(min-width: 769px)"
    fetchpriority="high"
  />
  <!-- Preconnect to optimize external resources -->
  <link rel="preconnect" href="https://www.youtube.com" />
  <link rel="preconnect" href="https://connect.facebook.net" />

  <!-- Open Graph Tags -->
  <meta property="og:title" content="List Your Solar Business | Solar Vipani" />
  <meta
    property="og:description"
    content="Expand your solar business reach by listing on Solar Vipani. Connect with customers actively seeking solar installation services in your area."
  />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="https://solarvipani.com/business-listing" />
  <meta
    property="og:image"
    content="https://solarvipani.com/images/solar-business-listing-og.jpg"
  />
  <meta property="og:site_name" content="Solar Vipani" />
  <meta property="og:locale" content="en_IN" />

  <!-- Twitter Card Tags -->
  <meta name="twitter:card" content="summary_large_image" />
  <meta
    name="twitter:title"
    content="List Your Solar Business | Solar Vipani"
  />
  <meta
    name="twitter:description"
    content="Expand your solar business reach by listing on Solar Vipani. Connect with customers actively seeking solar installation services in your area."
  />
  <meta
    name="twitter:image"
    content="https://solarvipani.com/images/solar-business-listing-twitter.jpg"
  />
  <meta name="twitter:site" content="@solarvipani" />

  <!-- FAQ Schema - Minified -->
  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": [
        {
          "@type": "Question",
          "name": "How much does it cost to list my business?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Listing your business is completely free of charge. We believe in providing value first and helping solar businesses grow their online presence without any upfront costs."
          }
        },
        {
          "@type": "Question",
          "name": "How do you earn money if the business listing is free?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "We provide premium marketing services to select businesses where we see growth potential. These paid services include targeted campaigns on platforms like Facebook, Instagram, Google Search, and YouTube to further boost your visibility."
          }
        },
        {
          "@type": "Question",
          "name": "Why should I list my business if I'm already getting customers?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Even if you have a steady customer base, listing on Solar Vipani significantly increases your online visibility, helping you reach even more potential customers who are actively searching for solar installation services. It's an additional channel that complements your existing marketing efforts."
          }
        }
      ]
    }
  </script>

  <!-- Additional SEO Meta Tags -->
  <meta
    name="keywords"
    content="solar business listing, solar panel installer directory, solar business registration, solar installer network, solar business growth, solar marketing"
  />
  <meta name="author" content="Solar Vipani" />
  <meta name="robots" content="index, follow" />
</svelte:head>

<main class="w-full overflow-x-hidden bg-card text-foreground transition-colors duration-[theme(--transition-default)]">
  <!-- Hero Banner with Solar Panel Background -->
  <div class="relative w-full h-[theme(--height-md)] flex items-center justify-center text-center overflow-hidden md:h-[theme(--height-xl)]">
    <picture>
      <source
        media="(max-width: 768px)"
        srcset="/header/header_mobile.avif"
        type="image/avif"
      />
      <source
        media="(min-width: 769px)"
        srcset="/header/header_desktop.avif"
        type="image/avif"
      />
      <img
        class="absolute top-0 left-0 w-full h-full object-cover object-center z-0"
        src="/header/header_desktop.avif"
        alt="Solar Panel Installation Business Growth"
        width="1920"
        height="600"
        fetchpriority="high"
        decoding="async"
      />
    </picture>
    <div class="absolute top-0 left-0 w-full h-full z-10 bg-black/55"></div>
    <div class="relative z-20 max-w-3xl px-6">
      <h1 class="text-4xl md:text-4xl font-bold mb-6 text-primary-foreground leading-tight drop-shadow-lg">
        Grow Your Solar Business
      </h1>
      <h2 class="text-2xl md:text-2xl font-medium mb-6 text-primary-foreground leading-snug drop-shadow-lg">
        Get discovered by customers researching online
      </h2>
    </div>
  </div>

  <div class="mx-auto max-w-[1140px] p-[theme(--container-padding)]">
    <!-- Value Proposition Section -->
    <Card class="p-[theme(--card-padding-y)] mb-[theme(--spacing-2xl)]">
      <div class="text-center mb-[theme(--spacing-2xl)]">
        <h2 class="text-2xl md:text-4xl font-semibold text-primary mb-[theme(--spacing-lg)]">Why List Your Business with Solar Vipani?</h2>
        <div class="flex justify-center items-center my-[theme(--spacing-lg)]">
          <span class="w-20 h-1 bg-accent rounded"></span>
        </div>
        <p class="text-lg text-foreground dark:text-foreground-secondary max-w-2xl mx-auto">
          Get discovered by customers ready to install solar panels - completely <span
            class="text-accent font-bold">FREE</span
          >
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-3 gap-[theme(--card-gap)] mb-[theme(--spacing-2xl)]">
        {#each benefits as benefit}
          <Card class="text-center flex flex-col items-center p-[theme(--spacing-lg)]">
            <div class="w-16 h-16 flex items-center justify-center text-primary mb-[theme(--spacing-lg)] rounded-full bg-primary/10">{@html benefit.icon}</div>
            <h3 class="text-lg font-semibold text-primary mb-[theme(--spacing-md)]">{benefit.title}</h3>
            <div class="text-foreground dark:text-foreground-secondary text-sm">
              {#each benefit.descriptions as description}
                <p class="mb-[theme(--spacing-sm)]">{description}</p>
              {/each}
            </div>
          </Card>
        {/each}
      </div>

      <div class="text-center mt-[theme(--spacing-2xl)]">
        <Button onclick={navigateToBusinessForm} class="uppercase tracking-wider gap-2">
          <span>Get Started for Free</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="hover:translate-x-1 transition-transform"
            ><line x1="5" y1="12" x2="19" y2="12"></line><polyline
              points="12 5 19 12 12 19"
            ></polyline></svg
          >
        </Button>
      </div>
    </Card>

    <!-- Social Proof Section -->
    <Card class="bg-accent-muted p-[theme(--card-padding-y)] mb-[theme(--spacing-2xl)]">
      <div class="text-center mb-[theme(--spacing-2xl)]">
        <h2 class="text-2xl md:text-4xl font-semibold text-primary mb-[theme(--spacing-lg)]">Join the Solar Installer Community</h2>
        <div class="flex justify-center items-center my-[theme(--spacing-lg)]">
          <span class="w-20 h-1 bg-accent rounded"></span>
        </div>
      </div>

      <div class="flex justify-center flex-wrap gap-[theme(--spacing-2xl)] mb-[theme(--spacing-2xl)]">
        {#each stats as stat}
          <Card class="w-48 text-center p-[theme(--spacing-lg)]">
            <div class="text-4xl font-bold text-primary mb-[theme(--spacing-sm)]">{stat.number}</div>
            <div class="text-lg font-semibold text-foreground dark:text-foreground-secondary">{stat.label}</div>
          </Card>
        {/each}
      </div>

      <div class="text-center mt-[theme(--spacing-2xl)]">
        <Button onclick={navigateToBusinessForm} class="uppercase tracking-wider gap-2">
          <span>List My Business</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="hover:translate-x-1 transition-transform"
            ><line x1="5" y1="12" x2="19" y2="12"></line><polyline
              points="12 5 19 12 12 19"
            ></polyline></svg
          >
        </Button>
      </div>
    </Card>

    <!-- Recently Joined Verified Installers -->
    <Card class="p-[theme(--card-padding-y)] mb-[theme(--spacing-2xl)] bg-[hsl(var(--accent)/0.1)]">
      <div class="text-center mb-[theme(--spacing-2xl)]">
        <h2 class="text-2xl md:text-4xl font-semibold text-primary mb-[theme(--spacing-lg)]">Recently Joined Verified Installers</h2>
        <div class="flex justify-center items-center my-[theme(--spacing-lg)]">
          <span class="w-20 h-1 bg-accent rounded"></span>
        </div>
        <p class="text-lg text-foreground dark:text-foreground-secondary max-w-2xl mx-auto">
          These solar professionals recently joined our growing community
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[theme(--card-gap)] mb-[theme(--spacing-2xl)]">
        {#if data && data.businesses && data.businesses.length > 0}
          {#each data.businesses as business}
            <a
              href={`/solar-panel-installer/${business.slug}`}
              target="_blank"
              rel="noopener noreferrer"
              class="no-underline text-inherit block transition-transform duration-[theme(--transition-default)]"
            >
              <Card class="relative h-full flex flex-col overflow-hidden p-[theme(--spacing-lg)]">
                <div class="absolute flex items-center text-primary-foreground text-xs font-semibold bg-success top-[theme(--spacing-xs)] right-[theme(--spacing-xs)] gap-[theme(--spacing-xs)] px-[theme(--spacing-sm)] py-[theme(--spacing-xs)] rounded-full">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="18"
                    height="18"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    ><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"
                    ></path><polyline points="22 4 12 14.01 9 11.01"
                    ></polyline></svg
                  >
                  <span>Verified</span>
                </div>
                <h3 class="text-lg font-semibold text-primary pr-[theme(--spacing-2xl)]">{business.businessname}</h3>
                <div class="flex flex-col mt-auto gap-[theme(--spacing-sm)]">
                  <div class="flex items-center text-foreground dark:text-foreground-secondary text-sm gap-[theme(--spacing-sm)]">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      ><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"
                      ></path><circle cx="12" cy="10" r="3"></circle></svg
                    >
                    <span>{business.city}, {business.state}</span>
                  </div>
                  <div class="flex items-center text-foreground dark:text-foreground-secondary text-sm gap-[theme(--spacing-sm)]">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      ><path
                        d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"
                      ></path></svg
                    >
                    <span>{business.phonenumber}</span>
                  </div>
                </div>
              </Card>
            </a>
          {/each}
        {:else}
          <div class="col-span-full text-center py-12">
            <p class="text-foreground dark:text-foreground-secondary">
              No verified installers available at the moment. Be the first to
              join!
            </p>
          </div>
        {/if}
      </div>

      <div class="text-center mt-[theme(--spacing-2xl)]">
        <Button onclick={navigateToBusinessForm} class="uppercase tracking-wider gap-2">
          <span>Join These Businesses</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            ><line x1="5" y1="12" x2="19" y2="12"></line><polyline
              points="12 5 19 12 12 19"
            ></polyline></svg
          >
        </Button>
      </div>
    </Card>

    <!-- How It Works Video Section -->
    <Card class="text-center p-[theme(--card-padding-y)] mb-[theme(--spacing-2xl)]" id="product-working">
      <div class="text-center mb-[theme(--spacing-2xl)]">
        <h2 class="text-2xl md:text-4xl font-semibold text-primary mb-[theme(--spacing-lg)]">See How It Works</h2>
        <div class="flex justify-center items-center my-[theme(--spacing-lg)]">
          <span class="w-20 h-1 bg-accent rounded"></span>
        </div>
        <p class="text-lg text-foreground dark:text-foreground-secondary max-w-2xl mx-auto">
          Watch this quick video to understand how Solar Vipani connects you
          with customers
        </p>
      </div>

      <div class="relative mx-auto max-w-2xl overflow-hidden rounded-[theme(--radius-lg)] shadow-[theme(--shadow-lg)]">
        <iframe
          src="https://www.youtube.com/embed/8UZ-4XN8Vq8"
          title="How Solarvipani.com works"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          referrerpolicy="strict-origin-when-cross-origin"
          allowfullscreen
          loading="lazy"
        >
        </iframe>
      </div>

      <div class="text-center mt-[theme(--spacing-2xl)]">
        <Button onclick={navigateToBusinessForm} class="uppercase tracking-wider gap-2">
          <span>Try It Now — Free</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            ><line x1="5" y1="12" x2="19" y2="12"></line><polyline
              points="12 5 19 12 12 19"
            ></polyline></svg
          >
        </Button>
      </div>
    </Card>

    <!-- FAQs Section -->
    <Card class="p-[theme(--card-padding-y)] mb-[theme(--spacing-2xl)]">
      <div class="text-center mb-[theme(--spacing-2xl)]">
        <h2 class="text-2xl md:text-4xl font-semibold text-primary mb-[theme(--spacing-lg)]">Frequently Asked Questions</h2>
        <div class="flex justify-center items-center my-[theme(--spacing-lg)]">
          <span class="w-20 h-1 bg-accent rounded"></span>
        </div>
      </div>

      <div class="flex flex-col items-center gap-[theme(--card-gap)] max-w-2xl mx-auto">
        {#each faqs as faq}
          <Card class="p-[theme(--spacing-lg)] w-full">
            <h3 class="text-lg font-semibold text-primary mb-[theme(--spacing-md)]">{faq.question}</h3>
            <p class="text-foreground dark:text-foreground-secondary text-sm">{faq.answer}</p>
          </Card>
        {/each}
      </div>
    </Card>

    <!-- Need Assistance Section -->
    <Card class="p-[theme(--card-padding-y)] mb-[theme(--spacing-2xl)]">
      <div class="text-center mb-[theme(--spacing-2xl)]">
        <h2 class="text-2xl md:text-4xl font-semibold mb-[theme(--spacing-lg)] text-primary">We're Here to Help</h2>
        <div class="flex justify-center items-center my-[theme(--spacing-lg)]">
          <span class="w-20 h-1 bg-accent rounded"></span>
        </div>
      </div>

      <div class="flex justify-center gap-[theme(--spacing-2xl)] flex-wrap">
        <Card class="p-[theme(--spacing-lg)] text-center w-64">
          <div class="text-primary mb-4 flex justify-center">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              ><path
                d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"
              ></path><polyline points="22,6 12,13 2,6"></polyline></svg
            >
          </div>
          <p class="mb-2 text-foreground dark:text-foreground-secondary">Email us at</p>
          <a
            href="mailto:admin@solarvipani.com"
            class="block text-lg font-semibold text-primary hover:underline transition-colors"
            rel="noopener">admin@solarvipani.com</a
          >
        </Card>

        <Card class="p-[theme(--spacing-lg)] text-center w-64">
          <div class="text-primary mb-4 flex justify-center">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              ><path
                d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"
              ></path></svg
            >
          </div>
          <p class="mb-2 text-foreground dark:text-foreground-secondary">Call us at</p>
          <a href="tel:+918983066701" class="block text-lg font-semibold text-primary hover:underline transition-colors" rel="noopener"
            >+91 8983066701</a
          >
        </Card>
      </div>
    </Card>

    <!-- About Solarvipani Section -->

    <AboutSolarVipani />
  </div>
</main>

<style>
  /* Pulse animation for CTA buttons */
  @keyframes pulse {
    0% {
      box-shadow: 0 0 0 0 hsl(var(--primary) / 0.7);
    }
    70% {
      box-shadow: 0 0 0 10px hsl(var(--primary) / 0);
    }
    100% {
      box-shadow: 0 0 0 0 hsl(var(--primary) / 0);
    }
  }

  :global(.pulse) {
    animation: pulse 2s infinite;
  }

  /* iframe styling */
  :global(iframe) {
    width: 100%;
    height: 400px;
    display: block;
    border: none;
  }

  @media (max-width: 768px) {
    :global(iframe) {
      height: 300px;
    }
  }

  @media (max-width: 576px) {
    :global(iframe) {
      height: 220px;
    }
  }
</style>

// apps/main-app-nextjs/app/[country]/business-listing/page.tsx
/**
 * `/{cc}/business-listing` — the free-listing pitch. 2 pages (IN and US).
 * Ported from
 * apps/main-app/src/routes/[country=country]/(layout-1)/business-listing/+page.svelte
 * and its loader.
 *
 * **A real page in both countries**, unlike `/{cc}/partners` next to it, which
 * `middleware.ts` 301s for US — and `/us/partners` 301s *here*, which makes
 * this the US installer-acquisition page. So the country fork is the whole
 * shape of the file: SvelteKit's page merged two pages that had drifted apart
 * and kept each country's live copy rather than unifying it, and that merge is
 * carried across as-is. The forked parts are `COPY` below; everything outside
 * it is shared because it was already identical.
 *
 * Kept from the SvelteKit merge, with its reasoning:
 *
 *  - **five of six benefits share a title, two differ in wording**, so it is a
 *    whole-array fork rather than a per-item gate.
 *  - **the US FAQ set is not a rewrite of the IN one.** The IN "What is Solar
 *    Vipani?" answer is India-specific and the US page never had that question,
 *    so US gets its own third entry.
 *  - **the closing CTA card is US-only; the video is IN-only.** Each country's
 *    live page, not a union of the two.
 *
 * Fixed here rather than carried across — the SvelteKit page's own comment
 * flags it and then ships it anyway: **the FAQPage JSON-LD was the US set for
 * both countries**. It is built from the array the page renders now, so the
 * markup cannot claim questions the reader is not shown. Same rule the
 * editorial and directory surfaces already follow.
 *
 * Two other changes from the original:
 *
 *  - **the "500+ businesses / 5,000+ cities" band is counted live.** Those two
 *    figures were never true — /about-us's header records 470 and 356 against
 *    them — and this page is asking an installer to trust the platform with
 *    their listing. `getPlatformStats` is the same source /about-us prints.
 *  - **`youtube-nocookie.com`, not `youtube.com`.** Same video, no profiling
 *    cookie on view.
 *
 * The Meta Pixel is not ported. See `business-form/page.tsx`.
 */
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Image from 'next/image';
import {
  ArrowRight,
  Award,
  Building2,
  CheckCircle2,
  Compass,
  Images,
  Mail,
  MapPin,
  Pencil,
  Phone,
  UserCheck
} from 'lucide-react';
import { Container, PageShell, Section, Stack } from '@/components/layout';
import { Breadcrumb, FAQ, type FaqEntry } from '@/components/directory';
import { getCountry, isCountry, type CountryCode } from '@/lib/countries';
import { listRecentBusinesses } from '@/lib/directory/data';
import { BASE_URL, breadcrumbLD, faqLD } from '@/lib/directory/structuredData';
import { installerUrl } from '@/lib/directory/urls';
import { OG_IMAGE, pageMetadata } from '@/lib/metadata';
import { getPlatformStats } from '@/lib/stats';

/** 15 days, matching the SvelteKit page's `config.isr.expiration`. */
export const revalidate = 1296000;

/** Empty on purpose — see "ISR needs `generateStaticParams` too" in the README. */
export async function generateStaticParams() {
  return [];
}

type Benefit = { icon: typeof Compass; title: string; body: string[] };

/** The three benefits both countries have carried since before the merge. */
const SHARED_BENEFITS: Benefit[] = [
  {
    icon: Compass,
    title: 'Get Discovered Online',
    body: [
      'Customers search for queries like "solar panel installers near me" and "top solar panel installer in [city]".',
      'We rank on the first page of Google, Yahoo, ChatGPT and more for those queries.'
    ]
  },
  {
    icon: Mail,
    title: 'Direct Customer Inquiries',
    body: [
      'We display your business phone number, WhatsApp, email and address.',
      'That lets customers reach out to you directly.'
    ]
  },
  {
    icon: Images,
    title: 'Post Recent Projects',
    body: ['Showcase your workmanship to potential customers.']
  }
];

const CREDIBILITY_BENEFIT: Benefit = {
  icon: Award,
  title: 'Strengthen Credibility',
  body: ['Get a verified business tag that boosts client confidence.']
};

const COST_FAQ: FaqEntry = {
  question: 'How much does it cost to list my business?',
  answer:
    'Listing your business is completely free of charge. We believe in providing value first and helping solar businesses grow their online presence without any upfront costs.'
};

const EXISTING_CUSTOMERS_FAQ: FaqEntry = {
  question: "Why should I list my business if I'm already getting customers?",
  answer:
    "Even if you have a steady customer base, listing on Solar Vipani significantly increases your online visibility, helping you reach even more potential customers who are actively searching for solar installation services. It's an additional channel that complements your existing marketing efforts."
};

/**
 * Everything that differs by country, in one object so the fork is visible in
 * one place rather than as six `cc === 'us'` ternaries down the page.
 *
 * `description` and `orgDescription` are each verbatim from the page that
 * country was served by before the merge.
 */
const COPY: Record<
  CountryCode,
  {
    subhead: string;
    lede: string | null;
    heroCta: boolean;
    finalCta: boolean;
    video: boolean;
    socialProof: boolean;
    description: string;
    orgDescription: string;
    languages: string[];
    benefits: Benefit[];
    faqs: FaqEntry[];
  }
> = {
  in: {
    subhead: 'Get discovered by customers researching online',
    // The IN hero has never had a lede or a hero CTA; the US one led with both.
    lede: null,
    heroCta: false,
    finalCta: false,
    video: true,
    socialProof: true,
    description:
      'Expand your solar business reach by listing on Solar Vipani. Connect with customers actively seeking solar installation services in your area.',
    orgDescription:
      "India's leading solar panel installer directory connecting customers with verified solar installation services",
    // Hindi is an India-only support language; every country serves English.
    languages: ['English', 'Hindi'],
    benefits: [
      ...SHARED_BENEFITS,
      {
        icon: UserCheck,
        title: 'Enhance Online Presence',
        body: [
          'Get a dedicated page on a website that ranks highly in the solar installation domain.'
        ]
      },
      CREDIBILITY_BENEFIT,
      {
        icon: Building2,
        title: 'Manage Multiple Branch Offices',
        body: [
          'Expand your reach by managing multiple branch locations under one main business profile.'
        ]
      }
    ],
    faqs: [
      {
        question: 'What is Solar Vipani?',
        answer:
          "Solar Vipani is India's leading platform connecting customers actively seeking solar installation with verified solar installers. We help grow your business by giving you direct access to qualified leads in your area."
      },
      COST_FAQ,
      EXISTING_CUSTOMERS_FAQ
    ]
  },
  us: {
    subhead: 'Get discovered on Google and ChatGPT',
    lede: 'Connect directly with customers seeking solar installation services in your area.',
    heroCta: true,
    finalCta: true,
    video: false,
    socialProof: false,
    description:
      'Expand your solar business reach by listing on Solar Vipani USA. Connect with customers actively seeking solar installation services in your area across the United States.',
    orgDescription:
      "America's leading solar panel installer directory connecting customers with verified solar installation services",
    languages: ['English'],
    benefits: [
      ...SHARED_BENEFITS,
      {
        icon: UserCheck,
        title: 'Enhance Online Presence',
        body: ['We provide a dedicated business profile page.']
      },
      CREDIBILITY_BENEFIT,
      {
        icon: Pencil,
        title: 'Manage Your Information',
        body: [
          'Keep your business details up to date so customers always have the latest information.'
        ]
      }
    ],
    faqs: [
      COST_FAQ,
      {
        question: 'How do you earn money if the business listing is free?',
        answer:
          'We provide premium marketing services to select businesses where we see growth potential. These paid services include targeted campaigns on platforms like Facebook, Instagram, Google Search and YouTube to further boost your visibility.'
      },
      EXISTING_CUSTOMERS_FAQ
    ]
  }
};

export async function generateMetadata({
  params
}: {
  params: Promise<{ country: string }>;
}): Promise<Metadata> {
  const { country } = await params;
  if (!isCountry(country)) return {};
  const config = getCountry(country);

  return pageMetadata({
    title: 'List Your Solar Business',
    description: COPY[country].description,
    path: `/${country}/business-listing`,
    locale: config.locale,
    imageAlt: `List your solar business on ${config.brandName}`
  });
}

/** The CTA every section on this page ends with. */
function ListButton({ country, label }: { country: string; label: string }) {
  return (
    <div>
      <a
        href={`/${country}/business-form`}
        className="inline-flex items-center gap-xs rounded-md bg-action px-lg py-sm text-base font-semibold text-action-ink no-underline transition-colors duration-fast ease-standard hover:bg-action-hover"
      >
        {label}
        <ArrowRight aria-hidden className="size-4" />
      </a>
    </div>
  );
}

export default async function Page({ params }: { params: Promise<{ country: string }> }) {
  const { country } = await params;
  if (!isCountry(country)) notFound();
  const config = getCountry(country);
  const copy = COPY[country];

  const [stats, businesses] = await Promise.all([
    getPlatformStats(),
    listRecentBusinesses(country)
  ]);

  const trail = [{ name: 'Home', href: `/${country}` }, { name: 'Business listing' }];

  const hero = (
    <section className="relative isolate flex min-h-[20rem] items-center overflow-hidden py-2xl">
      {/* Decorative — the copy on top carries the meaning. */}
      <Image
        src="/header/header.avif"
        alt=""
        width={1920}
        height={600}
        priority
        className="absolute inset-0 -z-10 size-full object-cover object-center"
      />
      <div className="absolute inset-0 -z-10 bg-black/55" />
      <Container>
        <Stack gap="lg">
          <div className="max-w-prose">
            <h1 className="text-3xl leading-tight text-white">Grow Your Solar Business</h1>
            {/* A <p>, not the original's <h2>: a subtitle as a heading puts a
                phantom entry in the outline above the page's real sections. */}
            <p className="mt-md text-lg text-white">{copy.subhead}</p>
            {copy.lede ? <p className="mt-sm text-white">{copy.lede}</p> : null}
          </div>
          {copy.heroCta ? <ListButton country={country} label="List my business now" /> : null}
        </Stack>
      </Container>
    </section>
  );

  return (
    <PageShell hero={hero}>
      <Section>
        <Stack gap="lg">
          <Breadcrumb trail={trail} />
          <div className="max-w-prose">
            <h2 className="text-xl text-ink">
              Why list your business with {config.brandName}?
            </h2>
            <p className="mt-sm text-ink-muted">
              Get discovered by customers ready to install solar panels — completely free.
            </p>
          </div>
          <div className="grid grid-cols-1 gap-md md:grid-cols-3">
            {copy.benefits.map((benefit) => (
              <div key={benefit.title} className="rounded-lg border border-line bg-surface p-md">
                {/* Decoration: the title carries the meaning. */}
                <benefit.icon aria-hidden className="size-6 text-ink-subtle" />
                <h3 className="mt-sm text-base leading-snug text-ink">{benefit.title}</h3>
                {benefit.body.map((line) => (
                  <p key={line} className="mt-2xs text-sm text-ink-muted">
                    {line}
                  </p>
                ))}
              </div>
            ))}
          </div>
          <ListButton country={country} label="Get started for free" />
        </Stack>
      </Section>

      {copy.socialProof ? (
        <Section>
          <Stack gap="lg">
            <h2 className="text-xl text-ink">Join the solar installer community</h2>
            {/* Counted live. The live page's "500+" and "5,000+" were never
                true — see this file's header. */}
            <div className="grid grid-cols-2 gap-md sm:grid-cols-3">
              {[
                { value: stats.installerCount, label: 'Businesses listed' },
                { value: stats.citiesServed, label: 'Cities and towns' },
                { value: stats.projectsCompleted, label: 'Projects published' }
              ].map((figure) => (
                <div
                  key={figure.label}
                  className="rounded-lg border border-line bg-brand-surface p-md text-center"
                >
                  <div className="text-2xl font-bold tabular-nums text-ink">
                    {figure.value.toLocaleString(config.locale)}
                  </div>
                  <div className="mt-2xs text-sm text-ink-muted">{figure.label}</div>
                </div>
              ))}
            </div>
            <ListButton country={country} label="List my business" />
          </Stack>
        </Section>
      ) : null}

      <Section>
        <Stack gap="lg">
          <div className="max-w-prose">
            <h2 className="text-xl text-ink">Recently joined verified installers</h2>
            <p className="mt-sm text-ink-muted">
              These solar professionals recently joined the directory.
            </p>
          </div>
          {businesses.length > 0 ? (
            <ul className="grid list-none grid-cols-1 gap-md md:grid-cols-2 lg:grid-cols-3">
              {businesses.map((business) => (
                <li key={business.slug}>
                  {/* The whole card is the anchor, and it stays in-tab — an
                      installer profile is this site, so a forced new window
                      would override the reader's own navigation. */}
                  <a
                    href={installerUrl(country, business.slug)}
                    className="flex h-full flex-col rounded-lg border border-line bg-surface p-md text-ink no-underline transition-shadow duration-fast ease-standard hover:shadow-raised"
                  >
                    <div className="flex items-start justify-between gap-sm">
                      <h3 className="text-base leading-snug text-action underline decoration-action/40 underline-offset-2">
                        {business.name}
                      </h3>
                      <span className="inline-flex shrink-0 items-center gap-2xs rounded-full bg-success-surface px-xs py-2xs text-xs font-semibold text-ink">
                        <CheckCircle2 aria-hidden className="size-3.5 text-success" />
                        Verified
                      </span>
                    </div>
                    <div className="mt-sm flex flex-col gap-2xs text-sm text-ink-muted">
                      {business.city ? (
                        <span className="flex items-center gap-xs">
                          <MapPin aria-hidden className="size-4 shrink-0 text-ink-subtle" />
                          {[business.city, business.state].filter(Boolean).join(', ')}
                        </span>
                      ) : null}
                      {business.phone ? (
                        <span className="flex items-center gap-xs">
                          <Phone aria-hidden className="size-4 shrink-0 text-ink-subtle" />
                          {business.phone}
                        </span>
                      ) : null}
                    </div>
                  </a>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-ink-muted">
              No verified installers to show yet. Be the first to join.
            </p>
          )}
          <ListButton country={country} label="Join these businesses" />
        </Stack>
      </Section>

      {copy.video ? (
        <Section id="product-working" width="narrow">
          <Stack gap="lg">
            <div className="max-w-prose">
              <h2 className="text-xl text-ink">See how it works</h2>
              <p className="mt-sm text-ink-muted">
                A short video on how Solar Vipani connects you with customers.
              </p>
            </div>
            {/* youtube-nocookie, not youtube.com — see this file's header. */}
            <div className="overflow-hidden rounded-lg border border-line">
              <iframe
                className="aspect-video w-full border-0"
                src="https://www.youtube-nocookie.com/embed/8UZ-4XN8Vq8"
                title="How Solar Vipani works"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerPolicy="strict-origin-when-cross-origin"
                allowFullScreen
                loading="lazy"
              />
            </div>
            <ListButton country={country} label="Try it now — free" />
          </Stack>
        </Section>
      ) : null}

      <Section width="narrow">
        <FAQ items={copy.faqs} heading="Frequently asked questions" />
      </Section>

      {copy.finalCta ? (
        <Section width="narrow">
          <div className="rounded-lg bg-accent-surface p-xl">
            <Stack gap="lg">
              <div className="max-w-prose">
                <h2 className="text-xl text-ink">Ready to grow your solar business?</h2>
                <p className="mt-sm text-ink-muted">
                  Join the solar installation companies already listed on {config.brandName}.
                </p>
              </div>
              <ListButton country={country} label="List my business now" />
            </Stack>
          </div>
        </Section>
      ) : null}

      <Section width="narrow">
        <Stack gap="lg">
          <h2 className="text-xl text-ink">We&rsquo;re here to help</h2>
          <div className="grid grid-cols-1 gap-md sm:grid-cols-2">
            <div className="rounded-lg border border-line bg-surface p-md">
              <Mail aria-hidden className="size-5 text-ink-subtle" />
              <p className="mt-sm text-sm text-ink-muted">Email us at</p>
              <a href="mailto:admin@solarvipani.com">admin@solarvipani.com</a>
            </div>
            <div className="rounded-lg border border-line bg-surface p-md">
              <Phone aria-hidden className="size-5 text-ink-subtle" />
              <p className="mt-sm text-sm text-ink-muted">Call us at</p>
              <a href="tel:+918983066701">+91 8983066701</a>
            </div>
          </div>
        </Stack>
      </Section>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify([
            breadcrumbLD(trail),
            {
              '@context': 'https://schema.org',
              '@type': 'Organization',
              name: config.brandName,
              url: BASE_URL,
              logo: OG_IMAGE.url,
              description: copy.orgDescription,
              contactPoint: {
                '@type': 'ContactPoint',
                telephone: '+91-8983066701',
                contactType: 'customer service',
                email: 'admin@solarvipani.com',
                availableLanguage: copy.languages
              },
              address: { '@type': 'PostalAddress', addressCountry: country.toUpperCase() }
            },
            {
              '@context': 'https://schema.org',
              '@type': 'Service',
              name: 'Solar Business Directory Listing',
              description:
                'Free business listing service for solar panel installers and solar energy companies',
              provider: { '@type': 'Organization', name: config.brandName, url: BASE_URL },
              serviceType: 'Business Directory',
              areaServed: { '@type': 'Country', name: config.name },
              offers: {
                '@type': 'Offer',
                price: '0',
                priceCurrency: config.currency,
                description: 'Free business listing for solar installers'
              }
            },
            // Built from the array the page renders. The SvelteKit version
            // shipped the US question set on both countries.
            faqLD(copy.faqs)
          ])
        }}
      />
    </PageShell>
  );
}
