// apps/main-app/src/routes/(layout-1)/tools/subsidy-checker/+page.svelte
<script lang="ts">
	import { contentUrl, countryUrl, geoUrl } from '$lib/countries/urls';
	import { Label } from '$lib/components/ui/label';
	import { Slider } from '$lib/components/ui/slider';
	import * as Select from '$lib/components/ui/select';
	import { breadcrumbLD, webAppLD } from '$lib/seo';
	import Breadcrumb from '$lib/in/components/seo/Breadcrumb.svelte';
	import FAQ from '$lib/in/components/seo/FAQ.svelte';
	import { CheckCircle, XCircle, ArrowRight, Info } from '@lucide/svelte';
	import { capture } from '$lib/posthog';

	let { data } = $props();

	const BASE_URL = 'https://solarvipani.com';

	const breadcrumb = breadcrumbLD([
		{ name: 'Home', url: `${BASE_URL}/in/` },
		{ name: 'Tools', url: `${BASE_URL}/tools/` },
		{ name: 'Subsidy Checker', url: `${BASE_URL}/tools/subsidy-checker/` }
	]);

	const webApp = webAppLD({
		name: 'Solar Subsidy Checker',
		description:
			'Check PM Surya Ghar Yojana central solar subsidy for your system size. See subsidy amounts, eligibility, and savings.',
		url: `${BASE_URL}/tools/subsidy-checker/`
	});

	const faqs = [
		{
			question: 'Who is eligible for the PM Surya Ghar solar subsidy?',
			answer:
				'Residential consumers with a valid grid connection are eligible for the PM Surya Ghar subsidy. The system must be on-grid (grid-connected) and installed by a registered vendor. Commercial and industrial connections are not eligible for central subsidies.'
		},
		{
			question: 'What are the PM Surya Ghar subsidy rates?',
			answer:
				'The central subsidy is Rs 30,000 per kW for the first 2 kW and Rs 18,000 per kW for capacity between 2-3 kW. Maximum central subsidy is Rs 78,000 for 3 kW and above systems.'
		},
		{
			question: 'Can I get both central and state subsidies?',
			answer:
				'Yes, in many states you can avail both central subsidy (PM Surya Ghar) and state-specific top-up subsidies. The state subsidy amount varies by state and may have additional eligibility conditions.'
		},
		{
			question: 'Are off-grid systems eligible for subsidies?',
			answer:
				'Off-grid and hybrid systems are generally not eligible for the PM Surya Ghar central subsidy. Some states may offer separate subsidies for off-grid systems, but these are less common.'
		}
	];

	const faqLdJson = {
		'@context': 'https://schema.org',
		'@type': 'FAQPage',
		mainEntity: faqs.map((f) => ({
			'@type': 'Question',
			name: f.question,
			acceptedAnswer: { '@type': 'Answer', text: f.answer }
		}))
	};

	// Form state
	let selectedState = $state('');
	let selectedDistrict = $state('');
	let systemSizeKw = $state(3);
	let connectionType = $state('residential');
	let gridConnection = $state('yes');
	let hasChecked = $state(false);

	const states = $derived(
		[...new Set(data.districts.map((d: { state: string }) => d.state))].sort() as string[]
	);

	const filteredDistricts = $derived(
		selectedState
			? data.districts.filter((d: { state: string }) => d.state === selectedState)
			: []
	);

	const selectedDistrictData = $derived(
		data.districts.find(
			(d: { district: string; state: string }) =>
				d.state === selectedState && d.district === selectedDistrict
		)
	);

	// Central subsidy calculation (PM Surya Ghar slabs)
	const centralSubsidy = $derived.by(() => {
		if (connectionType !== 'residential' || gridConnection !== 'yes') return 0;
		const kw = systemSizeKw;
		if (kw <= 2) return Math.round(kw * 30000);
		if (kw <= 3) return 60000 + Math.round((kw - 2) * 18000);
		return 78000; // max for 3+ kW
	});

	const isEligibleCentral = $derived(
		connectionType === 'residential' && gridConnection === 'yes'
	);

	const eligibilityReasons = $derived.by(() => {
		const reasons: string[] = [];
		if (connectionType !== 'residential')
			reasons.push('Central subsidy is only for residential connections.');
		if (gridConnection !== 'yes')
			reasons.push('Central subsidy requires a grid-connected (on-grid) system.');
		return reasons;
	});

	const estimatedCost = $derived(
		Math.round(systemSizeKw * (systemSizeKw <= 3 ? 55000 : systemSizeKw <= 5 ? 50000 : 45000))
	);
	const netCost = $derived(estimatedCost - centralSubsidy);

	function handleCheck() {
		hasChecked = true;
		capture('subsidy_checked', {
			system_size_kw: systemSizeKw,
			eligible: isEligibleCentral,
			subsidy_amount: centralSubsidy,
			net_cost: netCost,
			state: selectedState
		});
	}

	function formatCurrency(n: number): string {
		if (n >= 100000) return `Rs ${(n / 100000).toFixed(1)} Lakh`;
		return `Rs ${n.toLocaleString('en-IN')}`;
	}
</script>

<svelte:head>
	<title>Solar Subsidy Checker — PM Surya Ghar Yojana Subsidy Calculator | Solar Vipani</title>
	<meta
		name="description"
		content="Check PM Surya Ghar Yojana central solar subsidy for your system size. See subsidy amounts, eligibility, and net cost after subsidy. Free subsidy calculator."
	/>
	<link rel="canonical" href="{BASE_URL}/tools/subsidy-checker/" />
	{@html `<script type="application/ld+json">${JSON.stringify(breadcrumb)}<\u002Fscript>`}
	{@html `<script type="application/ld+json">${JSON.stringify(webApp)}<\u002Fscript>`}
	{@html `<script type="application/ld+json">${JSON.stringify(faqLdJson)}<\u002Fscript>`}
</svelte:head>

<div class="max-w-4xl mx-auto px-4 py-8">
	<Breadcrumb
		items={[
			{ name: 'Home', href: countryUrl('in', '/') },
			{ name: 'Tools', href: contentUrl('/tools/') },
			{ name: 'Subsidy Checker', href: contentUrl('/tools/subsidy-checker/') }
		]}
	/>

	<h1 class="text-3xl md:text-4xl font-bold text-primary mb-4">Solar Subsidy Checker</h1>
	<p class="text-muted-foreground mb-8 max-w-2xl">
		Check your eligibility and subsidy amount under the PM Surya Ghar Yojana — the Government of
		India's national rooftop solar subsidy scheme.
	</p>

	<!-- Calculator Form -->
	<div class="rounded-lg border bg-card p-6 shadow-[theme(--shadow-xs)] mb-8">
		<h2 class="text-lg font-semibold text-primary mb-4">Check Your Subsidy Eligibility</h2>
		<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
			<!-- State -->
			<div class="flex flex-col gap-2">
				<Label for="state">State</Label>
				<Select.Root type="single" bind:value={selectedState} onValueChange={() => { selectedDistrict = ''; }}>
					<Select.Trigger class="w-full">
						{selectedState || 'Select state'}
					</Select.Trigger>
					<Select.Content class="max-h-60">
						{#each states as state}
							<Select.Item value={state}>{state}</Select.Item>
						{/each}
					</Select.Content>
				</Select.Root>
			</div>

			<!-- District -->
			<div class="flex flex-col gap-2">
				<Label for="district">District</Label>
				<Select.Root type="single" bind:value={selectedDistrict} disabled={!selectedState}>
					<Select.Trigger class="w-full">
						{selectedDistrict || 'Select district'}
					</Select.Trigger>
					<Select.Content class="max-h-60">
						{#each filteredDistricts as d}
							<Select.Item value={d.district}>{d.district}</Select.Item>
						{/each}
					</Select.Content>
				</Select.Root>
			</div>

			<!-- Connection Type -->
			<div class="flex flex-col gap-2">
				<Label for="connection">Connection Type</Label>
				<Select.Root type="single" bind:value={connectionType}>
					<Select.Trigger class="w-full">
						{connectionType === 'residential'
							? 'Residential'
							: connectionType === 'commercial'
								? 'Commercial'
								: 'Institutional'}
					</Select.Trigger>
					<Select.Content>
						<Select.Item value="residential">Residential</Select.Item>
						<Select.Item value="commercial">Commercial</Select.Item>
						<Select.Item value="institutional">Institutional</Select.Item>
					</Select.Content>
				</Select.Root>
			</div>

			<!-- Grid Connection -->
			<div class="flex flex-col gap-2">
				<Label for="grid">Grid Connection</Label>
				<Select.Root type="single" bind:value={gridConnection}>
					<Select.Trigger class="w-full">
						{gridConnection === 'yes' ? 'Yes (On-Grid)' : 'No (Off-Grid)'}
					</Select.Trigger>
					<Select.Content>
						<Select.Item value="yes">Yes (On-Grid)</Select.Item>
						<Select.Item value="no">No (Off-Grid)</Select.Item>
					</Select.Content>
				</Select.Root>
			</div>

			<!-- System Size -->
			<div class="flex flex-col gap-2 md:col-span-2">
				<div class="flex justify-between items-baseline">
					<Label for="size">System Size</Label>
					<span class="text-primary text-lg font-semibold">{systemSizeKw} kW</span>
				</div>
				<Slider
					id="size"
					min={[1]}
					max={[10]}
					step={[0.5]}
					bind:value={systemSizeKw}
					class="w-full"
				/>
				<div class="text-muted-foreground text-xs">1 kW – 10 kW</div>
			</div>
		</div>

		<button
			onclick={handleCheck}
			class="mt-6 w-full bg-primary text-primary-foreground font-semibold py-3 rounded-lg hover:opacity-90 transition-opacity"
		>
			Check Subsidy
		</button>
	</div>

	<!-- Results -->
	{#if hasChecked}
		<div class="rounded-lg border bg-card p-6 shadow-[theme(--shadow-xs)] mb-8">
			<h2 class="text-2xl font-semibold text-primary mb-6">Subsidy Details</h2>

			<!-- Eligibility Status -->
			<div
				class="flex items-start gap-3 rounded-lg border p-4 mb-6 {isEligibleCentral
					? 'border-green-600/30 bg-green-600/10'
					: 'border-red-600/30 bg-red-600/10'}"
			>
				{#if isEligibleCentral}
					<CheckCircle class="w-5 h-5 text-primary shrink-0 mt-0.5" />
					<div>
						<p class="font-semibold text-foreground">
							Eligible for PM Surya Ghar Subsidy
						</p>
						<p class="text-sm text-muted-foreground">
							Your system qualifies for the central government subsidy.
						</p>
					</div>
				{:else}
					<XCircle class="w-5 h-5 text-destructive shrink-0 mt-0.5" />
					<div>
						<p class="font-semibold text-foreground">
							Not Eligible for Central Subsidy
						</p>
						{#each eligibilityReasons as reason}
							<p class="text-sm text-muted-foreground">{reason}</p>
						{/each}
					</div>
				{/if}
			</div>

			<!-- Subsidy Breakdown -->
			<div class="space-y-3">
				<div class="flex justify-between text-sm">
					<span class="text-muted-foreground">System Size</span>
					<span class="font-medium">{systemSizeKw} kW</span>
				</div>
				<div class="flex justify-between text-sm">
					<span class="text-muted-foreground">Estimated System Cost</span>
					<span class="font-medium">{formatCurrency(estimatedCost)}</span>
				</div>
				<div class="flex justify-between text-sm border-t pt-2">
					<span class="text-muted-foreground">Central Subsidy (PM Surya Ghar)</span>
					<span class="font-medium {centralSubsidy > 0 ? 'text-green-600' : ''}">
						{centralSubsidy > 0
							? `- ${formatCurrency(centralSubsidy)}`
							: 'Not applicable'}
					</span>
				</div>
				<div class="flex justify-between text-sm border-t pt-2">
					<span class="font-semibold">Net Cost (after subsidy)</span>
					<span class="font-bold text-primary">{formatCurrency(netCost)}</span>
				</div>
			</div>

			<!-- PM Surya Ghar Yojana Info -->
			<div class="mt-6 rounded-lg border p-4">
				<h3 class="font-semibold text-primary mb-2">PM Surya Ghar Yojana — Subsidy Slabs</h3>
				<p class="text-sm text-muted-foreground mb-3">
					Central government scheme providing direct subsidy for residential rooftop solar. Applicable to on-grid systems installed by registered vendors.
				</p>
				<div class="space-y-1 text-sm text-muted-foreground">
					<div class="flex justify-between">
						<span>Up to 2 kW</span>
						<span class="font-medium text-foreground">Rs 30,000 / kW</span>
					</div>
					<div class="flex justify-between">
						<span>2 – 3 kW</span>
						<span class="font-medium text-foreground">Rs 18,000 / kW</span>
					</div>
					<div class="flex justify-between">
						<span>Above 3 kW</span>
						<span class="font-medium text-foreground">Max Rs 78,000</span>
					</div>
				</div>
			</div>

			<!-- State Subsidies — Coming Soon -->
			<div class="mt-6 flex items-start gap-3 rounded-lg bg-muted p-4">
				<Info class="w-5 h-5 text-primary shrink-0 mt-0.5" />
				<div>
					<p class="font-semibold text-sm">{selectedState} State Subsidy</p>
					<p class="text-sm text-muted-foreground">
						Top-up subsidy data for {selectedState} is coming soon. Some states offer additional subsidies on top of the central PM Surya Ghar scheme.
					</p>
				</div>
			</div>

			<!-- CTA -->
			<div class="mt-6 rounded-lg bg-primary/5 p-4">
				{#if selectedDistrictData && selectedDistrictData.installerCount > 0}
					<p class="text-sm text-muted-foreground mb-3">
						Based on our network, <strong class="text-foreground">{selectedDistrictData.installerCount} verified installers</strong> in
						<strong class="text-foreground">{selectedDistrictData.district}</strong> can install this system.
					</p>
					<a
						href={geoUrl("in", selectedDistrictData.stateSlug, selectedDistrictData.slug)}
						class="inline-flex items-center gap-2 bg-primary text-primary-foreground font-semibold px-6 py-2.5 rounded-lg hover:opacity-90 transition-opacity text-sm"
					>
						Get Quotes with Subsidy Applied <ArrowRight class="w-4 h-4" />
					</a>
				{:else}
					<p class="text-sm text-muted-foreground mb-3">
						Get exact quotes with subsidy applied from
						<strong class="text-foreground">{data.totalInstallers}+ verified installers</strong>.
					</p>
					<a
						href={countryUrl("in", "/get-quotes/")}
						class="inline-flex items-center gap-2 bg-primary text-primary-foreground font-semibold px-6 py-2.5 rounded-lg hover:opacity-90 transition-opacity text-sm"
					>
						Get Quotes with Subsidy Applied <ArrowRight class="w-4 h-4" />
					</a>
				{/if}
			</div>

			<!-- Related tools -->
			<div class="mt-4 flex flex-wrap gap-3 text-sm">
				<a href={contentUrl("/tools/solar-calculator/")} class="text-primary hover:underline">
					Calculate system size & cost
				</a>
				<span class="text-muted-foreground">|</span>
				<a href={contentUrl("/tools/emi-calculator/")} class="text-primary hover:underline">
					Calculate EMI
				</a>
			</div>
		</div>
	{/if}

	<!-- Authority links -->
	<div class="flex flex-wrap gap-3 text-sm mb-8">
		<a href={contentUrl("/solar-subsidy/how-to-apply/")} class="text-primary hover:underline">
			How to Apply for Solar Subsidy
		</a>
		<span class="text-muted-foreground">|</span>
		<a href={geoUrl("in")} class="text-primary hover:underline">Browse Installers</a>
	</div>

	<FAQ items={faqs} />
</div>

// apps/main-app-nextjs/components/tools/SubsidyChecker.tsx
/* eslint-disable-next-line no-restricted-syntax -- Interactive leaf. Five controls, two of them dependent selects, feeding an eligibility verdict that changes as they move. The page around it — the FAQ, the slab table's copy, both JSON-LD blocks — stays server-rendered. */
'use client';

/**
 * The subsidy checker's interactive half. Ported from
 * apps/main-app/src/routes/(layout-1)/tools/subsidy-checker/+page.svelte.
 *
 * It shares the slab table and the cost ladder with the solar calculator;
 * both now come from lib/tools/estimate.ts, where that file explains why two
 * copies of a published money figure was worth removing.
 *
 * `capture('subsidy_checked', …)` is dropped — no PostHog in this app.
 *
 * **One bug fixed in the port.** The state top-up callout reads
 * `{selectedState} State Subsidy`, and the state select starts empty with no
 * requirement to fill it — so anyone who checks a subsidy without choosing a
 * state gets a heading that begins with a space and a sentence reading "Top-up
 * subsidy data for  is coming soon." The block is now conditional on a state
 * having been picked, which is also the only case where it says anything.
 */
import { useState } from 'react';
import { capture } from '@/lib/analytics';
import Link from 'next/link';
import { ArrowRight, CircleCheck, CircleX, Info } from 'lucide-react';
import { BreakdownRow, Panel, ToolLinks } from './Panel';
import { RangeField, SelectField } from './Field';
import type { DistrictOption } from '@/lib/tools/data';
import { geoUrl } from '@/lib/directory/urls';
import { centralSubsidy, grossCost, rupees } from '@/lib/tools/estimate';

const CONNECTION_TYPES = [
  { value: 'residential', label: 'Residential' },
  { value: 'commercial', label: 'Commercial' },
  { value: 'institutional', label: 'Institutional' }
];

const GRID_OPTIONS = [
  { value: 'yes', label: 'Yes (On-Grid)' },
  { value: 'no', label: 'No (Off-Grid)' }
];

export function SubsidyChecker({
  districts,
  totalInstallers
}: {
  districts: DistrictOption[];
  totalInstallers: number;
}) {
  const [state, setState] = useState('');
  const [district, setDistrict] = useState('');
  const [systemSizeKw, setSystemSizeKw] = useState(3);
  const [connectionType, setConnectionType] = useState('residential');
  const [gridConnection, setGridConnection] = useState('yes');
  const [revealed, setRevealed] = useState(false);

  const states = [...new Set(districts.map((d) => d.state))].sort();
  const inState = state ? districts.filter((d) => d.state === state) : [];
  const chosen = districts.find((d) => d.state === state && d.district === district);

  const eligible = connectionType === 'residential' && gridConnection === 'yes';
  const subsidy = centralSubsidy(systemSizeKw, eligible);
  const cost = grossCost(systemSizeKw);

  const check = () => {
    setRevealed(true);
    capture('subsidy_checked', {
      system_size_kw: systemSizeKw,
      eligible,
      subsidy_amount: subsidy,
      net_cost: cost - subsidy,
      state
    });
  };

  /** Both conditions are reported, not just the first — a commercial off-grid
      system fails on two counts and fixing one of them does not help. */
  const reasons = [
    connectionType !== 'residential' && 'Central subsidy is only for residential connections.',
    gridConnection !== 'yes' && 'Central subsidy requires a grid-connected (on-grid) system.'
  ].filter((r): r is string => Boolean(r));

  return (
    <>
      <Panel title="Check Your Subsidy Eligibility">
        <div className="grid grid-cols-1 gap-lg md:grid-cols-2">
          <SelectField
            label="State"
            value={state}
            placeholder="Select state"
            options={states.map((s) => ({ value: s, label: s }))}
            onChange={(v) => {
              setState(v);
              setDistrict('');
            }}
          />

          <SelectField
            label="District"
            value={district}
            placeholder="Select district"
            disabled={!state}
            options={inState.map((d) => ({ value: d.district, label: d.district }))}
            onChange={setDistrict}
          />

          <SelectField
            label="Connection Type"
            value={connectionType}
            options={CONNECTION_TYPES}
            onChange={setConnectionType}
          />

          <SelectField
            label="Grid Connection"
            value={gridConnection}
            options={GRID_OPTIONS}
            onChange={setGridConnection}
          />

          <div className="md:col-span-2">
            <RangeField
              label="System Size"
              value={systemSizeKw}
              readout={`${systemSizeKw} kW`}
              min={1}
              max={10}
              step={0.5}
              hint="1 kW – 10 kW"
              onChange={setSystemSizeKw}
            />
          </div>
        </div>

        <button type="button" onClick={check} className="btn btn-primary mt-lg w-full">
          Check Subsidy
        </button>
      </Panel>

      {revealed ? (
        <Panel title="Subsidy Details">
          {/* role="status": the verdict is the answer to the button press, and
              it appears above the fold of the panel rather than where focus
              is, so it has to be announced. */}
          <div
            role="status"
            className={`flex items-start gap-sm rounded-md border p-md ${
              eligible
                ? 'border-success bg-success-surface'
                : 'border-danger bg-danger-surface'
            }`}
          >
            {eligible ? (
              <CircleCheck aria-hidden className="mt-2xs h-5 w-5 shrink-0 text-success" />
            ) : (
              <CircleX aria-hidden className="mt-2xs h-5 w-5 shrink-0 text-danger" />
            )}
            <div>
              <p className="font-semibold text-ink">
                {eligible
                  ? 'Eligible for PM Surya Ghar Subsidy'
                  : 'Not Eligible for Central Subsidy'}
              </p>
              {eligible ? (
                <p className="text-sm text-ink-muted">
                  Your system qualifies for the central government subsidy.
                </p>
              ) : (
                reasons.map((reason) => (
                  <p key={reason} className="text-sm text-ink-muted">
                    {reason}
                  </p>
                ))
              )}
            </div>
          </div>

          <dl className="mt-lg divide-y divide-line border-t border-line pt-xs">
            <BreakdownRow label="System Size" value={`${systemSizeKw} kW`} />
            {/* Full figures, not the abbreviated form the tiles use. The
                SvelteKit page abbreviates past a lakh here too, so it prints
                "Rs 1.6 Lakh" minus "Rs 78,000" leaving "Rs 87,000" — three
                numbers that visibly do not add up. A breakdown's whole job is
                that the reader can check the subtraction. */}
            <BreakdownRow label="Estimated System Cost" value={rupees(cost)} />
            <BreakdownRow
              label="Central Subsidy (PM Surya Ghar)"
              value={subsidy > 0 ? `- ${rupees(subsidy)}` : 'Not applicable'}
              tone={subsidy > 0 ? 'credit' : 'plain'}
            />
            <BreakdownRow
              label="Net Cost (after subsidy)"
              value={rupees(cost - subsidy)}
              tone="total"
            />
          </dl>

          {/* The state top-up. Only shown once a state has been chosen — see
              the file header. `state_subsidies` is empty in every status, so
              "coming soon" is the honest thing to say and there is nothing to
              query. */}
          {state ? (
            <div className="mt-lg flex items-start gap-sm rounded-md bg-surface-sunken p-md">
              <Info aria-hidden className="mt-2xs h-5 w-5 shrink-0 text-action" />
              <div>
                <p className="text-sm font-semibold text-ink">{state} State Subsidy</p>
                <p className="text-sm text-ink-muted">
                  Top-up subsidy data for {state} is coming soon. Some states offer additional
                  subsidies on top of the central PM Surya Ghar scheme.
                </p>
              </div>
            </div>
          ) : null}

          <div className="mt-lg rounded-md bg-accent-surface p-md">
            {chosen && chosen.installerCount > 0 ? (
              <>
                <p className="text-sm text-ink-muted">
                  Based on our network,{' '}
                  <strong className="font-semibold text-ink">
                    {chosen.installerCount} verified installers
                  </strong>{' '}
                  in <strong className="font-semibold text-ink">{chosen.district}</strong> can
                  install this system.
                </p>
                <a
                  href={geoUrl('in', chosen.stateSlug, chosen.slug)}
                  className="btn btn-primary btn-sm mt-sm"
                >
                  Get Quotes with Subsidy Applied <ArrowRight aria-hidden className="h-4 w-4" />
                </a>
              </>
            ) : (
              <>
                <p className="text-sm text-ink-muted">
                  Get exact quotes with subsidy applied from{' '}
                  <strong className="font-semibold text-ink">
                    {totalInstallers}+ verified installers
                  </strong>
                  .
                </p>
                <Link href="/in/get-quotes" className="btn btn-primary btn-sm mt-sm">
                  Get Quotes with Subsidy Applied <ArrowRight aria-hidden className="h-4 w-4" />
                </Link>
              </>
            )}
          </div>

          <div className="mt-md">
            <ToolLinks
              links={[
                { label: 'Calculate system size & cost', href: '/tools/solar-calculator' },
                { label: 'Calculate EMI', href: '/tools/emi-calculator' }
              ]}
            />
          </div>
        </Panel>
      ) : null}
    </>
  );
}
