// apps/main-app/src/lib/components/chat/widgets/GenericToolDisplay.svelte
<script lang="ts">
  import WidgetShell from "./WidgetShell.svelte";
  import { humanizeToolName } from "../format";

  let { toolName, data }: { toolName: string; data: any } = $props();

  // Fallback for tools that have no bespoke card yet. Guard the stringify so a
  // circular payload can't throw during render.
  let pretty = $derived.by(() => {
    try {
      return JSON.stringify(data, null, 2);
    } catch {
      return String(data);
    }
  });
</script>

<WidgetShell emoji="🔧" title={humanizeToolName(toolName)}>
  <pre class="text-xs overflow-x-auto p-[theme(--form-element-field-gap)] rounded-[theme(--radius-md)] bg-[hsl(var(--card))] border border-[hsl(var(--border))] text-[hsl(var(--foreground))]"><code>{pretty}</code></pre>
</WidgetShell>

// apps/main-app-nextjs/components/chat/widgets/GenericToolDisplay.tsx
import { humanizeToolName } from '@/lib/chat/format';
import { WidgetShell, type ToolData } from './parts';

/** Fallback for a tool with no card of its own: the raw payload. */
export function GenericToolDisplay({ toolName, data }: { toolName: string; data: ToolData }) {
  let pretty: string;
  try {
    pretty = JSON.stringify(data, null, 2);
  } catch {
    pretty = String(data);
  }
  return (
    <WidgetShell emoji="🔧" title={humanizeToolName(toolName)}>
      <pre className="overflow-x-auto rounded-md border border-line bg-surface p-xs text-xs">
        <code>{pretty}</code>
      </pre>
    </WidgetShell>
  );
}
