// apps/main-app/src/lib/in/components/chat/widgets/KnowledgeBaseDisplay.svelte
<script lang="ts">
  import { Badge } from "$lib/components/ui/badge";
  import WidgetShell from "./WidgetShell.svelte";

  let { data }: { data: any } = $props();

  let related = $derived(Array.isArray(data?.related) ? data.related : []);
</script>

<WidgetShell emoji="📚" title={data.title}>
  <!-- Knowledge-base content is plain text, not markdown — render as text, not @html. -->
  <p class="text-sm text-[hsl(var(--foreground))] break-words whitespace-pre-line">{data.content}</p>

  {#if related.length}
    <div class="flex flex-col gap-[theme(--form-element-field-gap)]">
      <p class="text-xs font-semibold text-[hsl(var(--muted-foreground))]">Related topics</p>
      <div class="flex flex-wrap gap-[theme(--form-element-field-gap)]">
        {#each related as topic}
          <Badge variant="outline">{topic}</Badge>
        {/each}
      </div>
    </div>
  {/if}
</WidgetShell>

// apps/main-app-nextjs/components/chat/widgets/KnowledgeBaseDisplay.tsx
import { Badge, WidgetShell, type ToolData } from './parts';

export function KnowledgeBaseDisplay({ data }: { data: ToolData }) {
  const related: string[] = Array.isArray(data.related) ? data.related : [];
  return (
    <WidgetShell emoji="📚" title={data.title}>
      {/* Plain text, not markdown. */}
      <p className="text-sm break-words whitespace-pre-line">{data.content}</p>
      {related.length > 0 && (
        <div className="flex flex-col gap-xs">
          <p className="text-xs font-semibold text-ink-muted">Related topics</p>
          <div className="flex flex-wrap gap-xs">
            {related.map((topic) => (
              <Badge key={topic}>{topic}</Badge>
            ))}
          </div>
        </div>
      )}
    </WidgetShell>
  );
}
