// apps/main-app/src/lib/in/components/chat/widgets/ToolResultDisplay.svelte
<script lang="ts">
  import QuotationDisplay from "./QuotationDisplay.svelte";
  import RoiDisplay from "./RoiDisplay.svelte";
  import BookingDisplay from "./BookingDisplay.svelte";
  import SystemSizeDisplay from "./SystemSizeDisplay.svelte";
  import SubsidyDisplay from "./SubsidyDisplay.svelte";
  import CadDrawingDisplay from "./CadDrawingDisplay.svelte";
  import KnowledgeBaseDisplay from "./KnowledgeBaseDisplay.svelte";
  import LeadFormCard from "./LeadFormCard.svelte";
  import GenericToolDisplay from "./GenericToolDisplay.svelte";

  let { toolExecuted, toolResult }: { toolExecuted: string; toolResult: any } = $props();

  // Tools that run purely for the model's benefit — rendering their raw output
  // would just be noise for the user.
  const INTERNAL_TOOLS = ["collect_customer_info", "scrape_website"];
</script>

{#if toolResult && !INTERNAL_TOOLS.includes(toolExecuted)}
  {#if toolExecuted === "generate_quotation"}
    <QuotationDisplay data={toolResult} />
  {:else if toolExecuted === "calculate_roi"}
    <RoiDisplay data={toolResult} />
  {:else if toolExecuted === "book_site_visit"}
    <BookingDisplay data={toolResult} type="site_visit" />
  {:else if toolExecuted === "offer_lead_form"}
    <LeadFormCard data={toolResult} />
  {:else if toolExecuted === "calculate_system_size"}
    <SystemSizeDisplay data={toolResult} />
  {:else if toolExecuted === "check_subsidies"}
    <SubsidyDisplay data={toolResult} />
  {:else if toolExecuted === "generate_cad_drawing"}
    <CadDrawingDisplay data={toolResult} />
  {:else if toolExecuted === "search_knowledge_base"}
    <KnowledgeBaseDisplay data={toolResult} />
  {:else}
    <GenericToolDisplay toolName={toolExecuted} data={toolResult} />
  {/if}
{/if}

// apps/main-app-nextjs/components/chat/widgets/ToolResultDisplay.tsx
/**
 * The card for a tool the agent ran during a reply, picked by tool name.
 * A tool with no card of its own falls back to its raw payload.
 */
import { BookingDisplay } from './BookingDisplay';
import { CadDrawingDisplay } from './CadDrawingDisplay';
import { GenericToolDisplay } from './GenericToolDisplay';
import { KnowledgeBaseDisplay } from './KnowledgeBaseDisplay';
import { LeadFormCard } from './LeadFormCard';
import type { ToolData } from './parts';
import { QuotationDisplay } from './QuotationDisplay';
import { RoiDisplay } from './RoiDisplay';
import { SubsidyDisplay } from './SubsidyDisplay';
import { SystemSizeDisplay } from './SystemSizeDisplay';

// Tools that run for the model's benefit only; their output is noise to the visitor.
const HIDDEN_TOOLS = ['collect_customer_info', 'scrape_website'];

export const hasToolCard = (tool: string | undefined): tool is string =>
  !!tool && !HIDDEN_TOOLS.includes(tool);

export function ToolResultDisplay({ tool, result }: { tool: string; result: ToolData }) {
  if (!result || !hasToolCard(tool)) return null;
  switch (tool) {
    case 'generate_quotation':
      return <QuotationDisplay data={result} />;
    case 'calculate_roi':
      return <RoiDisplay data={result} />;
    case 'book_site_visit':
      return <BookingDisplay data={result} />;
    case 'offer_lead_form':
      return <LeadFormCard data={result} />;
    case 'calculate_system_size':
      return <SystemSizeDisplay data={result} />;
    case 'check_subsidies':
      return <SubsidyDisplay data={result} />;
    case 'generate_cad_drawing':
      return <CadDrawingDisplay data={result} />;
    case 'search_knowledge_base':
      return <KnowledgeBaseDisplay data={result} />;
    default:
      return <GenericToolDisplay toolName={tool} data={result} />;
  }
}
